### ISSUE TITLE
Drop support for some features in sub-loggers

### ISSUE THREAD

**Issue by tsimbalar** [serilog/serilog#1032]
While working on an issue in order to *honor* overrides configuration in *sub-loggers* (`Logger.WriteToLogger(...)` methods see #967 ) and going around the API and use cases (see https://github.com/serilog/serilog/pull/1027#issuecomment-331361672) , it turns out that maybe such a feature should not be supported.

I may be wrong, but I see at least 2 features that do not make much sense in sub-loggers : 
- the whole `LoggerConfiguration.ReadFrom`, because I can not imagine a scenario where the config from the sublogger would be loaded from somewhere else
- the `LoggerConfiguration.MinimumLevel.Overrides()` methods considering that `Filters` would probably be more appropriate

Now, the question is, if the feature is not supported, how should we make it obvious to the user that such a feature is not supported ? 

I can see several options : 
1. making the call throw a `UnsupportedException` when issued on a *sub-logger*
2. change the call to be a *no-op* but write something to the `SelfLog` to tell the user that the feature is not supported and its configuration will not be taken into account
3. marking the method as `Obsolete` and advising another workaround
4. marking it as not `EditorBrowsable` so that it is not suggested in *intellisense*
5. removing the calls from the API

- **Option 1** seems a bit extreme, and will cause some codebases to start failing at runtime when everything was just fine so far ...
- **Option 2** is a bit better, but there's a chance that nobody will ever see the message in the `SelfLog`
- **Option 3** would be nice in for a new *minor* version as it would give the users some time to migrate but would not break code straight away 
- **Option 4** is compatible with option 3
- **Option 5** would be nice for the next *major* version, it's definitely a **breaking** change

So I would like to suggest to follow **option 3** + **option 4** in the next minor versions in order to prepare for **option 5** in the next major version.

What do you think ? Are there more features that should not be exposed on sub-loggers ? 

*I do have some kind of ugly proof of concept of what a code-compatible but not binary-compatible version would look like in order to hide `MinimumLevel.Overrides` from sub-loggers here : https://github.com/tsimbalar/serilog/commit/21f9d503a9e83cc06c7c0dc3493c6dcf3f9e72a1*

**Comment by nblumhardt** [comment]
Thanks for writing up the options :+1:

I think `ReadFrom()` could appear in valid sub-logger scenarios, but it'd be esoteric usage. If it functions correctly, I think it'd be fine to leave on the API unless it costs us in complexity.

Any change to the types used in the configuration process (e.g. introducing `SubLogger*Configuration` so that we have somewhere to put the attributes), will be a binary breaking change somewhere, so I think that constrains the approach within 2.x a bit.

Just looking at the short term (3.x is not in the near future :-)), perhaps option 2, or combining option 2 with your open PR, could be another valid way to go? I.e. make a best-effort attempt to support it, but write to SelfLog warning that it will act only as a filter?

Feel like I need a bit more time to think it through...

**Comment by tsimbalar** [comment]
OK, I was not sure if binary-breaking changes were acceptable as long as we keep source-compatibility... 

So yes, the comments on the PR seem like the way to go, and maybe mentioning somewhere in the documentation that sub-logger overrides are kind of discouraged, or that the behaviour may be surprising.
