### ISSUE TITLE
Support for LogEventLevel.HigherThanFatal

### ISSUE THREAD

**Issue by tsimbalar** [serilog/serilog#1049]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x] New Feature

Currently, one can easily control how much noise is generated by Serilog, using several hooks in the `LoggerConfiguration`, for instance : 
- `MinimumLevel.Fatal()`
- `MinimimLevel.Override("System.Data", LogEventLevel.Fatal)`
- `WriteTo.SomeSink(restrictedToMinimumLevel: LogEventLevel.Fatal)`
- `LoggingLevelSwitch.MinimumLevel = LogEventLevel.Fatal;`
- the equivalent syntax for settings (*xml* / *json* ...)

... but I believe that all these APIs can "block" events with a level `< Fatal`, but *Fatal* events will always be logged. 

It would be useful to be able to specify a level ***Higher than Fatal*** that would allow to effectively complete disable a branch of the logging pipeline.

This would be useful to : 
- disable a sink (temporarily or not), for instance from a config file
- define a common configuration for several environments, but disable it by changing only one setting in another (instead of completely removing the several settings that added that sink) 

I'l not really sure if it should come as a new `enum` member for `LogEventLevel` or a more explicit `Disabled` flag ... or even how it should be named .... but anyway ... does anyone else think that could be useful ?

This kind of stuff has been requested in issues like #1048 , serilog/serilog-settings-configuration#70 , serilog/serilog-sinks-seq#87 , serilog/serilog-sinks-rollingfile#44

**Comment by nblumhardt** [comment]
:+1: worthwhile discussion to have.

I think this would be called `LogEventLevel.Off` to match conventions in other frameworks. It would have to be a member of `LogEventLevel` in order to work in all the places levels can currently be specified - we could go through and add `disabled` flags, but then the convenience of just flipping some existing level configuration is lost.

The key issues are to:

 * ensure it's impossible or very difficult to create a `LogEvent` with the level `Off`; unless we start adding `if` checks everywhere, one could still create an `Off` event and have it traverse the pipeline
 * make sure there are no scenarios where `switch` statements in Serilog or client code would fall through to a previously unreachable case

Neither is a _huge_ issue, but the first one doesn't quite sit comfortably with me (it's the original reason for no `Off` member). On the other hand - turning logging off by not adding sinks or configuring the pipeline _is_ semantically correct :-)

Just trying to think through other ways to address the scenario, I think it's fair to assert that when this issue is raised, it's almost always in relation to runtime configuration.

Perhaps, if that's the case, more ubiquitous support for filters and https://github.com/serilog/serilog-filters-expressions might be the answer?

I.e. to turn Serilog off at runtime via configuration, one could use:

```xml
<add key="serilog:filter:ByIncludingOnly.expression" value="false" />
```

There's also `LoggingFilterSwitch` in the same package, for the equivalent to `LoggingLevelSwitch`.

I don't know exactly what it would mean to push this as the alternative - it already exists, but it's not super-discoverable and needs an additional package. Thoughts?

**Comment by tsimbalar** [comment]
@nblumhardt I hadn't thought about the `filter` alternative. That sounds like a good way ... although, for an app that is already deployed in production but dot deployed with the proper dlls/packages, I believe specifying it in the config file would not work, or maybe even crash the app 😞 

I do agree that it doesn't really make any sense in scenarios other than via the *configuration* APIs and also the best way to *disable* something is to *not add it* in the first place 😃 , so maybe that's something to think about in the *configuration*/*appsettings* packages but that should not impact the *Core* repo. In the *xml* side, Config Transforms can handle the removal quite well, but I believe the `Microsoft.Extensions.Configuration` is *add-only* ...

I can't help myself from thinking that this could also be considered as part of the *Combined* settings thing ... , but well *when all you have is a hammer, everything looks like a nail*  ... 

But maybe allowing to **remove** defined *key-value* settings when combining several configs like : 

```csharp
new LoggerConfiguration()
  .ReadFrom.Combined(b => 
    b.AddExpression(....)
    b.AddKeyValuePairs(....)
    b.RemoveKeys("write-to:File:*")
    );
```

so that the sink is not actually added in the end ... 

... or directly in the *key-value* settings format, allow to indicate **removal** instead of **addition**
```xml
<add key="serilog:remove" key="write-to:File:*,minimum-level:override:*" />
```
... not a fan of having the word `remove` in the middle of a xml element named `<add>` but 😔  ...

**Comment by skomis-mm** [comment]
Another issue with introducing `Off` level is that sinks should be adjusted to lazy initialize so they won't introduce unwanted side effects. Some sinks have this (`RollingFile`), but I beleive most of them are not (`File`, `Async` etc).

For the `json` there is also a way using [jdt](https://blogs.msdn.microsoft.com/visualstudio/2017/05/25/whats-new-and-improved-with-the-slowcheetah-extension/) [transforms](https://github.com/Microsoft/json-document-transforms/wiki) to handle scenarios where different environments should have different configurations. 

For scenarios when suppressing is temporary I believe `Fatal` should be enough. Who wants to suppress `Fatal` events anyway? :)

**Comment by tsimbalar** [comment]
The more I think about this one, the more I think this feature is not worth the added complexity and risk :) 

Closing it, and we'll reopen if we need to :p

**Comment by jez9999** [comment]
What a dreadful resolution to this issue.  "Too risky, can't be bothered".

ASP.NET Core has "None" as an option by default.  This attitude makes me reconsider whether using Serilog is worth it.

**Comment by nblumhardt** [comment]
Our community has been able to achieve big things through constructive engagement; unfortunately, the tone of your comment makes it unlikely any of the volunteers here will take time out to help you.

If this issue is important to you, working through the analysis above and providing some insight into:

 - why the workaround is unsuitable,
 - how the challenges can be overcome, and
 - how risks to downstream consumers can be mitigated,

would be the way to move this forward.

**Comment by filipw** [comment]
> Who wants to suppress `Fatal` events anyway? :)

I don't think it's that uncommon. An example - a framework/library logs exceptions as fatal using a dedicated logger name and then rethrows. Since they are rethrown, they end up being application unhandled exceptions so they get logged again by the host application.

Having an option to complete mute logs coming from the library by this specific logger name name with e.g. `LogEventLevel.Off` (especially as Microsoft.Extensions.Logging has `None`) would make it very simple and symmetrical to MEL. Yes there are other ways of achieving this, but it would be nice to just have 1-to-1 parity in log levels between MEL and Serilog.

**Comment by AraHaan** [comment]
I do not get why Serilog does not use MEL's LogLevel enum which would make it less code for them to maintain.

**Comment by cocowalla** [comment]
> The reasoning is that we are using a logging SAAS and we have to pay for the logs

> While this maybe possible via a filter or other hoop

It's absolutely possible with a filter, which TBH I don't consider a "hoop" at all, especially since it's ijust one additional line of code - I do this is production for a more complex use case and, it works just fine.

In your specific case though, there are simpler and more obvious options:

1. Simply don't configure the SaaS logging sink in your `Develop` environment - this is certainly the simplest and most obvious way to do it, and indeed is the way I've done it on every single project I've ever worked on that uses such sinks

2. In your `Develop` environment, set the minimum log level for the SaaS sink to `Fatal` - I imagine logs at that level are extremely rare

**Comment by jez9999** [comment]
Thankfully I'm no longer working in my job where we were using Serilog.  My attitude in future toward which logging framework we use given Serilog's nonstandard log levels and stubborn refusal to introduce useful new ones will be simple: don't use Serilog.

**Comment by AraHaan** [comment]
I agree, we should start looking into implementing our own system similar to serilog but have it integrate directloy into MEL and provide built in support for what all of serilog's sinks and enricher's support.

**Comment by nblumhardt** [comment]
@jez9999 honestly, that's absolutely fine. It'd be weird if Serilog had some kind of mandate for everyone to like it and agree with its "one true way" of doing things. There are other good options out there, hopefully one fits your requirements.

@AraHaan that's also great! Please do.

Others on this thread, I'm going to lock it because unfortunately it seems to be generating noise without moving anything forward.

The original resolution to this issue was that there's some risk involved, and that we'd reopen if necessary. If anyone is prepared to work through the implications of adding `Off` **rigorously**, working through a variety of libraries and ecosystem components, and writing up how they might be affected, this would be welcome in a new issue/proposal.

The kinds of things I mean are:

 * Points in https://github.com/serilog/serilog/issues/1049#issuecomment-338051356
 * Components that format levels - like sinks, expression templates, etc.; which sinks will crash or behave badly if they receive an event with the `Off` level?
 * Components that parse levels - what if anything would we need to do in Serilog.Settings.Configuration and elsewhere?
 * What would be the performance impact of enforcing that no `LogEvent` could be written through the pipeline with a level of `Off`? (Could we elide the check on code paths where we know the incoming level has already been determined to be enabled)?
 * Would any changes be needed in any other APIs that accept levels (not just `ILogger`)?

If the work and risk can be properly quantified then we might have a better basis to justify making changes, here.
