### ISSUE TITLE
Capturing the property value threw an exception: InvalidCastException

### ISSUE THREAD

**Issue by sleemer** [serilog/serilog#1061]
Test environment:
- Serilog 2.5.0
- MacOS Sierra 10.12.6
- .Net Core 2.0.2

Code:
```csharp
Log.Logger = new LoggerConfiguration()
      .Destructure.ByTransformingWhere<Type>(
          type => true, 
          type => new { FullName = type.FullName })
      .WriteTo.Console()
      .CreateLogger();

Log.Information("{@Type}", typeof(string));
```

Expected behavior:
[13:19:38 INF] {FullName = System.String}

Actual behavior:
[13:21:53 INF] Capturing the property value threw an exception: InvalidCastException

Repo with example:
https://github.com/sleemer/serilog.bug.destructuring

**Comment by nblumhardt** [comment]
Thanks, looks like we need to investigate 👍

**Comment by adamchester** [comment]
This is probably an issue with the method signature being confusing. Even now, it's surprising to me that specifying `Destructure.ByTransformingWhere<Type>(...)` does not actually restrict the _destructuring_ to *only* instances of `Type`, even though there's no way the transformation is going to succeed unless it is an instance `System.Type` or derived.

@sleemer, could you confirm please, what you wanted to do was something like this below?

```csharp
[Fact]
public void DestructureByTransformingWhereOnlyAppliesThePredicateAlways()
{
    var events = new List<LogEvent>();
    var sink = new DelegatingSink(events.Add);

    var log = new LoggerConfiguration()
        .Destructure.ByTransformingWhere<Type>(
            predicate: type => typeof(Type).IsAssignableFrom(type),
            transformation: type => new { FullName = type.FullName })
        .WriteTo.Sink(sink)
        .CreateLogger()
        .ForContext<LoggerTests>();

    log.Information("{@Type}", typeof(string));

    Assert.Equal(1, events.Count);
    var evt = events.Single();
    Assert.Equal("{ FullName = \"System.String\" }", evt.RenderMessage());
}
```

I'm still considering what is the best way to address this. Probably the best option is to always ensure the value being destructured is _assignable from_ the `TValue` typeparam.

**Comment by sleemer** [comment]
@adamchester I'm not sure that this is related to the method signature. My original idea was to write ```csharp
.Destructure.ByTransforming<Type>(type => new { FullName = type.FullName })
```
but it wasn't even called.
I also tried this method with another type's parameters, but it doesn't work either...
```csharp
.Destructure.ByTransforming<List<int>>(list => new { Count = list.Count })
```
... and got the same exception as I described above - InvalidCastException

**Comment by adamchester** [comment]
@sleemer 

```csharp
.Destructure.ByTransforming<Type>(type => new { FullName = type.FullName })
```

does not work because, unfortunately, it's implemented by an exact type match (`System.Type` in this case). That condition is never true, because at runtime the instances are actually of something *derived* from `System.Type`.

```csharp
.Destructure.ByTransforming<List<int>>(list => new { Count = list.Count })
```

This seems to work, can you provide any more details on this one? I tested with:

```csharp
log.Information("{@List}", new[] { 1, 2, 3, }.ToArray().ToList());
```

**Comment by sleemer** [comment]
@adamchester you are right,

```csharp
.Destructure.ByTransforming<List<int>>(list => new { Count = list.Count })
```

it works. Previously I was getting the error because I had the following configuration

```csharp
Log.Logger = new LoggerConfiguration()
   .Destructure.ByTransformingWhere<Type>(type => true, type => new { FullName = type.FullName })
   .Destructure.ByTransforming<List<int>>(list => new { Count = list.Count })
   .WriteTo.Console()
   .CreateLogger();
```
but after deleting  

```csharp
Destructure.ByTransformingWhere<Type>(type => true, type => new { FullName = type.FullName })
```
it started to work. I assume that was due to destructuring pipeline, when it failed at first statement.

**Comment by adamchester** [comment]
Hey @sleemer, I'm just confirming if you agree that `ByTransformingWhere` can be made behave the way you need using something like:

```csharp
.Destructure.ByTransformingWhere<Type>(
    predicate: type => typeof(Type).IsAssignableFrom(type),
    transformation: type => new { FullName = type.FullName })
```

instead of using a `predicate` that always returns `true`?

Earlier in this issue, I suggested that `Destructure.ByTransformingWhere` can sometimes be rather confusing. Do you have any suggestions for how we could improve this?

**Comment by sleemer** [comment]
Hi @adamchester, thanks for your help. I can confirm that it works as I need. My initial problem was that I expected that when you use ByTransforming<T> it would be called only for types T, but now I think that using predicate is more convenient.

**Comment by adamchester** [comment]
Thanks

**Comment by luthrayatin** [comment]
Hi,

I'm facing a related issue (I hope) with destructuring in Serilog. Whenever I use @ to log my entry as a destructured object, the log entry shows up with the text: "Capturing the property value threw an exception" instead of the destructured object. I've tried this with multiple object types.

Example: 
_logger.Debug("DbContexts: {@DbContexts}", dbContexts);
gave me:
DbContexts: Capturing the property value threw an exception: FileNotFoundException

but when I changed my code to:
_logger.Debug("DbContexts: {DbContexts}", dbContexts);
I received this in the log file:
DbContexts: ["Delegation.Persistence.SqlDbContext"]

Can you guys look into this and help me understand what might be going on?

Here are the Serilog and sink packages from my package.config:
<package id="Serilog" version="2.7.1" targetFramework="net462" />
  <package id="Serilog.Enrichers.Thread" version="3.0.0" targetFramework="net462" />
  <package id="Serilog.Formatting.Compact" version="1.0.0" targetFramework="net462" />
  <package id="Serilog.Settings.AppSettings" version="2.2.2" targetFramework="net462" />
  <package id="Serilog.Sinks.Console" version="3.1.1" targetFramework="net462" />
  <package id="Serilog.Sinks.File" version="4.0.0" targetFramework="net462" />
  <package id="Serilog.Sinks.Literate" version="3.0.0" targetFramework="net462" />
  <package id="Serilog.Sinks.PeriodicBatching" version="2.1.1" targetFramework="net462" />
  <package id="Serilog.Sinks.Seq" version="4.0.0" targetFramework="net462" />

**Comment by nblumhardt** [comment]
Hi @luthrayatin - the behavior your seeing is by design, the `SqlDbContext` type you're destructuring isn't built with serialization in mind, and one or more of its properties is throwing an exception when Serilog tries to read the value to include in the event.

Picking off individual parts of the DB context to include in the event would be a quick workaround.

**Comment by luthrayatin** [comment]
Thank you @nblumhardt. Like I said in my comment, I've tried this with multiple types, not just DbContexts, I've tried with custom types as well.

For example:
Here:
`Logger.Information("{EventType} received: {@EventData}", nameof(TransactionOccurredEvent), evt);`

and the type:
```
public class TransactionOccurredEvent{
        public TransactionDetails Transaction { get; set; }
        public TokenisedTransactionDetails MastercardTokenisedTransaction { get; set; }
}
```

And, the result in the log is:

> TransactionOccurredEvent received: Capturing the property value threw an exception: FileNotFoundException

**Comment by nblumhardt** [comment]
Thanks @sleemer - sorry I missed that aspect of your earlier message.

This will still most likely be caused by calling a property getter, rather than by Serilog itself. My bet is that there's an assembly (`.dll`) missing from your application, and while the code you're calling in the app doesn't touch any of the types from that assembly, a property that's able to be reached by navigating through these particular types is causing the runtime to try to load that assembly and a `FileNotFound` exception is resulting.

My guess, anyway :-)

Here's the line of code that is throwing the exception:

https://github.com/serilog/serilog/blob/dev/src/Serilog/Capturing/PropertyValueConverter.cs#L339

You can see a few lines further down that the full exception details will be written to [SelfLog](https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics), so checking there should clear it up.

**Comment by luthrayatin** [comment]
@nblumhardt Thank you for showing me the point of failure. I'm working on the code trying to figure this out. If I can't get it to work, I'll try to create a repro with a simple type and let you know what I find.

**Comment by HairyPorker** [comment]
@nblumhardt I have similar issue with @luthrayatin.
'Capturing the property value threw an exception: FileNotFoundException' 
I tried to manually serialize the object with JsonConvert to Json string before passing to the logger, and it works. Seems the issue is from the build in serializer inside the deconstructor.
