### ISSUE TITLE
I can't open/build Serilog with latest VS/.NET tooling

### ISSUE THREAD

**Issue by trullock** [serilog/serilog#1071]
I can't open the solution (or its projects, rather) with the latest VS2017, because of the hardcoded old SDK version, and then problems with Linq references if I update/remove the legacy SDK version.

Its unclear how I should modify the target frameworks as its unclear what the desired level of support is.

The test projects have strange (inconsistent) target frameworks.

If someone tells me what to do I'm happy to do it and PR

**Comment by nblumhardt** [comment]
Installing the SDK from the .NET SDK download page will fix this; 👍 to a tooling update if you're keen to update everything for the latest 2.x SDK (issues like references can take a bit of careful unpicking). In particular, care needs to be taken not to introduce new blanket .NET Standard package references for .NET Framework targets, we've done quite a bit of work to get around the implicit framework references in the past.

The test project targets could definitely be rationalized; since test times aren't currently significant, it'd be great to expand _Serilog.Tests_ from:

```xml
<TargetFrameworks>netcoreapp1.0;net452;net46</TargetFrameworks>
```

to:

```xml
<TargetFrameworks>netcoreapp1.0;netcoreapp1.1;netcoreapp2.0;net452;net462;net47</TargetFrameworks>
```

Thanks for the help!
Nick

**Comment by trullock** [comment]
Should we be making any changes to the main serilog targets?>

**Comment by trullock** [comment]
Whats the reasoning for 

    
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>

**Comment by nblumhardt** [comment]
> Should we be making any changes to the main serilog targets?

I don't think so, no.

> Whats the reasoning for ... `<DisableImplicitFrameworkReferences>`

Without it, consumers on .NET Framework end up pulling in large numbers of unnecessary reference assemblies (packages).

**Comment by nblumhardt** [comment]
This went in with https://github.com/serilog/serilog/pull/1091 - thanks for pushing it along 👍
