### ISSUE TITLE
Unexpected behavior when combining explicit properties with log context properties

### ISSUE THREAD

**Issue by pardahlman** [serilog/serilog#1080]
**A few questions before you begin:**

> Is this an issue related to the Serilog core project or one of the [sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks) or [community projects](https://github.com/serilog/serilog/wiki/Community-Projects).  This issue list is intended for Serilog core issues. If this issue relates to a sink or related project, please log on the related repository.  Please use [Gitter chat](https://gitter.im/serilog/serilog) and [Stack Overflow](http://stackoverflow.com/questions/tagged/serilog)  for discussions and questons.

**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug
- [ ] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**

Serilog, version 2.6.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [ ] netCore 2.0
- [ ] netCore 1.0
- [x] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**

I have configured Serilog with the LogContext enricher. When capturing a log entry that combines properties provided explicitly (from call site) with properties from the log context I get an unexpected behavior:

If the message template references an explicit property after a property from the log context, the properties are not correctly matched. This is perhaps best described by an example

```csharp
var logger = new LoggerConfiguration()
    .Enrich.FromLogContext()
    .WriteTo.Debug()
    .CreateLogger();

using (LogContext.PushProperty("propOne", "valueOne"))
{
    logger.Information("propOne has value {propOne}"); // (1)
    logger.Information("propTwo has value {propTwo}, propOne has value {propOne}", "valueTwo"); // (2)
    logger.Information("propOne has value {propOne} propTwo has value {propTwo}", "valueTwo");  // (3)
}
```

_(1)_ works as expected, it captures _propOne has value valueOne_

_(2)_ works, that is it captures _propTwo has value valueTwo, propOne has value valueOne_. However, the self logger outputs _Named property count does not match parameter count: propTwo has value {propTwo}, propOne has value {propOne}_

_(3)_ is unsuccessfully captured: _propOne has value valueTwo propTwo has value {propTwo}_ and the self logger outputs _Named property count does not match parameter count: propOne has value {propOne} propTwo has value {propTwo}_

**Please describe the expected behavior?**

I would expect _(2)_ and _(3)_ to succeed without any output to the self log.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

See above.

**Comment by IanYates** [comment]
It's working as designed.

I can see why you're looking for the functionality you describe, but if it was to match properties in that way things could get rather brittle in your codebase.  Picture you have an ASP.NET site and, somewhere in your pipeline, you decide to add a LogContext.Push() call so that every log event for the call now has `userId` being logged.

However, 6 months ago you, or some teammate, already added some log messages for some process on the admin screen governing the creation of new user accounts.  Part of the log message includes a placeholder for something you're going to log as `userId`.  Suddenly you've broken your logging code in a subtle way

**Comment by pardahlman** [comment]
Thanks for getting back at me :ok_hand:

Without any deeper knowledge of Serilog's inner workings, it would make sense to me if:

1. the "holes" and number of arguments are the same, use the explicit arguments to fill the holes.
2. the number of holes does not match the number of provided arguments, use enrichers to set any property match any hole in the provided template, then try to match the provided arguments.

**Comment by IanYates** [comment]
I've only just started monitoring GitHub issues again, but I recall there were changes made a release or two back in this area, specifically to do with the holes and number of arguments.

Searching...

Found it :)
According to the release notes, v2.5 included https://github.com/serilog/serilog/pull/944
That links to https://github.com/serilog/serilog/issues/825 as well for a bit more context

I appreciate it's almost the opposite of what you're after but the changes suggested would need to keep that long discussion in mind.

I wonder if there could be a new logger.[Level]Bag() call   (where Level is debug, information, etc) and, instead of taking in multiple arguments, it just accepts a string and an object that has its properties enumerated and matched to the message template.  For your case you could then be sure that holes were aligned with values based on name, not position, which would be much less brittle.  The object passed in could be a C# anonymous class instance.
Exceptions can be logged as usual by having an overload taking the exception as the first parameter.

So something like
```
logger.InformationLevelBag(
    "widget {widgetId}, priced {widgetPrice} created for tenant {tenantId}", 
    new {
        widgetId = 1234,
        widgetPrice = 56
});
```

with tenantId coming from ambient context.

For sanity reasons it could do case-insensitive string matching of the properties.  Extra properties of the object would be logged out if the {properties} string was present in the message template.

Yes it's an object allocation, but it'd at least be a definite easy collect for the GC.

Note: this may well have already been suggested somewhere else in the massive list of Serilog issues :)

**Comment by nblumhardt** [comment]
Thanks for all the input, folks! Closing this one for now, would be good to reopen if there's new perspective on top of the earlier lengthy discussions.

In a nutshell, though, `LogContext` is _nonlocal_. It shouldn't be possible to break/change the handling of log statements deep inside a call chain just by pushing properties onto the stack higher up. Trade-offs both ways, but switching tactics now would be a big undertaking and only viable with some really strong motivating cases.

Serilog Analyzer (VS add-in) will detect and reject these cases as invalid use of the API, highly recommended if you're able to install it 👍 

Cheers!
