### ISSUE TITLE
How to build a preconfigured facade (with dynamic configuration) for encapsulation

### ISSUE THREAD

**Issue by HansHammel** [serilog/serilog#1081]
We are currently switching to a microservice architecture and needed a cloud logging solutions, quickly prototyped using Serilog. But now, after fife days of work, ending up with 12 projects, Serilog is taking most of the configuration code and dependencies, slowing down build times and involving heavy copying. For each of the 12 projects 5 Serilog dll's (expected: 100 * 5). For that short time of usage (^) and the fairly small number of projects, this will (foreseeably) going to become a big problem. So, setup/ glue code and adding references (Serilog itself , a couple of enrichers, a hand full of sinks and their deps) is getting cumbersome. With reference to the static nature of the Log class, and some runtime dependencies of sinks used, what is the proper way to shift setup and references to a "helper" project? How can this encapsulation be done including considerations of thread safety and performance issues (of the core, I am aware of the problem of I/O bound sinks). And, there is the problem of dynamic configuration. Not only the LogEventLevel, but also the sink attachment. This is all supposed to come from the config server at runtime. And, I want to be able to mute some namespaces at runtime. So, any solution for this? Ideally a facade, factory, provider with (injectable) dynamic configuration...!?!? To state this out, I am searching a way to not reimplement all your static classes, which I currently (partially) do ;-)

Thanks, OB.

Update: BTW: Struggling with the dyn. conf. requirements, I came across the problem of needing to reference (also) static classes, enums, etc., that world be nice to have a SINGLE separate assembly of.

Related https://github.com/serilog/serilog/issues/861 https://github.com/serilog/serilog/pull/499

**Comment by nblumhardt** [comment]
Hi - thanks for checking in.

Given that Serilog will turn out to be one of the smallest possible dependencies of your services, I think the strategy of building facades is going to fall short: it seems infeasible (or unproductive) to try writing a dynamic facade for every dependency that's common to all of the services. By the time you're done it's likely there will be many shared libraries for various common tasks.

By the time the 100 microservices have implementations, relying on communication libs, ORMs, file formats and so-on, I would guess the proportion of build time attributed to copying Serilog DLLs will end up a much smaller, possibly invisible, fraction.

You might get a better long-term pay-off by distributing/parallelizing your build, or hooking into Git to determine which projects have changed in a given build. You'll need similar infrastructure in order to survive microservice deployment, which can't be done 100 services at a time, anyway.

Or, you could trade the cost of building and maintaining these facades for faster disks and more CPUs on the build server :-)

Hope this helps,
Nick

**Comment by HansHammel** [comment]
> Hope this helps,
I'm afraid not! 

Reducing dll's is a design goal. And the mein problem is not Serilog'S core, but the variety of associated dll's as mentioned above. Some of them even depend on dlls bound at runtime, likely to miss in a hundred of projects. And, separating the whole thing helps avoiding the "dll hell" and versioning/ updating issues...

Anything about dynamic configuration and thread safety?

**Comment by nblumhardt** [comment]
Serilog is thread-safe everywhere once `LoggerConfiguration.CreateLogger()` has been called.

This is a bit of a can-of-worms topic since it's highly dependent on your goals, architecture, etc. I will close this as I think it's too broad to cover well here - good luck with it, though! https://gitter.im/serilog/serilog is a good channel for working through any issues you hit along the way.

**Comment by HansHammel** [comment]
IMHO these are a major design flaws.
