### ISSUE TITLE
Log class name / method name / line number

### ISSUE THREAD

**Issue by leaderanalytics** [serilog/serilog#1084]
I am new to Serilog. Like most others I need to log location of exceptions, etc. in my code.
I found a workaround [here](https://stackoverflow.com/questions/29470863/serilog-output-enrich-all-messages-with-methodname-from-which-log-entry-was-ca) but like the OP of the referenced question I am incredulous that such fundamental and essential information can only be obtained via a workaround in a framework as robust as Serilog.

So.... before I decorate my code with hundreds of "Here()" calls, please confirm that obtaining requested info is not available via a more straightforward approach.

Thanks

BTW I've also read [this](https://nblumhardt.com/2016/08/context-and-correlation-structured-logging-concepts-in-net-5/)

**Comment by nblumhardt** [comment]
Here you go: https://gist.github.com/nblumhardt/0e1e22f50fe79de60ad257f77653c813

![image](https://user-images.githubusercontent.com/342712/35013620-ac5257f2-fb59-11e7-9872-1d096ab82d23.png)

You might wish to customize the way the method is formatted (_Ben.Demystifer_ has some great method formatting code to consider as reference.)

But, just to make you aware:

 * Inlining means release builds might not report the correct method name
 * Perf is going to be variable

HTH,
Nick

**Comment by nblumhardt** [comment]
(Assuming you might want to add the line number in there too - I've left it out since it's only available when PDBs are present, but the formatting code should be easy to modify if you want to pull it in.)

**Comment by leaderanalytics** [comment]
Thanks very much Nick!

**Comment by andre-ss6** [comment]
@nblumhardt Is there a way to enable an enricher only when a specific severity level is enabled? It would be nice to be able to use this code only when, say, Verbose is enabled.

**Comment by nblumhardt** [comment]
@andre-ss6 nothing out of the box, currently, but there's a good case for it. I'm going to open a new ticket to discuss :+1:

**Comment by andre-ss6** [comment]
@nblumhardt Ok, nice! And btw, I guess that the reason for not simply adding a `CallerInfoAttriute` optional parameter to all of Serilog public API methods is that you can't because of the `params object[] propertyValues)`. Is that right? Os is it more than simply making a breaking change and more about some design decision?

**Comment by nblumhardt** [comment]
@andre-ss6 primarily because of `params object[]`, but also because message templates make a stronger anchor from the log event back to the code than file/line numbers can.

I.e., it's possible to find all log events using `@MessageTemplate = 'Transaction committed in {Elapsed} ms'` over a long span of time, while searching for log events with `File = 'Transactions.cs' and Line = 100` will be thwarted by trivial code modifications that push line numbers around.

**Comment by virtualvoid** [comment]
this is just awkward, every logger includes the method name. I don't know why I should bother adding extra features instead of the author. 

how to "enrich" with configuration file / appsettings ?
