### ISSUE TITLE
Trim log file

### ISSUE THREAD

**Issue by davidATceedo** [serilog/serilog#1101]
We just moved from Log4Net to Serilog. There seems to be some obstacles, mainly that Serilog holds on to the file and doesn't share it... We have code that trims to log file. Is there anyway we can still do that?

Also, we sometimes need to change the configurations (especially the minimum log level) and we noticed that if we instantiate a new instance of the Logger with the same path, it will throw the error that the file is being used... I added "share: true" to the WriteTo.File() params - and this seems to solve it, but I wonder what happens to first instance ? Can I not dispose of it in anyway??

**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug

**What version of Serilog is affected?  Please list the related NuGet package.**
2.6.0, sinks.file v.4.0.0

**What is the target framework and operating system? 
- [ ] 4.5.x

**Comment by nblumhardt** [comment]
Hi! Using `shared: true` on both the initial and second `WriteTo.File()` call should do roughly what you're looking for - you need to specify it on both for it to work properly.

RE changing the minimum level at runtime, check out `LoggingLevelSwitch` - you can use this without creating a new logger at all. Similarly, `LoggingFilterSwitch` in _Serilog.Filters.Expressions_ can set filters dynamically without a new logging pipeline.

Instead of trimming the log file yourself with custom code, have you looked at rolling it on size or time period? Serilog's file loggers are not the ultimately-flexible implementation you might find with log4net or NLog, but most scenarios can be handled pretty cleanly if you're not trying to match existing behaviour exactly.

**Comment by davidATceedo** [comment]
Thanks for the reply. Will try to use the LoggingLevelSwitch, and also give rolling files a chance...
