### ISSUE TITLE
Fail to  install Serilog.Sinks.Console or Serilog.Sinks.File

### ISSUE THREAD

**Issue by dconner2006** [serilog/serilog#1121]
Using Visual Studio 2015 4.51 Nuget installed the Serilog package 2.6.0, but failed with the sinks.
Below is the error I received:

```
Install-Package : An error occurred while retrieving package metadata for 'Serilog.2.6.0' from source 'c:\Users\c839962\documents\visual studio 2015\Projects\SerilLog\packages'.
At line:1 char:1
+ Install-Package Serilog.Sinks.Console
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

**What version of Serilog is affected?  Please list the related NuGet package.**

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [x] 4.5.x

**Please describe the current behavior?**

**Please describe the expected behavior?**

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

**Comment by nblumhardt** [comment]
Hi - thanks for getting in touch.

Since the 2.6.0 package version has been installed 300,000+ times so far my guess is it's something specific to the machine./NuGet install/caches/etc. - to verify, do you have access to another machine with the same toolchain installed? If so, attempting the install there will determine whether it's cache related or NuGet/VS version-related. There are some instructions floating around out there on how to clear out NuGet caches. HTH!

Let us know how you go!
Nick

**Comment by dconner2006** [comment]
Thanks. I installed sp 3 and it is working.

Thanks
