### ISSUE TITLE
RollingFile -  Newest log at the top of File

### ISSUE THREAD

**Issue by hema2013** [serilog/serilog#1162]
Hello,
 I am using Serilog [Rolling File] to log data in file .
 The Current implementation now when the data logged in the file it put the newest one at the bottom of 
  the file . 

 Can I make configure Serilog to log the data in file from newest to oldest ?

  Thanks

**Comment by bartelink** [comment]
This would be very inefficient from an OS perspective (and very hard on disks, esp SSDs), which is why, pretty much forever, logs on pretty much all platforms have always been `tail`ed.

But, as a Rolls Royce workaround... the default view of [Seq](https://getseq.net) presents the newest at the top and much much more ;)

**Comment by nblumhardt** [comment]
👍 .. it's not impossible to write a custom file sink that would do this, though as @bartelink points out, it'd be monstrously inefficient, so it's not something we can include as an out-of-the-box option. Let us know if you need any further info on it :-) Cheers!
