### ISSUE TITLE
Serilog unable to write logs to file when application (exe) called from Command Prompt

### ISSUE THREAD

**Issue by Audhut** [serilog/serilog#1202]
Hi All,

I have a windows application which does some processing. I am using Serilog to log the information for each action.
The application works in two ways.
1)	When no command arguments are passed it opens windows form with some buttons
2)	When some specific arguments are passed it does some processing.

When I click on the exe of the program it launches the application and it does the logging successfully.
But if  I call the exe through the  Command Prompt with command arguments, the system does  not generate logs and log file.

Below is the code of the program.cs file

**Note**:  Log.Information($"windows app called") is successfully logged if the exe is run directly. But if the exe is called through Command Prompt  with  Command arguments then     Log.Information($"console app called") is not logged.

     static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration().WriteTo.File("xxx-con-user-cleanup-log-.txt", rollingInterval: RollingInterval.Day)
                .CreateLogger();

            if (args.Length == 0)
            {
                Log.Information($"windows app called");

                Application.EnableVisualStyles();
                Application.SetCompatibleTextRenderingDefault(false);
                Application.Run(new Dashboard());
            }
            else
            {

                Log.Information($"console app called");

                if (args.Length > 0)
                {
                    var scheduler = new SchedulerUserCleanUpProcess();
                    for (int i = 0; i < args.Length; i++)
                    {
                        var arg = args[i].ToUpper();
                        Log.Information(
                            $"SchedulerUserCleanUpProcess - Input Argument - {arg.Trim().ToUpper()}");

                        if (arg == "LU" || arg == "IU" || arg == "NU" || arg == "DU")
                        {
                            scheduler.Execute(arg);
                        }
                        Console.WriteLine(@"args[{0}] == {1}", i, args[i]);
                    }
                } 
            }
            Log.CloseAndFlush();
        }

**Comment by bartelink** [comment]
Typically this sort of thing will be due to you running the app as admin in one context and then as a lower privilege next time.
The ownership is based on when the folder is created, so if that's a highly privileged user, the normal one can't 'just' go change that file.
Typically this is addressed by assigning permissions as part of the install process and/or putting it in an appropriately priviliged area of the disk.
For debugging this sort of thing, SysInternal filemon is the goto tool - it will show you what's trying to write where (but really, you know its a file write to file X as user Y from looking at task manager).

**Comment by Audhut** [comment]
Hi bartelink ,

Thank you so much for the response.  The user under which I run the exe directly and through the command is the same. So, the permissions may not be an issue. One thing I mention to forget is if I launch the exe though the Command Prompt without any parameters then it opens the windows app. And if I perform any actions, then it doesn’t log that also.
But if I launch it directly by clicking the exe. Then it works.

**Comment by bartelink** [comment]
How you launch the app (from VS, commandline, clicking in explorer) can dictate the permissions and lead to inconsistencies even with the same user due to elevation (admin credentials being in play or not)
Repeating: Serilog does nothing specific with file permissions; that's not it's job - if it goes wrong a) the chances are its something you're doing b) you can find out what that is with filemon

**Comment by tsimbalar** [comment]
Could it be because your current working directory is different ?

>
If you configured the File Sink using a "non-absolute" path, then the final
log file path may end up being different . Maybe the log file IS written,
but in a different location ?

**Comment by bartelink** [comment]
The other thing @tsimbalar's point brings to mind is that there is a `SelfLog` facility, which provides a hook that you can use to detect any failures in writing (Serilog will not surface writing errors unless you use `AuditTo` instead of `WriteTo` in your config).

**Comment by nblumhardt** [comment]
Closing as stale, but please jump back in if you have more data @Audhut 👍
