### ISSUE TITLE
Add secure hint to message templates

### ISSUE THREAD

**Issue by daniel-white** [serilog/serilog#1211]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x] New Feature

**What is the target framework and operating system?*

- [x] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
Right now `$` and `@` are available prefixes for hinting as to how the message template should be interpreted.

**Please describe the expected behavior?**
It would be nice if another prefix were added to support secure/sensitive values. These values could be hashed, encrypted, etc. depending on the sink and/or event enricher. I propose using `~` or `!` as the prefix.

**Comment by nblumhardt** [comment]
Hi Daniel!

This is an interesting idea; we try to keep the message template syntax very stable, however, so that all of the current implementations in .NET remain compatible (esp. Serilog, NLog, LibLog, and Microsoft.Extensions.Logging). The bar for considering changes is therefore really high (while individual changes might benefit some scenarios, the whole ecosystem benefits more from a stable format).

A solution using custom destructuring policies, (check out `LogMasked` in _Destructurama_) or through quasi-syntax in the template, like:

```
Log.Information("Hello, ~{Name}", name);
```

would be the way to go, here. The "securing" aspect could be performed by a wrapper sink that rewrites the message template and encodes matching properties appropriately (see `LoggerSinkConfiguration.Wrap()`).

HTH! And thanks again for the input,

Cheers,
Nick

**Comment by daniel-white** [comment]
Thanks for the kind and well thought out rejection.
