### ISSUE TITLE
Discussion: Remove the use of the static Log. and Log.Logger from .NET core examples

### ISSUE THREAD

**Issue by PureKrome** [serilog/serilog#1237]
👋 Hi Serilog team 😺 

- New Feature
- Serilog v 2 .7.1
- netCore 2.1

Ok - so this is a discussion (question?) about reading the .netCore 2.x samples when learning to use Serilog. Currently, the code is more or less this for [console](https://github.com/serilog/serilog/wiki/Getting-Started#example-application) or [web](https://github.com/serilog/serilog-docker/blob/master/web-sample/src/Program.cs):

```
public static void Main(string[] args)
{
    // Create an instance of an ILogger but stick it in some static variable.
    Log.Logger = new LoggerConfiguration() .... 

    // Wrap the entire application in a simple Try/Catch block to be able to log
    // any unexpected error that occured. Kewl!
    try
    {
        // If this is a WebHost then we need to do some more ceremony...
        // Note: What about GenericHost???? Assumption from me is that this will occur
        //     in the future for that, also.
        WebHost.CreateDefaultBuilder(args)...
            .UseSerilog() .....  / <-- magic!!
    }
    catch(Exception exception)
    {
        Log.Fatal(....);
        return;
    }
    finally
    {
        Log.CloseAndFlush();
    }
}
```

Ok - nothing to crazy here.

So - I usually see statics like this and think back to some old problems that caused grief and pain in the old days. I'm hoping we can change the documentation (read: docs only .. not the main infrastructure about how Serilog is designed, etc) to use an *instance* instead (with proper disposal at the end of the method). 

Sure, this is very pedantic -- I totally accept that.

But **I hope what this will teach the reader** is that they should _hopefully_ think that they should use DI and have an `ILogger` injected into their classes (like controllers, etc). I feel that .. having the static `Log` or `Log.Logger` exposed here in the _initial samples_ could unintentionally promote the use of `Log.Logger` throughout their applications (assumption here I'm making is that we shouldn't be promoting the use of Statics (like this) in apps ... parallel unit testing will thank you later 😈  and yes, no one unit tests the `program` class but if other classes are using the static `Log.Logger` then this is what I'm referring to.)

So maybe something like this might work?

```
public static void Main(string[] args)
{
    // Create an instance of an ILogger but stick it in some static variable.
    var logger = new LoggerConfiguration() .... CreateLogger();

    // Wrap the entire application in a simple Try/Catch block to be able to log
    // any unexpected error that occured. Kewl!
    try
    {
        // If this is a WebHost then we need to do some more ceremony...
        // Note: What about GenericHost???? Assumption from me is that this will occur
        //     in the future for that, also.
        WebHost.CreateDefaultBuilder(args)...
            .UseSerilog() .....  / <-- magic!!
    }
    catch(Exception exception)
    {
        logger.Fatal(....);
        return;
    }
    finally
    {
        logger.Dispose();
    }
}
```
NOTE: I didn't wrap this in a `using` block only to reduce the indentation of the method-code.

I'm assuming with the above pseudo code is the `UseSerilog()` also still works and wires up the magic required for the `Host`, etc so `ILogger` still works, etc.

Anyways, that's some thoughts from a noobie who's been using this for a while and still constantly refers to the beginner docs all the time.

HTH.

**Comment by nblumhardt** [comment]
Hey! Thanks for the feedback, @PureKrome, appreciate the input 👍 

Personally, and I may be out on a limb :-), I don't think it's a great idea having loggers in DI, registering loggers with the container, and so-on, and would vastly prefer the use of the static `Log` class, myself. The samples use it because I think it's the pit-of-success path.

I feel like ASP.NET jumped the shark with this- DI is about communicating the dependencies of a component, and cluttering up its constructors with `ILogger`s communicates nothing important ("this class does logging!"). Constructor real-estate is super-valuable when you use IoC a lot.

If you're writing in a more functional style with lots of static methods, passing `ILogger`s around also becomes a chore. If a component way down deep in a call graph needs to log, all of the callers need to get involved - transitive dependency churn.

RE unit testing, I don't think logging should be enabled during unit testing, or log events tested, personally - though there are some tools for out there for capturing async-local events logged through the static logger. Log events should be cheap to add and trivial to change without test impact, otherwise the logging gets stale since no one wants to have to modify tests in order to improve the content or punctuation in a log event/message.

Of course, opinions vary widely, and apologies if in my haste to get a quick reply to you on a Friday afternoon if I come across a bit dogmatic and opinionated :-) The choice of static `Log` in all the samples is conscious, though, and the product of a lot of soul-searching already, so not keen to change this. Thanks again!

**Comment by tsimbalar** [comment]
> Constructor real-estate is super-valuable when you use IoC a lot

I'll have to write down this one somewhere 👍

**Comment by PureKrome** [comment]
Thanks @nblumhardt appreciate the feedback.

+1 to the unit statement, also.

**Comment by bartelink** [comment]
I agree with all this; I'm abusing Serilog as a metrics abstraction in https://github.com/jet/CallPolly and pass `ILoggers` where there is an implicit hardwired contract as to what I log (and I have tests of the kind described) - in an actual app, static loggers are the way to go.

I've also used this idea of an event DU in the properties to death in another set of libs - it works well in that I get to test behaviors and logging while not having to introduce a logging abstraction. The value for me is in the fact that I get two critical things for free that are hard to get right:- 1. good perf 2. clean and clear logging statements that I don't need to explain or document the mechanism behind.)

One idea I've been mulling over is to have a formal `Metric` or `Event` in `LogEvent` that formalizes (in the same way that `Exception` does) the notion of some intentional payload to which one would actually be safe to attach a dependency to. However I appreciate that this is definitely corner case usage for a logger so would need quite som nudging to actually suggest it for real.

**Comment by nblumhardt** [comment]
@tebeco I think you may have misunderstood the OP; the question is about the style used in the example code, not what the library supports.

Serilog was designed from the start to be usable without any static state. Just configure your IoC container to inject the right `ILogger` into the right components and you're done! The log4net global `LogManager`/category name system works in some cases, but in others (e.g. multitenancy) you need independent logging pipelines _even for the same caller_.

`Log.Logger` is the simplest path for most people, but Serilog absolutely does account for non-static logging pipelines, you might need to dig around a bit more to work out how to support your precise scenario, though. Shoot some questions to the Gitter if you need a hand.

**Comment by tebeco** [comment]
also @bartelink if you need the `static Logger.Log` in you own app nothing would stop you to do so right ?

i mean create a
```
using ChooseFrameworkLib;

public static class MyAppLogger
{
  public static Logger Log {get;set;}
}
```

as you see i also decide what lib i want for logging in a single place and i avoid 
`using Serilog` in all my codebase so i can as a consumer what i want and you still have the static logger you want so everything is still ok for everybody

now with the approach of this class being part of serilog you are assuming people actually want the static logger and will love adding a `using serilog` everywhere they do logging and also they will have to add the reference everywhere
then the transitive will leak everywhere down if they design a nuget
so a simple change like “hey let’s use another framework” is doomed because of the “helper class that should have been written by consumer and not producer

**Comment by adamchester** [comment]
This link might be useful @tebeco 

https://nblumhardt.com/2016/04/which-logging-abstraction-should-i-use/

**Comment by bartelink** [comment]
The other thing in the picture is `LogContext`/`PushContext`, which is not as trivial to wrap in this manner (One'll often use `ForContext` in various places in app code too).

While there is little harm in doing what you suggest, for me, it also doesn't buy you that much of value in the context of an app.

Within apps I'm rarely interested in a logging abstraction - often a way to migrate is to [forward one logger to the other](https://stackoverflow.com/questions/49592351/redirect-all-nlog-output-to-serilog-with-a-custom-target) - new code works the way you expect for zero perf cost and no abstratctions to second guess, test or benchmark; old code works as you'd expect.
