### ISSUE TITLE
Extracting logs from file - Rolling file sink?

### ISSUE THREAD

**Issue by ad1969** [serilog/serilog#1270]
In our company, we have a process that extracts new logs periodically and exports them into Splunk.

This process looks at a predetermined file name. It will magically extract the latest entries, but the file needs to be the same name and in the same location.

I'm looking for a solution to implement this. If I don't add a {date} to the file name and hard code is as say log.txt, will all logs be added to log.txt and once a size limit is met, the current log.txt will be named to say log1.txt and the application will continue logging into a file called log.txt?

Thanks
Alex

**Comment by bartelink** [comment]
Splunk forwarding can be made to work fine as it is - Splunk's forwarder can have multiple rules configured per location and/or extensions. If there's 'well we're not going to read the docs just because you found some crazy log library" pushback, I'd mention that others do it just fine, and refer to https://www.nuget.org/stats/packages

`NLogFormat` compatibility, as you're effectively requesting would mean doing cascading renames, which is hard to do correctly, safely and efficiently, especially in the face of multiple writers. To deal with the cascading renames, the splunk forwarding actually needs to do more complex processing to deduplicate logs that have already been ingested by deriving, maintaining and then deduplicating by fingerprinting file contents.

I did ask for https://github.com/serilog/serilog-sinks-file/issues/40, which makes a whitelist regex in the splunk forwarder config less messy as it means not special casing - but that's just gold plating. (I don't personally have the config settings to hand but suspect asking on Stack Overflow or the Splunk SO clone site will yield you a set of working configs pretty easily)

(BTW the other thing you want to do is use the compact json formatter and send the log entries as json)
