### ISSUE TITLE
What are the best practices to resolve memory issues in serilog?

### ISSUE THREAD

**Issue by kudlatiger** [serilog/serilog#1273]
I see these errors in my application log from Serilog 

Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.AccessViolationException at Serilog.Events.DictionaryValue..ctor(System.Collections.Generic.IEnumerable1>) at Serilog.Capturing.PropertyValueConverter.TryConvertEnumerable(System.Object, Serilog.Parsing.Destructuring, System.Type, Serilog.Events.LogEventPropertyValue ByRef)at Serilog.Capturing.PropertyValueConverter.CreatePropertyValue(System.Object, Serilog.Parsing.Destructuring, Int32) 
  at Serilog.Capturing.MessageTemplateProcessor.CreateProperty(System.String, System.Object, Boolean) 
  at serilog.Exceptions.Destructurers.ExceptionEnricher.Enrich(Serilog.Events.LogEvent,Serilog.Core.ILogEventPropertyFactory)

Seems to be memory issue

**Comment by nblumhardt** [comment]
Hi! This will unfortunately be due to memory corruption happening either:

 * Somewhere else in the process (writing over the heap),
 * Because of some incorrect unsafe/native code somewhere in the thing being destructured, or,
 * Because of a concurrency issue (perhaps destructuring an object that includes unsafe code, that's being concurrently modified elsewhere)

Of these, it's most likely to be the first. Serilog itself doesn't contain any unsafe code (that I can recall), so it would be difficult for this to be caused by code in the Serilog library itself.

Hope you're able to track it down; https://stackoverflow.com/questions/3245185/how-to-debug-accessviolationexception-coming-from-native-code might be a starting point (or at least suggest some keywords to follow).

On the downside, these are sometimes hard to locate. On the upside, it's a truly satisfying debugging task when you're able to find one. Good luck!
