### ISSUE TITLE
Log.ForContext<T> pattern might derive SilentLoggers

### ISSUE THREAD

**Issue by Suchiman** [serilog/serilog#1294]
I had a discussion with an unhappy user the other day in IRC so i thought let's make an issue :wink:

It is a common pattern to use code like
```csharp
private static readonly ILogger Logger = Log.ForContext<CurrentClass>();
```

Now due to various circumstances it is possible that `Log.Logger` isn't initialized yet at the time the static constructor runs which creates a `ForContext` logger based on the `SilentLogger` which will break all logging for that class.

The example i was given, was that with growing complexity of the application, a Sink was built that needed services from DI which delayed the initialization of the logger, at which point many classes might have been already touched, creating unuseable loggers. They had to figure this out the hard way when the application wasn't logging everything that should have been anymore. Also having correct behavior dependent on the correct order of static constructors being run is very bad.

Another example was being able to reconfigure the logging pipeline at runtime.

The rest was a bit of angry rambling about having the audacity to do things differently (immutable loggers vs. mutable loggers / LogManager like in nlog / log4net) than in long established logging frameworks which caused trust issues.

I think this can be fixed by introducing a `Log.GetGlobalLogger()` and a `Log.ForGlobalContext` method. They would work similiar to the current `ForContext` mechanism in creating a `new Logger(…)` but with the `ILogEventSink sink` parameter not being `this` but a custom Sink that always calls through `Log.Logger`.

Alternatively one could argue to change the static `ILogger` returning methods on `Log` to do this by default. Of course this would be a breaking change, but i hope no one is using the factory methods on `Log` to then switch out `Log.Logger` and expect the previously derived loggers to still use the previous `Log.Logger` instance. If anyone would truely need that odd behavior, they could change the code to `Log.Logger.ForContext`, etc.

Looking at the code, checking the level seems to be the biggest hurdle.

**Comment by nblumhardt** [comment]
Thanks for the write-up :-)

Could be a docs issue? I can see the footgun, but we're pretty clear in all of the code examples that assigning `Log.Logger` is the first thing most apps should do. Perhaps we should also call out why? (And show the alternative of always calling `ForContext<T>()` dynamically instead of assigning its result to static vars.)

Adding new APIs for this will inevitably also come down to a docs issue - they won't be the first methods people reach for, and so only people who are aware of the issue will find them - which might defeat the purpose. What do you think?

**Comment by Suchiman** [comment]
The user was adhering to the rule of initializing the logger at the very first so the logging was working fine initially. Things broke ***silently*** down later when the requirement to get a service from DI delayed the initialization, it's obvious that logging doesn't work before its initialized but that its partially not working after being initialized because of this race condition requires you to debug to this point and hover over the logger to see it's the `SilentLogger`. This could be helped a bit if the `SilentLogger` were to write to `SelfLog`.

I suppose you can alter
```csharp
private static readonly ILogger Logger = Log.ForContext<CurrentClass>();
```
to
```csharp
private static ILogger Logger => Log.ForContext<CurrentClass>();
```
which would avoid this problem entirely, at the cost of increased allocations in the application.

I think the deal with `Log` is all about expectations, when you reassign `Log.Logger`, then the next `Log.Information` will do the right thing but the previously gathered `Log.ForContext` does not.

On the other hand, i've been evangelizing serilog for some time now and this is the first time an issue of this degree came up, maybe having a Sink rely on DI services is a bit too obscure scenario, but being able to change the logging pipeline at runtime came up quite a few times.

**Comment by nblumhardt** [comment]
Somewhere on here, I think I posted a sample for a `DynamicLogger` class that would wrap a mutable `ILogger` or `Logger`, and return proxied `ILogger`s from methods like `ForContext` that would pick up the logger to use on-the fly. I.e.:


```csharp
var dynamicLogger = new DynamicLogger(someLogger);
Log.Logger = dynamicLogger;

//...
dynamicLogger.Update(someOtherLogger)
```

Needs a better API... but, opting-in would avoid us having to introduce a perf hit for all users of the library (including the memory barriers for ensuring changes to the logger propagate to CPU caches - potentially expensive, and impossible to measure because the perf impact depends on the app in which Serilog's being used).

I think there's still the same discoverability problem, unfortunately, but I also think doing it by default will turn out to be a dead end. What do you think?

**Comment by Suchiman** [comment]
Ah yes a very interesting idea, this moves the point were you do the switch one back and is opt-in able, i like it. You can start with `Log.Logger = new DynamicLogger(Logger.None)` and then later update it 👍

**Comment by nblumhardt** [comment]
:+1: not sure I'll have the chance to hack anything together, but I'll gist it if I get a chance. Might be one to get some real-world feedback in gist form, before we consider whether we bundle it?

(Seems harmless to bundle, but the discoverability might not be great either way 🤔 )

**Comment by abrasat** [comment]
Does each ILogger instance have its own LogContext ? Would be possible to get the LogContext from a ILogger instance?

**Comment by nblumhardt** [comment]
Hi @abrasat - I think yours is a separate question; the answer (to both queries) is "no", but if you need more info can you please open a new ticket or pop this onto Stack Overflow? Thanks!

**Comment by abrasat** [comment]
Ok, I opened a new ticket [https://github.com/serilog/serilog/issues/1301](https://github.com/serilog/serilog/issues/1301)

**Comment by nblumhardt** [comment]
@Suchiman I'm on a bit of an issue-tracker-cleanout; I think this is interesting but I won't have time to jump onto it personally. I'll close the issue here, and if you (or someone following along) want to sketch out `DynamicLogger` at some point, just give the word and I'll send what info I can 👍
