### ISSUE TITLE
Lazy evaluate property values

### ISSUE THREAD

**Issue by sprengr** [serilog/serilog#1297]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x] New Feature

**Please describe the current behavior?**
Sometimes the evaluation of a log property value is non trivial, takes a long time and maybe we won't even see these logs, because they are lower leveled than the specified minimum level. Right now in these cases we have to do something like this:

```csharp
if (Log.IsEnabled(LogEventLevel.Debug)) {
    Log.Debug(template, LongRunningCalculationWeWantToLog());
}
```

**Please describe the expected behavior?**
It would be nice to be able to do something like this:
```csharp 
    Log.Debug(template, () => LongRunningCalculationWeWantToLog());
```
Which would only execute `LongRunningCalculationWeWantToLog` when the log level is >= Debug.

**Comment by nblumhardt** [comment]
Thank you for the suggestion. We've considered this in the past, but not taken this approach because of the additional allocation required when accepting delegates. The conditional `if (...)` approach is the recommended way to go.

If you find that this comes up a lot in your domain, and allocations aren't a concern, it may be worth creating your own wrapper/extension method for this particular kind of call.

HTH!

**Comment by sprengr** [comment]
Thanks for clarifying. 

> If you find that this comes up a lot in your domain, and allocations aren't a concern, it may be worth creating your own wrapper/extension method for this particular kind of call.

That's what I usually do. If anyone's interested: 

```csharp
        public static void LazyDebug(this ILogger log, string template, Func<string> value, params object[] values)
        {
            if (log.IsEnabled(LogEventLevel.Debug)) {
                log.Debug(template, value(), values);
            }
        }
```

**Comment by cocowalla** [comment]
@sprengr won't your approach result in the allocation of a delegate? (for the `Func<string>`)
