### ISSUE TITLE
Community Project: Serilog.NodaTime

### ISSUE THREAD

**Issue by kingboyk** [serilog/serilog#1298]
I have a new community project, [Serilog.NodaTime](https://github.com/kingboyk/Serilog.NodaTime) which adds support to Serilog for destructuring [NodaTime](https://github.com/nodatime/nodatime) types.

I've been asked to publish the project to Nuget so before I do that I just want to check that you are OK with the naming.

Also could you please add it to the list of community projects? Alternatively, I am happy to donate the project.

Thanks for all your great work!

**Comment by tsimbalar** [comment]
Hi,

looks nice ! 

I do have a few suggestions for it to fit better within the *Serilog* ecosystem. 

1. Because the project deals mostly with `Destructure`-ing, it would feel more natural if the added extension method was on top of `LoggerDestructuringConfiguration` instead of `LoggerConfiguration`. (you can refer to the projects under [Destructurama](https://github.com/destructurama) to get an idea). This has the added benefit that it makes the configuration method usable through the different *settings* providers (`AppSettings`, `Configuration`, `KeyValueSettings`).

2. For discoverability, you would normally put your extension methods in the `Serilog` namespace, so that they automatically show up without needing any extra `using` statements (but keeping your class in their own namespace is recommended)

3. It's probably me being paranoid, but I usually create all my class as `internal` by default ... and only mark them as `public` if it is really needed :) 

4. about the name of the package, I think @nblumhardt will be the best to give recommendations ... but I think that the `Serilog.` prefix is reserved on nuget.org ... so you may need a different prefix / root namespace...

**Comment by tsimbalar** [comment]
Also, maybe another suggestion / possibility would be to see if your project could be added to the `Destructurama` organization, which already includes several `Destructuring` extensions for Serilog : https://github.com/destructurama

This would probably also make your package easier to find. (there is for instance a package called `Destructurama.JsonNet` which adds destructuring for `JSON.NET` types .... and it would make a lot of sense to have `Destructurama.NodaTime` ....

**Comment by kingboyk** [comment]
Thanks @tsimbalar  for your feedback - it's very much appreciated :)

I'll create a new branch asap to look at implementing suggestions 1 and 2 and anything else which may flow from this Issue (indeed I had hoped to do it today but you know how it goes).

I'm in mixed minds about declaring the deconstruction classes as `internal`. I see your point; furthermore my project is modelled on [NodaTime.Serialization.JsonNet](https://github.com/nodatime/nodatime.serialization/tree/master/src/NodaTime.Serialization.JsonNet) where the equivalent classes are indeed `internal` and what's good enough for Jon Skeet is certainly good enough for me... On the other hand, my thinking was that by making the classes `public` it would allow users to cherry pick just the deconstructors they need without being compelled to load all of them. Perhaps a reasonable compromise would be to mark the classes `internal` and add extension methods for each NodaTime type? Or maybe I should concede? Not sure at the moment.

**Comment by kingboyk** [comment]
With regards to the organisational issues and naming:

- I think you may be right about Serilog being a reserved name on Nuget which, courtesy aside, was a reason for asking

- Destructurama sounds like it could be a good home for the project, certainly. They have no public members listed on the repo but I see a familiar name in the commit history...

...therefore I think we'll have to wait to hear from @nblumhardt on this one.

Thanks again!

**Comment by nblumhardt** [comment]
Howdy! There's no problem with using the _Serilog_ prefix - the "official" packages will get the blue checkmark icon, community packages won't, but there's a long history of _Serilog.*_ community packages and this is fine.

It would be nice to keep expanding _Destructurama_ but it's not really intended to become an umbrella organisation the way Serilog is: we originally created it to house some much-loved but esoteric components that were once part of Serilog itself. Publishing it independently is great :+1:

**Comment by kingboyk** [comment]
@nblumhardt - the package is now live [on Nuget](https://www.nuget.org/packages/Serilog.NodaTime/). If you'd like to add a link to it on the Community Projects page that would be cool - and if you don't that's fine too :) Thanks for your help!

**Comment by nblumhardt** [comment]
Reopened so we can track adding it to the community page :+1:

**Comment by nblumhardt** [comment]
Done!

**Comment by Rody66** [comment]
Thank you!
