### ISSUE TITLE
Add Compact Log Viewer to Community Project WIKI page

### ISSUE THREAD

**Issue by warrenbuckley** [serilog/serilog#1306]
Hi @nblumhardt 
Is it possible to please list the desktop application I built for viewing JSON clef files on disk.

https://github.com/serilog/serilog/wiki/Community-Projects

**Repo**
https://github.com/warrenbuckley/Compact-Log-Format-Viewer

**Windows**
https://www.microsoft.com/store/apps/9N8RV8LKTXRJ?cid=storebadge&ocid=badge

**MacOS**
https://itunes.apple.com/gb/app/compact-log-viewer/id1456027499

Would you mind if I created PR's on these repo's as well please to help promote it (obviously mention its community made)

https://github.com/serilog/serilog-formatting-compact
https://github.com/serilog/serilog-formatting-compact-reader

![Pretty Please](https://media.giphy.com/media/l0NwNrl4BtDD7JCx2/giphy.gif)

**Comment by nblumhardt** [comment]
Done!

Fantastic idea RE listing this on the CLEF formatter repo. I've added it to:

https://github.com/serilog/serilog-formatting-compact/blob/dev/README.md#tools

I think we might be better off centralizing all of the info in that README rather than duplicating it in the _*Reader_ repo, since it's become the de-facto reference doc for the format.

Cheers!

**Comment by nblumhardt** [comment]
Done! https://github.com/serilog/serilog/wiki/Community-Projects - Thanks @warrenbuckley
