### ISSUE TITLE
How to set logged event timestamp

### ISSUE THREAD

**Issue by abrasat** [serilog/serilog#1311]
My application receives from embedded systems messages containing log information, including timestamps. This logged information is converted to json format and sent to serilog. How can serilog be configured to allow to set the timestamp of the serilog logged events "manually" (the requirement is to use the "original" timestamp from the embedded system messages)?

**Comment by abrasat** [comment]
Unfortunately is the "Timestamp" property of the LogEvent class defined only as read-only (only { get } available), otherwise it would have been possible to override it with a custom LogEventEnricher

**Comment by nblumhardt** [comment]
Hi @abrasat -

In this case you need to use `logger.Write(new LogEvent(timestamp, ...))`  - the [`LogEvent` constructor](https://github.com/serilog/serilog/blob/dev/src/Serilog/Events/LogEvent.cs#L36) should guide you in which parameters you need to supply.

If you want to use message templates "match up" to a `params object[]` of arguments somewhere, you'll need to use [`ILogger.BindMessageTemplate()`](https://github.com/serilog/serilog/blob/dev/src/Serilog/ILogger.cs#L928) instead of `new MessageTemplate()` or `MessageTemplateParser.Parse()` (example in the comments on that method).

HTH!

**Comment by abrasat** [comment]
Thank you for the information.
I was hoping for a LogEventEnricher-based solution, as I use logger calls also in class libraries which actually depend only on the Microsoft.Extensions.Logging definitions and where I was planning to avoid the Serilog dependency.
The Serilog log is injected only in the main application by calling AddSerilog().

**Comment by nblumhardt** [comment]
:+1:

In that case, you can use a wrapper sink - there's an example in https://github.com/nblumhardt/serilog-sinks-timewarp/blob/master/Serilog.Sinks.TimeWarp/Program.cs that modifies timestamps this way.

**Comment by abrasat** [comment]
Thank you for the link.
Actually I would like to set the timestamp from the embedded system in all configured serilog sinks (for instance in the current application : sinks for console, file, elasticsearch, etc). Do I have to write a wrapper for each of the used serilog sinks? Or is there some other solution possible?

**Comment by nblumhardt** [comment]
Using `WriteTo.Logger`, as in: `WriteTo.TimeWarp(..., writeTo => writeTo.Logger(lc => ...)))` will let you construct a whole logging pipeline downstream.

**Comment by abrasat** [comment]
Thx. Can this be combined also with the Async sink? Could you please post a code sample how to casacade TimeWarp with the option of Async for some or all of the Console, File and ElasticSearch sinks?
