### ISSUE TITLE
Serillog Version 2.7.1 and Version 2.8.0 has the same assembly version of 2.0.0.0

### ISSUE THREAD

**Issue by RushuiGuan** [serilog/serilog#1319]
This is not right.  Different nuget versions cannot point to the same assembly version.  It will cause a lot of pain when:
* Assembly A references Serilog Version 2.7.1
* Assembly B references Serilog version 2.8.0
* Program C references both Assembly A and B

Since the assembly versions are not distinct between the versions, at runtime, dotnet couldn't tell if the correct assembly is being loaded.

This is related: [Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'](https://github.com/serilog/serilog-aspnetcore/issues/74)

**Comment by nblumhardt** [comment]
Hi @RushuiGuan - thanks for the note.

Package versions and assembly versions have no fixed relationship. We've used the immutable 2.0.0 assembly version deliberately throughout the entire Serilog 2 release series, and although there are downsides, it's also avoided many painful scenarios. (The GAC is unfortunately going to be painful whether we do this or not .. :-))

Thanks again; I'm closing this as by-design, but hopefully someday we'll all be completely free of the GAC, strong naming, etc. etc.!

**Comment by RushuiGuan** [comment]
Hi @nblumhardt, thanks for the reply.

Assembly versioning is used at runtime and should aways uniquely identify a binary.  When multiple versions of the same assembly are referenced, users can use binding redirect to determine exactly which version to use.  Dotnet even allows us to reference multiple versions of the same assembly at the same time.  All this is no longer possible since the serilog V2 assemblies have exactly the same version.  

Logging is such a common library, it is common for a program to reference multiple versions at the same time, often not by choice because of third party dependencies.  Versioning your assembly this way leaves the user with no way to resolve the conflict.  Depends on the runtime and how the assemblies are referenced, the program may or may not run at all.

The "painful scenarios" have been solved many years ago.  What's left is a proven working system.  Please reconsider.  Thanks!

**Comment by nblumhardt** [comment]
Thanks for the thoughtful reply. I know there are pros/cons to the scheme we've chosen, and unfortunately you might be stuck with a scenario (e.g. SharePoint, _System.AddIns_, or some other GAC-heavy application model), where some limitations come through.

For modern .NET projects that use NuGet and deploy their libraries alongside executables, the current scheme works well; the version used at runtime will be determined by which DLL gets deployed, and this comes down only to which NuGet package version is installed.

At deployment time, MSI and other versioned artifact deployment technologies work with this because we ensure the file version is set to the package version, not the assembly version:

![image](https://user-images.githubusercontent.com/342712/59084542-f7ce9780-893e-11e9-8684-5056d7faaeed.png)

The plus side for most use cases is the elimination of unnecessary run-time assembly loading failures and binding redirect issues. It's really cut out a massive amount of trouble - _Serilog_ is the third-most downloaded non-Microsoft package on NuGet, so we measure the success of this strategy by the amount of inbox traffic we're _not_ getting about it 🙂.

What tools are causing you trouble? Happy to help resolve your version conflict if you can send some more details.
