### ISSUE TITLE
Use case-insensitive matching for source names in level overrides

### ISSUE THREAD

**Issue by tillig** [serilog/serilog#1335]
[I'm unclear if this is the right repo for this or not; I'd be happy to move or refile if needed.]

Microsoft.Extensions.Configuration is a case-insensitive construct. For example, `configuration.GetSection("a:b:c")` will yield the same as `configuration.GetSection("A:B:C")`. This allows things like environment variables or command line parameters to participate in config but also be named in a contextually correct fashion (e.g., environment variable `A__B__C`).

In configuring the minimum level and overrides for log sources, I think I've discovered that the JSON configuration values are case-sensitive. For example, this...

```json
{
  "serilog": {
    "minimumLevel": {
      "default": "Information",
      "override": {
        "microsoft": "Warning",
        "system": "Warning"
      }
    }
  }
}
```

..._does not work_ - it still shows informational messages from Microsoft.* sources.

![Info still shows up though the configuration is set to Warn](https://user-images.githubusercontent.com/1156571/60120399-8b70d800-9735-11e9-93a3-6295544483a5.jpg)

However, this:

```json
{
  "serilog": {
    "minimumLevel": {
      "default": "Information",
      "override": {
        "Microsoft": "Warning",
        "System": "Warning"
      }
    }
  }
}
```

_does work_ - only warnings show up for the Microsoft.* sources.

![Only Warn is showing for Microsoft.* sources](https://user-images.githubusercontent.com/1156571/60120527-ddb1f900-9735-11e9-9cde-f2528eb6a880.jpg)

The only difference is the capitalization of the source names, which indicates the source names here are case-sensitive.

Granted, JSON itself _is case-sensitive_ but since this is running through the MS configuration stuff, it can't really be assumed to be case-sensitive, especially if someone configures it through the environment:

`SERILOG__MINIMUMLEVEL__OVERRIDE__MICROSOFT="Warning"`

Where does that comparison/filtering take place? Is that a core Serilog thing? I could throw a PR in for that if I know where to start tracking it down.

**Comment by tillig** [comment]
In the event it helps (or not?) I looked at how log4net does it.

[In .NET desktop framework, it's using object equality. In .NET Core/compact it uses the `string` type's `==` override.](https://git-wip-us.apache.org/repos/asf?p=logging-log4net.git;a=blob;f=src/Repository/Hierarchy/LoggerKey.cs;h=ccc566b1b195d87e7e9eca4bfce72854c909673c;hb=refs/heads/master#l118) The object equality is because they're interning strings in .NET desktop framework.

**Anyway, this boils down to log4net being case-sensitive for its logger names.**

That said, log4net is also pretty tightly tied to loggers being based on types - a "logger repository" in there is tied to an assembly and used as a central sort of cache key. You could ostensibly have two different loggers for any given type if there were two different repositories, each based on a different assembly. It's... an interesting and somewhat complex thing.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. I think log4net was probably the origin of this decision (it was the main influence on conventions in Serilog at the beginning).

This needs some thought - unfortunately it's not a change we can make quickly, but I'll definitely loop back around to this when I have time to think it through properly.

**Comment by tillig** [comment]
No worries, just trying to help. Let me know if there's anything else I can do.

**Comment by zvirja** [comment]
There is an exotic issue related to Ubuntu-based docker images. Apparently the convention for Ubuntu is to have all the environment variable keys uppercased and without DOTS in names. If I configure docker image and pass key not in upper case or containing dot, apparently Ubuntu simply ignores that environment variable. Could be related to [this](https://unix.stackexchange.com/a/93533). So we are restricted to uppercase characters and underscores in key. 

That lead to an issue if I try to override minimum level with env variable as

this is simply omitted by Ubuntu:

```
SERILOG__MINIMUMLEVEL__OVERRIDE__MyApp.MyService=Verbose
```
and this does not work due to case-sensitive match and replaced DOT:

```
SERILOG__MINIMUMLEVEL__OVERRIDE__MYAPP_MYSERVICE=Verbose
```

We could of course perform case-insensitive match, but that would not help. For `Product.My_Service` and `Product.My.Service` configuration will looks the same -> `PRODUCT_MY_SERVICE`, so normalization will need to be implemented at a moment we test input value, which is of course dirty 😟 

I do not see a nice way to overcome that without changing configuration schema (so that type name is passed in value, not key). But wanted to post it here, so you are aware 😉

**Comment by nblumhardt** [comment]
I don't think this is a change we are likely to make in the near future; closing as stale, but thanks for raising it nonetheless. (Hope all's well with you @tillig 👋)

**Comment by tillig** [comment]
Somewhat related - serilog/serilog-settings-configuration#386 found that the parser for the log level enum in configuration was inconsistently case-sensitive and case-insensitive, and that got resolved to be case-insensitive everywhere. That makes things just slightly more inconsistent: enum parsing is case-insensitive, but the keys are case-sensitive.
