### ISSUE TITLE
Asynchronous support throughout Serilog

### ISSUE THREAD

**Issue by nathan-alden-sr** [serilog/serilog#134]
Practically all of Serilog could benefit from asynchronous programming with .NET 4.0+ and  C# 5.0. For example, the `ILogger` interface currently lacks `*Async` methods. This means I have to write my own `Task.Run()` wrappers in order to get basic asynchronous support. Serilog interfaces with many external systems that really should use the TPL--ElasticSearch, file system, CouchDB, etc.

I would love to see a Serilog 2.0 that exposed all its existing interfaces asynchronously. Let's be sure we're using server threads as efficiently as possible!

**Comment by Mystere** [comment]
I think a lack of async/await support is a mistake.  Particularly since it seems that you are basing this decision upon the implementation of http based sinks that use timers to ship logs.  Much has been made about how dangerous using timers for such recurring jobs can be (see: http://haacked.com/archive/2011/10/16/the-dangers-of-implementing-recurring-background-tasks-in-asp-net.aspx/) for example.  It's recommended that if you're using Timers, you should register them with IRegisteredObject.  I know you're subscribing to shutdown events, but i'm uncertain if that is truly wise.

Given the pervasiveness of async/await going forward in ASP.NET and general .NET development, especially in ASP.NET 5, I would urge you to reconsider adding native Async versions of the API rather than using the timer based batching that you currently use.  I would also urge you to implement some kind of contextual isolation of these logs, particularly for durable ones so that we don't have to disable overlapped recycling, and have less chances of log file locking with multi-user scenarios.

**Comment by SimonCropp** [comment]
@nblumhardt so a year later and do u still think this is a bad idea?

i think this 

>  if we awaited a network call for each event written to one of these we'd bomb application performance

is not the approach you would use. you would actually return the task all the way up and let the root application decide to await or not based on how important they think the log message is and the context they are in

am i missing something?

**Comment by nblumhardt** [comment]
Hey @SimonCropp ! ... I think it would be _really_ interesting to create an async Serilog fork as a PoC, but yes, I still expect we'd hit some really tough trade-offs.

For example, Serilog supports multiple sinks in a pipeline, all of which might be asynchronous. The code that dispatches a single event to multiple sinks would need to itself return a task, so you end up having to create an array of the `Task`s returned from each sink's `Emit()` and return `Task.WhenAll(...)` from the dispatcher. That's a lot of allocation and runtime machinery to get into the action for every single log event.

I don't think this particular case would be a blocker, except that the only argument for using `async` is performance, and it doesn't seem like a great trade-off to swap a theoretical performance improvement in some cases for a definite degradation in all others.

Having said that, if I had the time I'd give the whole "asynchronous logging framework" thing a try anyway, it does sound like a very interesting design challenge. Favorable benchmarks from AsyncSerilog vs Serilog would be surprising to see though.

**Comment by nblumhardt** [comment]
@Mystere I suspect a `Task<T>` that is in progress but not completed has all the same problems as a background thread unfortunately - the runtime doesn't automatically `await` anything completing during shutdown, so unless every logging statement is `await`ed in an HTTP response handler I think it will still be possible to lose data in edge cases. In practice, hooking shutdown seems to work reasonably, and in ASP.NET 5 CoreCLR apps you can instead call `LogContext.CloseAndFlush()` in Serilog v2 to ensure the pipeline flushes.

I'd love to solve the overlapped recycling issue BTW, still not entirely happy we've cracked it. I don't think async support would make a difference here though - multiple processes sharing a writable file is a tough nut to crack.

Thanks for the feedback all the same, I'm sorry I didn't get back to responding here earlier. Cheers!

**Comment by aKzenT** [comment]
I think it is time to consider reopening the discussion about async support.

Just as a starting point for discussion I created the pull request #950 in which I changed the sink and logger interfaces to return a Task, implementing the async pattern, so that you can easily do your own experiments, benchmarks, etc.

Unit tests are all green and I already did some performance tuning. Feedback appreciated!
