### ISSUE TITLE
Sublogger Ignoring Events from Parent Logger

### ISSUE THREAD

**Issue by jceddy** [serilog/serilog#1346]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [X] Bug
- [ ] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
Serilog.AspNetCore 2.1.1

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [X] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
I set a Default MinimumLevel in my Serilog configuration of Debug, and override the MinumumLevel of one of my SourceContexts to "Verbose".
If I log directly to a Sink (File Sink, for example), it works as expected, with everything except the overridden source being filtered to Debug or higher, but Verbose events making it through for the overridden source.
If I instead put a sub-logger between the main logger and the file sink (to add a filter or something), the Verbose events from the overridden source don't make it through.

Here is a snippet from my appsettings.json configuration file:

```
  "Serilog": {
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "System": "Information",
        "Microsoft": "Information",
        "Namespace.BenchmarkTimer": "Verbose"
      }
    },
    "WriteTo": [
      {
        "Name": "Logger",
        "Args": {
          "configureLogger": {
            "Filter": [
              {
                "Name": "ByIncludingOnly",
                "Args": {
                  "expression": "StartsWith(SourceContext, 'Namespace.BenchmarkTimer')"
                }
              }
            ],
            "WriteTo": [
              {
                "Name": "File",
                "Args": {
                  "path": "d:\\path-to-log-folder\\Benchmark Timer.txt"
                }
              }
            ]
          }
        }
      }
    ]
  },
```

**Please describe the expected behavior?**
All of the events from the parent logger make it through to the sinks configured in the sub-logger.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
Configure an application as described above. Write verbose logs from SourceContext "Namespace.BenchmarkTimer". The verbose events will not make it to the sub-logger's configured File Sink.

**Note**: I did try setting restrictedToMinimumLevel to "Verbose" on the sub-logger, which didn't make a difference.

**Comment by jceddy** [comment]
I discovered that I could set MinimumLevel to Default "Verbose" in the configureLogger argument of the sub-logger, so I have a workaround. This still seems like a bug to me...shouldn't sub-loggers inherit the minimum levels of the parent logger?

**Comment by nblumhardt** [comment]
@jceddy yes, I believe they should; I am not sure whether the issue lies in _Serilog.Settings.Configuration_ (we may be setting the sub-logger's level when is should be left alone), or, if it's because the "apply inherited configuration" mechanism that's used to configure sub-loggers is not accounting for below-minimum-level writes from the parent logger.

If anyone has a chance to investigate and/or construct a minimal test case using the C# API that would be a great help.

Cheers,
Nick

**Comment by maciejw** [comment]
@nblumhardt I'll try to fix it :) I need this in my project ;)

**Comment by tsimbalar** [comment]
This vaguely rings a bell, like something we tried to fix and gave up :-/

https://github.com/serilog/serilog/issues/967

**Comment by maciejw** [comment]
@tsimbalar this is exactly it, I'll try nevertheless :)

**Comment by maciejw** [comment]
Ok, few notes, after I've poked around a bit:

this scenario is important to me:
When we have more than one sink, lets say audit file and application file and I want to log audit events on info level, but application events I want to log from microsoft & system on warning (default level), my app on info (MyApp), when time comes, I want to switch one of my modules (MyApp.ModuleX) to debug. because I dont want to have 100gig logs I cannot set all to debug, or set every root namespace to some level. this is not practical. 

To do this with serilogs Minimumlevel.Override() its tricky indeed because serilog uses logger as sink, but also loggers have hierarchy because of ForContext, with no context of override maps defined in sink loggers.

The easiest thing to do is to set every logger and sink Minimumlevel to verbose and use filters with some configuration like LevelOverrideMap evaluated with every event and on specific sink.

Since you want to remove MinimumLevel altogether filters are the only place to do this. maybe we have to pursue this direction. new api, so it has no impact on existing codebsae, it can be done in external library I think.
maybe something like this already exists?:) if not, I can do it.

**Comment by maciejw** [comment]
out of curiosity what kind of performance degradation is acceptable in case of filtering
these are results for for loop that is producing 100000 log events

first two has been done using flters on sublogger sink and last two, use minimum level with overrides no subloggers, except ForContext

Category: Overrides, excluded by default level elapsed 280 ms
Category: Overrides, included by override category level elapsed 279 ms
Category: MinimumLevel, excluded by default level elapsed 6 ms
Category: MinimumLevel, included by override category level elapsed 124 ms

quite a big difference

here is sample repo https://github.com/maciejw/serilog-filter-overrides

I'll try to pinpoint where the difference comes from.

**Comment by flyingpianoman** [comment]
Is there any update on this, running into this issue as well.

**Comment by klinki** [comment]
I just run into this issue as well. It's quite annoying :(

**Comment by nblumhardt** [comment]
@tsimbalar @maciejw this isn't the same issue as #967, as far as I can tell.
