### ISSUE TITLE
Move ILogger abstractions out of Serilog package

### ISSUE THREAD

**Issue by sungam3r** [serilog/serilog#1358]
**Does this issue relate to a new *feature* or an existing *bug*?**

- [ ] Bug
- [x] New Feature, breaking changes

In essence, this package is used by two sides - message providers and its consumers. If I am writing a library and want to integrate the serilog into it, then most likely I will only need to publish (log) messages about what is happening in that library. That is, I need an `ILogger` (which I can get through DI) and a few types around him - `LogEventLevel, etc.`. Parsing, formatting, filters, and more will never be needed. They are used by the consuming party.

In this case, I would like to be able to depend only on the publisher's abstractions. **They are much more stable and will change less frequently**.

This example can be cited: [Microsoft.Extensions.Logging](https://www.nuget.org/packages/Microsoft.Extensions.Logging/) depending on [Microsoft.Extensions.Logging.Abstractions](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions/)

Relates to #1100

**Comment by nblumhardt** [comment]
Thanks for the suggestion!

We looked at this option back around the "great package split" of 2.0, and decided against it back then because the transitive closure of dependencies from `ILogger` started to feel semi-arbitrary (things like `LogEventProperty`, `TextToken` etc.; and the `LogContext` implementation caused further non-abstract types to also be pulled in at the consuming side.

If we were determined, we could factor around some of these, but it's more likely to be something we'd do as part of a full API overhaul ("3.0" or "4.0") than a standalone change. Shifting types between packages right now would cause more churn and tooling pain than any potential churn in the types themselves (we've avoided breaking changes in the binary API for several years, now.)

I'd rather close this for now but keep the general idea in mind when/if we embark on some wider changes in the future.
