### ISSUE TITLE
LogContext Properties not overriding existing Property values

### ISSUE THREAD

**Issue by jceddy** [serilog/serilog#1379]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [X] Bug
- [ ] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
2.9.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [X] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
When I push a Property onto the log context, it doesn't override an existing property with the same name.

I have the following logger configuration:

			var config = new LoggerConfiguration()
				.Enrich.WithProperty("Source", "Server")
				.Enrich.FromLogContext();

And some code that does:

					using (LogContext.PushProperty("Source", "Client"))
					using (LogContext.PushProperty("ClientLogger", true))
					{
						Logger.Debug("Debug Message");
					}

The generated log contains the properties:
Source => Server
ClientLogger => true

**Please describe the expected behavior?**
I expect that LogContext.PushProperty("Source", "Client") will override the value of Source from "Server" to "Client".

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
I believe the code snippets above are enough to reproduce the issue, but can provide more if necessary.

**Comment by jceddy** [comment]
FYI: I solved my immediate issue by creating two separate loggers, but this still seems like a bug to me.

**Comment by nblumhardt** [comment]
Thanks for the note, @jceddy 👍 

This is by design - in the end, we had to make a call on which "wins" - the context value or the one from the message.

On the one hand, context values are needed for correlation and tracking down related events, so they may be preferred in some scenarios

On the other hand, replacing properties that appear in the message with ones from the context could lead to the meaning of the message changing/becoming misleading.

Long ago, we had to make a call, and decided to favor properties from the message; it's been a reasonable choice, and changing direction now would cause problems downstream, so we're not likely to change direction here.

You can work around it by creating your own `ILogEventEnricher` and `Push()`ing that onto the `LogContext` instead of the individual property values. Then, in its `Enrich()` method, instead of calling `AddPropertyIfAbsent()`, as the default log context enrichers do, call `AddOrUpdateProperty()` and replace the existing values.

Hope this helps, let me know if you need more info. Thanks again!

**Comment by jceddy** [comment]
I'm a little confused about what you mean by properties that "appear in the message". In my example, the "Source" property does not appear in the message, it is only ever added my an enricher.  
  
Are you really just saying that with the "default" serilog enriched, the first enriched "wins"? Does that mean I can just switch the order of the enrichers in my logger configuration to get the result I'm shooting for?

**Comment by nblumhardt** [comment]
Ah, sorry, misread your post; yes, that's right - switching the enrichers around should do it :-)
