### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by HppZ** [serilog/serilog#1386]
this repo can reproduce the bug.
https://github.com/HppZ/TestSerilog.git

2019-11-18 13:40:51.201 +08:00 [INF] [{"id":"play004","next":[[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[[[[]],[[]],[[]],[[]]],[[[]],[[]],[[]],[[]]]]],[[]],[[]],[[]],[[]],[[]]],"content":{"t":"000f4253","u":"A","v":true,"$type":"Content"},"$type":"Datum"},{"id":"play005","next":null,"content":{"t":"000f4252","u":"A.mp4","v":false,"$type":"Content"},"$type":"Datum"}]

**Comment by nblumhardt** [comment]
Hi! Thanks for the report. This is happening because your `next` property is of type `object`:

https://github.com/HppZ/TestSerilog/blob/f319fc92c8f90774f585295b87b2376ce87b1f1a/TestSerilog/App.xaml.cs#L37

When JSON.NET deserializes that, it will instantiate a dynamic value type such as `JObject`, which is not automatically able to be understood by Serilog (it implements `IEnumerable`, for example, causing it to be considered a collection).

Installing and configuring https://github.com/destructurama/json-net will sort this out.

**Comment by HppZ** [comment]
can i use newtonsoft json lib in serilog?

**Comment by nblumhardt** [comment]
Yes, check out the link in my comment above 👍

**Comment by HppZ** [comment]
thanks, issue fixed.
but why serilog can't understand object property?

**Comment by nblumhardt** [comment]
Serilog _does_ understand the object - it's just that its understanding isn't the one that's most useful :-) ... If you're curious, stepping through the Serilog pipeline when destructuring a JSON.NET object will show you how these appear from a reflection standpoint. Hope this helps!
