### ISSUE TITLE
Request: User defined time provider

### ISSUE THREAD

**Issue by ChristophAxthelm** [serilog/serilog#1398]
**Does this issue relate to a new *feature* or an existing *bug*?**

- [ ] Bug
- [x] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**

Serilog 2.9.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netCore 2.0
- [x] netCore 1.0
- [x] 4.7
- [x] 4.6.x
- [x] 4.5.x

**Please describe the current behavior?**

Serilog currently uses `DateTimeOffset.Now` to create the timestamp for each new log event. The precision of this time is in the range of 10 milli seconds, which is sufficient for most applications. However for some use cases is required to get a more precise timestamp.

**Please describe the expected behavior?**

For that reason it makes sense to extend Serilog to accept a time, which "somehow" is provided by the user of Serilog.

Options:

1. Pragmatic and easy, but less "beautiful": Add a method for Serilog.ILogger.Write() with a DateTimeOffset parameter: `Write (DateTimeOffset, LogEventLevel, Exception, string, object[])`
2. Allow configuring Serilog to use a user defined time provider. Example:
   ```
   Action<DateTimeOffset> myTimeProvider = ...;
   new LoggerConfiguration()
       .ConfigureTimeProvider(myTimeProvider)
       ....;
   ```

**Comment by bartelink** [comment]
I'd use such a feature to use `DateTimeOffset.UtcNow` so no enricher is required to make a Utc date.

(As a workaround, you can currently add an enricher that adds a property for your custom date)

**Comment by nblumhardt** [comment]
:+1:

The "pragmatic" option is already supported through `Write(LogEvent)`, AFAIK.

You can also implement the second option today, at the expense of a few allocations, using the code from this example:

https://github.com/nblumhardt/serilog-sinks-timewarp/blob/master/Serilog.Sinks.TimeWarp/Program.cs#L42

(Instead of setting every timestamp to a Sunday, the delegate can switch it to UTC, replace it with a more precise one, etc.)

I'd most like to support these scenarios through this "middleware" style of extension point, and did quite a lot of work on a `struct`-based replacement logging pipeline for v3. If we don't find the time to make that (extensive) change right now, a per-`LoggerConfiguration` clock might do the job - keen to know if the time-warp solution is useful in the meantime, though.

**Comment by ChristophAxthelm** [comment]
Hi,

thank you very much for your answers. I tried both your approaches (Enricher + "TimeWarp"). Both approaches have similar timing results. The time between calling the log method and the time which is logged is mostly in the range of micro seconds. But this values vary and are not deterministic.

@nblumhardt:
The `Write(LogEvent)` apporach has the problem, that `MessageTemplateProcessor` is private and therefor cannot be used for creating the `MessageTemplate` and `Properties`, which are needed to Create a new LogEvent.

Would it be possible that you introduce such a time provider approach in near-term? I would be willing to propose a pull request, but at the moment I am stuck with the time consuming process of my company to get the OSS contribution permission.

Best regards,

Christoph
