### ISSUE TITLE
Serilog dump database entities to log file

### ISSUE THREAD

**Issue by PeterLarsen-CPH** [serilog/serilog#1407]
We have been using Serilog.AspNetCore 2.1.1 for some time now without any serious issues.

Yesterday I noticed that Serilog was dumping data from tables directly to the log-file.
I have found, that I can prevent this from happening by using the following override:

`"Microsoft.EntityFrameworkCore.Database.Command":"Warning"`

but it seems to me as a huge risk to have a log framework, that by itself, can start dumping huge amount of highly sensitive data to a file or other media added.

I know it must be a feature, but to me its a risk and I know what will happen if the Risk & Audit folks hear about this

Is this really default behavior and how can I prevent this from happening again please - and I am not talking about setting a propety - because that will not be enough for the risk team since the next developer might change it back by a mistake.

Thank you in advance.

**Comment by nblumhardt** [comment]
Hi Peter, thanks for getting in touch.

This isn't due to Serilog; the entries you're seeing are from EntityFramework, hence the namespace attached to the log events. (Serilog doesn't know anything about databases, entities, or what data is in the events that pass through it.)

You might be able to get some advice from the EF project, or from Stack Overflow with the `entityframework` (IIRC) tag.

On the Serilog side, there have been a few efforts over the years to detect sensitive data in the logging pipeline; check out `ITextFormatter`, if you're logging to a file- you may be able to add a "backstop" by wrapping the default text formatter (`MessageTemplateTextFormatter` or one of the JSON ones) and inspecting its output before passing the result through to the log file.

HTH,
Nick

**Comment by PeterLarsen-CPH** [comment]
Hi Nick and thanks,

I could not get my head around how Serilog was able to do this, so this make sense :-)

Many thanks for taken the time to explain.
Peter
