### ISSUE TITLE
make Serilog/Rendering/ public

### ISSUE THREAD

**Issue by JanEggers** [serilog/serilog#1425]
**Is your feature request related to a problem? Please describe.**
what a coworker of mine is requesting is omitting stacktraces of certain exception types because logfiles get too large / cluttered. Because im using seq i dont wanted to manipulate the logevent itself just its formatting to the textfile. to do that i  grabbed the code of MessageTemplateTextFormatter to start customizing it. I copied over classes from rendering namespace because they are internal right now.  

the problem is not solvable because MessageTemplateRenderer relies on internal properties.

**Describe the solution you'd like**
make Serilog/Rendering/ public

maybe you have another suggestion on how to omit stacktraces for file sink.....

**Comment by nblumhardt** [comment]
Thanks Jan!

At the moment, I think your workaround (grabbing the code) is the better option, since your copy is likely to keep working because those types generally rely on stable parts of the Serilog API, and keeping Serilog's copy internal avoids us having to to keep those APIs stable over time (each public API translates for us into a part of Serilog that's harder to change and improve).

Although I think we should close the issue, it's a good data point in case others have the same needs and raise this again down the track (always open to re-evaluating :-))

**Comment by JanEggers** [comment]
@nblumhardt can you please check I updated the issue. MessageTemplateRenderer relies on internal properties.

instead of TokensArray I can use Tokens.ToList() but what can i use instead of rawtext?

https://github.com/serilog/serilog/blob/2c7dbbfad6c607adad6a57f86e8cd680ddf620a1/src/Serilog/Rendering/MessageTemplateRenderer.cs#L45

https://github.com/serilog/serilog/blob/2c7dbbfad6c607adad6a57f86e8cd680ddf620a1/src/Serilog/Rendering/MessageTemplateRenderer.cs#L69

**Comment by JanEggers** [comment]
also 

error CS1501: No overload for method 'Render' takes 4 arguments

https://github.com/serilog/serilog/blob/2c7dbbfad6c607adad6a57f86e8cd680ddf620a1/src/Serilog/Formatting/Display/MessageTemplateTextFormatter.cs#L96

**Comment by JanEggers** [comment]
and also PropertiesOutputFormat PositionalProperties and NamedProperties are internal

**Comment by JanEggers** [comment]
for scalarvalue I use 
                        new ScalarValue(logEvent.Timestamp).Render(writer, pt.Format, _formatProvider);
instead of ScalarValue.Render(logEvent.Timestamp, writer, pt.Format, _formatProvider);

**Comment by liviriniu** [comment]
@JanEggers I also have planned for my project that uses Serilog logging, to omit conditionally stack traces of some particular logged exceptions. My plan is to first see what https://github.com/RehanSaeed/Serilog.Exceptions can help me with and if not suitable, I think I would build another custom enricher for filtering exceptions and/or strip them of what I don't want to bloat the logs.

If you're facing the same need as I have, I imagine that you ended diving into `MessageTemplateTextFormatter` because a custom enricher approach didn't work?

**Comment by JanEggers** [comment]
> If you're facing the same need as I have, I imagine that you ended diving into MessageTemplateTextFormatter because a custom enricher approach didn't work?

the enricher would do the job I guess, but enrichers work for all sinks and I just want to remove the stacktrace when logging to a file for other sinks the stack should still be present.

**Comment by liviriniu** [comment]
This seems good for a chat. Would it be appropriate to contact me on Gitter IM for serilog privately and sort it out? Then you can post the result here...

**Comment by JanEggers** [comment]
problem solved:

```
    /// <summary>
    /// this formatter wrapps the default implementation and omits stacktraces for the filtered exceptions
    /// </summary>
    public class OmitStacktraceFormatter : ITextFormatter
    {
        private readonly ITextFormatter _inner;
        private readonly Func<Exception, bool> _exceptionFilter;

        public OmitStacktraceFormatter(ITextFormatter inner, Func<Exception, bool> exceptionFilter)
        {
            _inner = inner;
            _exceptionFilter = exceptionFilter;
        }

        private readonly MessageTemplateParser _parser = new MessageTemplateParser();

        public void Format(LogEvent logEvent, TextWriter output)
        {
            if (_exceptionFilter(logEvent.Exception))
            {
                logEvent = new LogEvent(logEvent.Timestamp, logEvent.Level, null, _parser.Parse(logEvent.MessageTemplate.Text + "{"+ nameof(logEvent.Exception) + "}"), logEvent.Properties
                    .Select(p => new LogEventProperty(p.Key, p.Value)).Concat(new []
                    {
                        new LogEventProperty(nameof(logEvent.Exception), new ScalarValue(logEvent.Exception.Message)), 
                    }));
            }

            _inner.Format(logEvent, output);
        }
    }
```

**Comment by liviriniu** [comment]
As part of my suggestion with using a custom enricher and for future reference: https://stackoverflow.com/questions/52322074/is-there-a-way-to-specify-that-a-particular-enricher-should-only-be-used-for-a-s
