### ISSUE TITLE
Create interface for LoggingLevelSwitch

### ISSUE THREAD

**Issue by mattvaughan** [serilog/serilog#1436]
**Is your feature request related to a problem? Please describe.**
I'd like to create an interface for LoggingLevelSwitch or make MinimumLevel virtual. Basically, I have log level values being set "Behind the scenes" of a library beyond my control. You get the level when you read it, but you don't get notified when it changes, so I can't update the MinimumLevel of a LoggingLevelSwitch object on the fly.
I'd like to override the implementation of MinimumLevel to read from this third party SDK.

**Describe the solution you'd like**
Represent the Logging Level Switch as an interface instead of a class

**Describe alternatives you've considered**
Make the MinimumLevel property virtual

**Comment by mattvaughan** [comment]
#1437

**Comment by nblumhardt** [comment]
Hi Matt, thanks for the notes and PR 👍 

This is a design alternative we considered, but chose not to implement, because of the performance critical role of `LoggingLevelSwitch` in the "logging is off" path.

Creating a worker thread to periodically check the required level and adjust switches accordingly may be the best solution available right now.

Another option would be to create an `ILogger` wrapper for Serilog, forwarding to the default Serilog implementation, that uses custom logic in `IsEnabled(LogEventLevel)`.

**Comment by mattvaughan** [comment]
@nblumhardt Thanks for taking a look. So if I understand it correctly, you're saving users from implementing a level check that performs poorly? Or are you saying that using an interface affects performance directly?

**Comment by nblumhardt** [comment]
Hi @mattvaughan - thanks for your reply.

One of the core performance aims of Serilog is that when logging is "off", statements like:

```csharp
_log.Debug("Iteration {N} of {M}", n, m);
```

should be as close to free/zero-cost as possible (imagine `M` is one billion :-)). We jump through some hoops so that there are no allocations, and normally, just an integer comparison for the level check in addition to the call. On an `ILogger` the call itself will still cost one virtual dispatch, which is the main cost.

Using the current level switch (instead of a fixed level), there's an additional volatile read, which is also potentially expensive, but there's a chance this can be removed through some additional changes (`Interlocked.MemoryBarrierProcessWide()` and non-virtual reads).

Making the switch an interface would add one more virtual dispatch to the overhead, which, while it would be entirely reasonable for users who need the functionality, it's hard to justify adding this overhead on every call, and as these things add up, we've historically been very hesitant to let additional slowdowns into the "off" path.

Hope this helps, and sorry my explanation is a bit rushed!

Nick
