### ISSUE TITLE
serilog-sinks-console in docker Chinese garbled code appears, How to solve it

### ISSUE THREAD

**Issue by lkd3063601** [serilog/serilog#1454]
public static IHostBuilder CreateHostBuilder(string[] args) =>
Host.CreateDefaultBuilder(args)
.ConfigureWebHostDefaults(webBuilder =>
{
webBuilder.UseStartup();
}).UseSerilog((context, configuration) =>
{
configuration
.MinimumLevel.Warning()
.MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
.Enrich.FromLogContext()
.WriteTo.Console(theme:ConsoleTheme.None)
.WriteTo.File(Path.Combine("logs", @"log.txt"), rollingInterval: RollingInterval.Day);
});

![luama](https://user-images.githubusercontent.com/15059204/86262096-0646bb80-bbf2-11ea-8d13-1d32757bf8bd.png)

**Comment by nblumhardt** [comment]
Hello! It's not clear where the issue lies, here. Specifying an encoding for the console, when your app starts up, may help; for example:

```csharp
System.Console.OutputEncoding = new UTF8Encoding(false);
```

Otherwise more info might be needed to solve this. As it's a usage issue (Serilog doesn't make any changes to console output encoding) Stack Overflow will be a better place to find help for this.

All the best,
Nick

**Comment by lkd3063601** [comment]
I found the reason，my Program.cs  Encoding is ANSI ，So in the Program.cs Chinese characters printed in Chinese are garbled

**Comment by nblumhardt** [comment]
Awesome, glad you could track it down :+1:
