### ISSUE TITLE
Add extension methods for lazy evaluated property values

### ISSUE THREAD

**Issue by thomashauser** [serilog/serilog#1458]
For DEBUG messages, some property values are often expensive to generate. But if the LogLevel is set higher, the objects are still passed calculated. Unfortunately there is no overload for lazy evaluated property values.

**Comment by rafaelsc** [comment]
Can you give us an example of this problem?

I did not see how your PR would help with that.

**Comment by thomashauser** [comment]
You can provide the Func to the new extension method. The ToString method of the LazyPropertyValue object will only be called, if the corresponding log level is set and the message will be logged.
```
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.Console(Serilog.Events.LogEventLevel.Debug)
                .WriteTo.Debug()
                .CreateLogger();

            Log.Logger.Debug("Mein {test}", () =>
            {
                Debug.Write("Thread.Sleep...");
                Thread.Sleep(1000);
                Debug.WriteLine("OK");
                return "xxx";
            });

```

**Comment by rafaelsc** [comment]
I understood better now, you want to call a function to get one log property. 

But instead of this: 

```csharp
	Log.Logger.Debug("My {test}", GetComplexLogProp());

	string GetComplexLogProp()
	{
		Debug.Write("Calling the Fucntion to get a value...");
		return "xxx";
	}
```

You want to use a delegate to the lazy call the function, similar to this but this is not supported now in Serilog.
```csharp
	Log.Logger.Debug("My {test}", GetComplexLogProp); //ERROR: CS1503 Argument 2: cannot convert from 'method group' to 'object'

	string GetComplexLogProp()
	{
		Debug.Write("Calling the Fucntion to get a value...");
		return "xxx";
	}
```

I particularly don't like the idea of integrating this solution to the main codebase. And I never had the need to call a slow function to process one property for a log entry using Serilog.

Lazy calling a function to get the properties will introduce a lot of *side effects* that will make it hard to debug in production code.

And your solution will not work was expect internally in Serilog, like in this exemple;
```csharp
	Log.Logger.Debug("My {@test}", GetComplexLogProp);

	object GetComplexLogProp()
	{
		Debug.Write("Thread.Sleep...");
		Thread.Sleep(1000);
		Debug.WriteLine("OK");
		return new {Prop1= 0, Prop2 = "Hi"};
	}
```

This could become a future feature request to be implemented in a way that works with all other Serilog features and working in a predicted way.

But this is my opinion, I don't know the @nblumhardt opinion.

**Comment by nblumhardt** [comment]
Thanks for the PR!

In the cases where this is required, the recommended approach is:

```csharp
if (Log.IsEnabled(LogEventLevel.Debug)
{
    Log.Debug("Some expensive {Computation}", Compute());
}
```

Lambdas introduce allocations/captures, and require almost exactly the same number of lines of code, so we don't provide an equivalent lambda-based API for this.
