### ISSUE TITLE
Repeated placeholders within a message template cause selfLog to incorrectly log a message

### ISSUE THREAD

**Issue by 57r480** [serilog/serilog#1464]
**Description**
When passing a placeholder into a message template more than once, it updates a sink correctly but selfLog writes the line 'Positional property count does not match parameter count'.

**Reproduction**
Log.Information("{0}, {0}", "hello");

PropertyBinder.ConstructPositionalProperties() (line 62) compares the number of placeholders to the number of values provided to populate them.
In this case there is a repeated placeholder so it's comparing 2 and 1, resulting in the update to selfLog.

**Expected behavior**
Compare number of unique placeholders with provided values.

**Relevant package, tooling and runtime versions**
v2.9.0
(netCore 3.0)

**Additional context**

**Comment by nblumhardt** [comment]
Thanks for the note 👍 

I think the check here is deliberately simplistic for performance reasons, but if we do the more expensive check only when the parameter count differs, we could at least reduce the false-positive rate, and hopefully won't incur any additional overhead in the hot path.

If anyone's interested in taking a look, we'd need some benchmarks along with this fix.

**Comment by iskcal** [comment]
Hi, @57r480 @nblumhardt.

I have checked the function `ConstructPositionalProperties` in `PropertyBinder`, and it seems that there is a simple way to solve this situation. In this function, the variable `result` records the relations between the placeholders and the log objects, which are not repeated. Therefore, the comparison can be modified to the length of `result` and the length of log objects, and placed after the construction of `result` (Line 89).

The advantage of this solution is that there is no need to add additional logic, so it has little impact on performance. The disadvantage is that it may change the outputs of `SelfLog` in some cases, for example.
```csharp
log.Information("{0}{1}", "hello");
```
Serilog (v2.9.0) firstly outputs "Positional property count does not match parameter count" then outputs "Unassigned positional value...", while this solution outputs "Unassigned positional value...". 

Since it has a breaking change, I don't know whether it is acceptable.

**Comment by iskcal** [comment]
Hi, @nblumhardt Did I miss something?

**Comment by nblumhardt** [comment]
Hi! Sorry, @iskcal - I haven't had a chance to dig in deeply yet.

**Comment by STeeL835** [comment]
So, logging like 
```cs
Log.Information("Processing failed for {Mode}. Check if {Mode} is enabled in 'there'", mode);
Log.Information("Processing failed for {Mode}. Check if {0} is enabled in 'there'", mode);
```
will not be possible right now due to performance reasons? Or is it a different issue?

**Comment by nblumhardt** [comment]
@STeeL835 both are invalid templates (see https://messagetemplates.org), so this is a different issue (the template being discussed in this thread is valid but not properly processed).

**Comment by nblumhardt** [comment]
@iskcal I've made your suggested change (I think!) in #1903 :-)

**Comment by iskcal** [comment]
@nblumhardt It seems to be OK. :-)
