### ISSUE TITLE
Allow developers to react to changes in the MinimumLevel of a LoggingLevelSwitch

### ISSUE THREAD

**Issue by augustoproiete** [serilog/serilog#1468]
**Is your feature request related to a problem? Please describe.**
There's currently no easy way of detecting when the `MinimumLevel` of a `LoggingLevelSwitch` changes, and the recommended workaround is monitoring its value on a timer, which works but is cumbersome.

**Describe the solution you'd like**

There has been requests to make the `MinimumLevel` virtual so it can be overridden, or change it to an interface for custom implementations, (e.g. #1436, #1417, #1232,  and #682), and none of these were implemented because it would considerably affect performance of reads on the `MinimumLevel`.

These requests seem to share the same end goal: Run custom code **when the `MinimumLevel` changes**.

Given that _writes_ to `MinimumLevel` shouldn't happen nearly as often as _reads_, it seems that executing custom code immediately after the value of `MinimumLevel` is changed wouldn't be a big concern in terms of performance - unless I'm missing something (?).

With that in mind, I'd like to propose the introduction of a couple of methods in the `LoggingLevelSwitch` class that allow developers to enable/disable running custom code when the `MinimumLevel` changes.

It could be something along these lines:

```diff
public class LoggingLevelSwitch
{
+   Action<LogEventLevel> _notify;
    // ... (omitted for brevity)

    public LogEventLevel MinimumLevel
    {
        get { return _minimumLevel; }
        set
        {
            _minimumLevel = value;
+           var n = _notify;
+           n?.Invoke(value);
        }
    }
+
+   public void EnableNotifications(Action<LogEventLevel> notify)
+   {
+      _notify = notify ?? throw new ArgumentNullException(nameof(notify));
+   }
+
+   public void DisableNotifications()
+   {
+       _notify = null;
+   }
}
```

**Describe alternatives you've considered**
Monitor instances of `LoggingLevelSwitch` on a timer or background thread.

**Additional context**

If executing custom code in the setter of `MinimumLevel` turns out not to be a bad idea, we could also consider:

- Checking if the new value being assigned is different than the current value and only run the action if that's the case
- Provide previous and actual `LogEventLevel` rather than only the actual
- Allow more than one `Action` to be executed rather than a single one w/ last one wins

I'd be happy to send a PR once a design is agreed.

**Comment by nblumhardt** [comment]
That's an awesome idea! :+1: .... disappointed now that I didn't come up with it :sweat_smile: 

Scenario-wise, having support for multiple listeners, dynamically added, would make it easier for code to interact with a `LoggingLevelSwitch` that it doesn't "own".

 We could follow `ChangeToken`'s registratoion style, and do:

```csharp
IDisposable OnChange(Action<LogEventLevel> listener);
```

where disposing the result would deregister the listener?

Synchronization is interesting; a lock would need to cover both adding/removing listeners, and changing the level, so that listeners always "know" the correct level (interleavings of changing the level and adding listeners shouldn't result in listeners being stale/missing a change).

For that to work,

 * Either `OnChange` would need to immediately call the callback with the current value, when added, or
 * We'd need an `ILevelChangeListener` with `OnRegistered(level)` and `OnChanged(level)`

Last thought ... calling callbacks under a lock is good to avoid; we probably could, here, but not sure it's worth the substantial effort involved. "The callback will be invoked under a lock" might be worth noting in the XDOC for OnChange?

**Comment by bartelink** [comment]
Any reason not to make it a straight Event (or an Observable as you've all but suggested above). [Some notes on Observable vs Events](https://stackoverflow.com/questions/24572366/should-iobservable-be-preferred-over-events-when-exposing-notifications-in-a-lib)

**Comment by nblumhardt** [comment]
Need to give it some thought - probably no reason; events might be a bit simpler of those two. I think explicit callbacks are nice to work with in a lot of cases, and are used as much as the other two, but could just be me, there :-)

**Comment by nblumhardt** [comment]
I'd love to dig into possibilities here further, but I think it's stalled so I'll close it now as stale. Feel free to jump in if you're considering picking this back up :-)
