### ISSUE TITLE
JsonFormatter Not Handling ExceptionDetail Data Properly

### ISSUE THREAD

**Issue by CheetahChrome** [serilog/serilog#1488]
When viewing the outputed Json of the `JsonFormatter` the handling of an `Exception`'s property `ExceptionDetail` of its sub property `Data` comes out as `"System.Object" : null`.

Here is the result Json based on a `System.Exception` object in question, noted the `Data` field:

```
{
	"Timestamp": "2020-09-17T02:01:51.6297808-06:00",
	"Level": "Fatal",
	"MessageTemplate": "Dispatcher",
	"RenderedMessage": "Dispatcher",
	"Exception": "System.Windows.Markup.XamlParseException: 'Provide value on 'System.Windows.Baml2006.TypeConverterMarkupExtension' threw an exception.' Line number '84' and line position '36'.",
	"Properties": {
		"ExceptionDetail": {
			"Data": {
				"System.Object": null
			},
			"HResult": -2146233087,
			"Message": "'Provide value on 'System.Windows.Baml2006.TypeConverterMarkupExtension' threw an exception.' Line number '84' and line position '36'.",
			"Source": "PresentationFramework",
			"InnerException": {
				"Type": "System.FormatException",
				"HResult": -2146233033,
				"Message": "'' value is not valid. It must contain one, two, or four delimited Lengths.",
				"Source": "PresentationFramework"
			},
			"LineNumber": 84,
			"LinePosition": 36,
			"KeyContext": null,
			"UidContext": null,
			"NameContext": null,
			"BaseUri": null,
			"Type": "System.Windows.Markup.XamlParseException"
		}
	}
}
```

The actual `Data` field was reported as  `Data = {System.Collections.ListDictionaryInternal}` with one value. 

---
**Project Code**

I have uploaded my solution to [CheetahChrome/WPFCore](https://github.com/CheetahChrome/WPFCore). To reproduce run the "WPFCore3" wpf app and put a breakpoint at `MainWindow.xaml.cs` line 64 `Log.Fatal(exception, v);` which is about to log the exception.

**Example Exception as JSON**

I attempted to serialize the actual exception to report here and was unable to using the latest serializer (`JsonSerializer.Serialize(exception)` ) and got a JSON Parse exception

> A possible object cycle was detected which is not supported. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 0.

which suggests that if Microsoft can't handle it...its an unfortunately an issue for Serilog.

**Comment by nblumhardt** [comment]
Thanks for the note; this isn't a Serilog core issue but relates to how _Serilog.Exceptions_ is capturing `Data`. Raising this on Stack Overflow and checking out the Serilog.Exceptions issue tracker for previous discussions should help turn up a solution. Good luck with it!

**Comment by CheetahChrome** [comment]
> this isn't a Serilog core issue

To be clear, this happens when I use `JsonFormatter` such as

` ITextFormatter jsonFormatter = new JsonFormatter(renderMessage: true);`

and **it** (*the formatter*) returns invalid json.

So are you saying that  `Serilog.Formatting.Json.JsonFormatter` is not considered a `Serilog` operation? The error does not happen unless I used the above class.

**Comment by nblumhardt** [comment]
Hi William, thanks for the reply. "Serialization" in Serilog is split into two roles:

 * the "capturing" side (which _Serilog.Exceptions_ implements) controls how .NET types `Exception` are mapped to the more limited, JSON-like internal data model represented with `LogEventPropertyValue`, and
 * the "formatting" side (`JsonFormatter`, here) writes out whatever that model represents in JSON text.

The problem you're hitting is on the capturing side - by the time the event gets to `JsonFormatter` all we have is a structure with key `"System.Object"` and value `null`, which it's faithfully recording in the JSON above.

Capturing is tricky because of problems like circular references, as you've observed; exceptions in .NET are particularly nasty to serialize as JSON, hence _Serilog.Exceptions_ is a substantial project in its own right.

Probably a bit much of a fine distinction unless you're deeply into the Serilog internals - but the code responsible will be in _Serilog.Exceptions_ somewhere, and not this repo.

HTH!

**Comment by CheetahChrome** [comment]
Excellent, thank you for taking the time to break it down; I do appreciate it. I will pursue the fix elsewhere. :-)
