### ISSUE TITLE
New core feature: overriding event levels based on predicate / namespace

### ISSUE THREAD

**Issue by tomzorz** [serilog/serilog#1491]
Based on @nblumhardt 's comment [here](https://stackoverflow.com/questions/47036442/change-override-log-event-level-in-serilog/64007508#comment113174882_47046128) on my StackOverflow question about the same topic, I thought it could be handy to have a ticket here to discuss it. 

**The original SO prompt:**

> Is there a way to change the log level of certain events dynamically? (maybe by namespace or a predicate)
> 
> I'm looking for something like .MinimumLevel.Override("Microsoft", LogEventLevel.Warning) but what I really want to do is change the level of Information events coming from the Microsoft namespace to Verbose. Events of higher importance should be left as-is.

The already accepted [answer](https://stackoverflow.com/a/47046128/4788286) solves the issue, but it has a few shortcomings:
- needs to be called for each sink
- can't use configuration file to set it up
- we have to recreate the log events, which would be better if it could be avoided

**Comment by julealgon** [comment]
This is something that would be useful to me as well. We had a requirement where all log entries could only have "Error" level as the "highest severity level" (no critical or fatal). This means ideally I'd like to convert all `Fatal` events into `Error` events before sending them into the sink.

We had to come up with some nasty manual mapping logic in a custom log property inside an enricher to do this conversion. And it is less than ideal, since it still keeps the original level property, just adds a new property that is like the "fixed level".
