### ISSUE TITLE
Customization vs Optimization priorities

### ISSUE THREAD

**Issue by simmotech** [serilog/serilog#1541]
I've been browsing some of the source code and I am confused over some of the micro optimizations implemented that prevent customization.
For example, sealed and internal classes which make adding a _slightly_ tweaked MessageTemplateTextFormatter impossible - you have write a new ITextFormatter from scratch. Padding, for example, is internal yet you would want to use that for consistency.

Yet other more obvious optimizations (to me at least) such as formatting DateTime for timestamp are not there. 
I reckon that could be speeded up 3-fold.

So what is the priority (after correctness of course)?

I'm a complete newbie to github. I also have never used .NET Standard/.NET Core before. I have a vague notion of forking and PRs but if I created a fork and got the whole source onto my machine would I be able to compile it, try out some optimization (the Date formatting for example) and run benchmarks for comparison?
If so, I might be up for having a go but if I need to install every .NET version under the sun and other apps/packages to make it compile, that might be a bit too much for me just now.

**Comment by nblumhardt** [comment]
Hi @simmotech!

Thanks for the note; most of the time, if you find something is sealed or internal, it's because we want to limit the surface area for which Serilog has to maintain backwards compatibility.

Making members virtual or types public means that consumers could rely on them, and then in the future if we come up with a better way of doing things and want to move forward, we're stuck with either bloating the surface area of the library, or breaking backwards compatibility (which is taken very seriously - Serilog's core hasn't had a backwards-incompatible update since 27th June 2016 :-)).

The philosophy guiding the core library is to make as many usage scenarios possible as we can, with the smallest fixed set of APIs. Formatting is a good example of this - there are implementations of `ITextFormatter` out there that all do wildly different things; some copy bits and pieces out of `MessageTemplateTextFormatter`, but not huge amounts of code.

Forking should make it pretty easy to try things out on your own machine (you can even just download a zip of the source code directly from this project without forking). You'll need .NET 5 and potentially some of the Core SDKs, but nothing unusual. Good luck!

**Comment by simmotech** [comment]
Thanks Nicholas

I did indeed get it all running locally after installing many SDKs.
I even found a .ps1 file to run the benchmarking - killed my machine performance for nearly 3 hours!
Eventually, I found where all the output went to.

In the meantime, I tried some simple benchmarking in another app and found that the fast DateTime formatting I mentioned previously is ~11.9x faster than using IFormat on DateTime (4.3x faster if UTC offset is required). Plus it can also be easily adapted to write directly to a TextWriter rather than create a string first.

I'll try and incorporate it into the fork I have and if it still looks promising, I'll raise a PR - is that the right way to do it?
Also, is there a better place to discuss Serilog code in general rather than create a new ticket?

**Comment by nblumhardt** [comment]
Thanks for the update! I'm not sure we'd take a PR to optimize `DateTime` formatting in `MessageTemplateTextFormatter`, with dates/times being such a subtle area - would be interesting to see but not certain we'd merge unless it's almost trivial (just a gut feel, anyway :-))

**Comment by simmotech** [comment]
Ah! I think I misunderstood the meaning of PR then - I thought it was just a way of sharing potential ideas with others - I now see it is the way to tryout/implement a _pre-agreed_ piece of work. Sorry for being presumptuous!

Actually I think that the fork I made is visible to anyone anyway.

I have one last question to ask then I promise I'll stop asking and then close this thread:
How can I run a simple single Benchmark directly from within Visual Studio and see the summary?

I normally use JetBrains' UnitTestRunner and simple use Console.WriteLine() in my unit tests
But that doesn't seem to work here and I don't know if its BenchmarkDotNet configuration or .NET SDK version or if I need 'ITestOutputHelper' as intellisense suggests.

This is test code I want to run - any ideas?

```
    [SimpleJob(invocationCount:100)]
    public class OutputTemplateRenderingBenchmark
    {
        const string DefaultFileOutputTemplate = "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level}] {Message}{NewLine}{Exception}";
        static readonly LogEvent HelloWorldEvent = Some.InformationEvent("Hello, {Name}", "World");
        static readonly MessageTemplateTextFormatter Formatter = new MessageTemplateTextFormatter(DefaultFileOutputTemplate, CultureInfo.InvariantCulture);

        readonly TextWriter _output = new NullTextWriter();

        [Benchmark]
        public void FormatToOutput()
        {
            Formatter.Format(HelloWorldEvent, _output);
        }

        [Fact]
        public void OutputTemplateRendering()
        {
            Console.WriteLine("I am here test");

            BenchmarkRunner.Run<OutputTemplateRenderingBenchmark>(new DebugInProcessConfig());
        }
    }

```

**Comment by nblumhardt** [comment]
> I now see it is the way to tryout/implement a pre-agreed piece of work. Sorry for being presumptuous!

No, that's completely fine! It's okay to send a PR for something unexpected; it's just that it's easy to spend a lot of time building/submitting one, only to have it rejected because it doesn't match the project's goals/plans. Checking in first is usually a good way to avoid this :-)

Can't answer the benchmarking question off the top of my head, sorry - it's been some time since I tinkered with it.

**Comment by Numpsy** [comment]
I haven't tried using it (I generally just run BDN projects from the command line), but there is a VisualStudio extension at https://github.com/szehetner/BenchmarkDotNet-VS-Runner that may or may not be of interest.

**Comment by simmotech** [comment]
Thanks - that looks just the ticket!
