### ISSUE TITLE
Memory Leak with new LoggerConfiguration()

### ISSUE THREAD

**Issue by DaleyKD** [serilog/serilog#1579]
**Description**
When instantiating a `new LoggerConfiguration().CreateLogger()`, it appears that, even though we dispose the `ILogger`, we have a memory leak.

At first, I thought it was purely the MSSqlServer sink (so I did log a bug there), but today I tried two other sinks (Notepad and Debug) and they both had a minor leak, although much, much less.

**Reproduction**
https://github.com/DaleyKD/SerilogMemLeakTest

**Expected behavior**
Disposing the ILogger should give me my memory back (at least soon).  _Do we need to be able to dispose the LoggerConfiguration?_

**Relevant package, tooling and runtime versions**
Serilog: 2.10.0
.NET 5.0.5

**Additional context**
We have a multi-tenant setup, where each tenant has their own database (and each database has the log table).  Our service needs to be able to get an ILogger based on a connection string and then write to the table.

I realize Serilog was designed to have a static instance.  Until we found this memory leak, we thought we were fine.

Trying to keep around long running loggers in some kind of static Dictionary isn't going to work in case we have thousands of tenants.

**Comment by johnduhart** [comment]
@DaleyKD Can you capture two memory dumps (one after your app starts up, and one after a period of time has passed)? This will help identify what objects are not being GCed.

You should be able to do this with Visual Studio: https://docs.microsoft.com/en-us/visualstudio/profiling/memory-usage?view=vs-2019#collect-memory-usage-data

**Comment by DaleyKD** [comment]
I can get the visual representation, but I can't seem to find a way to output it nicely.  Here are some screen caps:
![image](https://user-images.githubusercontent.com/7206282/118690279-860b5380-b7cd-11eb-8924-2641004d93f9.png)
![image](https://user-images.githubusercontent.com/7206282/118690321-93284280-b7cd-11eb-8e8e-82665b325055.png)

I can't seem to get Diagnostic Tools to show the Native Heap?
![image](https://user-images.githubusercontent.com/7206282/118691369-a2f45680-b7ce-11eb-888c-23cf6c74254a.png)

**Comment by nblumhardt** [comment]
Howdy! Serilog wasn't designed around a static instance - short-lived and throwaway loggers are fully supported.

The gotchas that emerge when you create multiple `Logger`s arise from the state held by sinks. E.g. if you create 1000000 SQL server sinks, they'll be creating 1000000 `SqlConnection`s, if you create 1000000 file sinks, they'll be holding onto 1000000 open files, etc. :-)

Sinks also sometimes hold onto exclusive locks, end up registered for callbacks, etc. etc.

Using a single logger is generally the way to avoid having to think about or deal with these kinds of issues, so that's why we frequently recommend it.

For example, in your case you may be able to `PushProperty("TenantId", ...)` onto `LogContext`, and then use `Serilog.Sinks.Map` to manage a pool of SQL Server sinks by mapping tenant ids to connection strings in the mapping function. (Definitely want to set a limit on the number of open sinks when configuring `Map()` in this case, though.

If there is a bug behind this behavior though, it will probably be one of:

 * Your code is not disposing the right root `Logger` returned from `CreateLogger()`
 * You're using an IoC container that tracks `IDisposable` objects, and not using lifetime scopes to clean them up (this is the case in some MEDI configurations)
 * The MSSQL sink is allocating a resource like a connection from a connection pool that isn't fully released on disposal

Getting a count of the objects on the managed heap by type will reveal which of these it is, if it's any of them.

HTH!
 *
