### ISSUE TITLE
Support for possible new API built upon interpolated string handlers in .NET 6

### ISSUE THREAD

**Issue by ThomasMader** [serilog/serilog#1643]
With .NET 6 the possibility of writing interpolated string handlers were added. (https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/interpolated-string-handler)
With that it should be possible to create a new public interface without the need for extra property value arguments for the logging methods.

So instead of

`logger.Debug("This is just an example with: {SomeTestData}", someTestData);`

it could be done with an interpolated string:

`logger.Debug($"This is just an example with: {someTestData}");`

With that it would also be possible to add the caller information (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/caller-information) like calling member, line number via the constructor of the interpolated string handler.

**Comment by nblumhardt** [comment]
Thanks, Thomas; unfortunately the interpolated string handler API doesn't account for parameter names, which substantially reduces the quality of logged events. There are a few past discussion threads in this repo and elsewhere on the different approaches and workarounds attempted so far, but none really satisfactory. If you think we might have missed something new in the .NET 6 functionality let us know, though! 👍

**Comment by ThomasMader** [comment]
Further down the page about interpolated string handlers is an example of how to deal with format strings.
With a similar approach one could also add property names I imagine.

**Comment by bartelink** [comment]
There's nothing stopping you doing a proof of concept as a set of extension methods, is there?

One thing I'd point out is that if you follow the tutorial, one thing I got from it is that there should not be many cases of the same message template being used at multiple places in a codebase - i.e. after reading it, I've rarely had trouble correlating a location back to a code location.

**Comment by nblumhardt** [comment]
@ThomasMader thanks for your reply. It would have to be the C# compiler that added support for property names. The code generated by the compiler calls `AppendLiteral()` with literal text, and `AppendFormatted()` with the actual object (not its name from the source code).

I think the result of the last discussion was that `AppendFormatted()` would need to accept an additional "name" argument that could be derived from the source text in cases where the value in the hole is an identifier like `someTestData`, or could be specified by the user when the value is not (e.g. `$"The sum is {1 + 1#sum}"` - figuring out unambiguous C# syntax for this is non-trivial).

Here's the thread: https://github.com/dotnet/roslyn/issues/142

**Comment by kulakovt** [comment]
Sorry guys for my persistence. I just want to be sure that I understand correctly the reason for the rejection.

> unfortunately the interpolated string handler API doesn't account for parameter names

It's not true anymore. Because:

1. You can use your own implementation of [InterpolatedStringHandler](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/interpolated-string-handler)
2. In your version of `InterpolatedStringHandler` you can implement `AppendFormatted()` method with an additional parameter that has [CallerArgumentExpression](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.callerargumentexpressionattribute?view=net-6.0).

```cs
[InterpolatedStringHandler]
public ref struct StructuredLoggingInterpolatedStringHandler
{
    public void AppendFormatted<T>(T value, [CallerArgumentExpression("value")] string name = "")
    {
        var property = new LogEventProperty(
            name,
            ValueConverter<T>.Default.CreatePropertyValue(value));
        // ...
    }
}
```

This is a proof of concept:
https://github.com/fedarovich/interpolated-logging-demo/blob/master/InterpolatedLoggingDemo/Program.cs#L16

**Comment by nblumhardt** [comment]
That's interesting, @kulakovt - I hadn't considered `CallerArgumentExpression`, here.

Worth some more thought. I'm still unsure about how easy it would be to create low-quality structured log events this way, but given the frequent (mis-)use of interpolated strings as logger arguments, there may be some value in it nonetheless.

Couple of things to think about:

 * Any ideas for property names when the hole looks like `{1 + 1}`?
 * Will analyzing property names lead to perf problems?
 * Will constructing message templates with string builders on-the-fly lead to performance problems?

**Comment by kulakovt** [comment]
> Any ideas for property names when the hole looks like {1 + 1}?

Now, in case: `logger.LogInformation($"{1 + 1}");`
`AppendFormatted` will receive `value = 2, name = "1 + 1"`. I believe this behavior is simular to Serilog (with manual template parsing). 

> Will analyzing property names lead to perf problems?

This is entirely the work of the compiler. After compilation, all property names will be just a string constants in the assembly. There is no penalty for runtime.

- [Andrew Lock about CallerArgumentExpression](https://andrewlock.net/exploring-dotnet-6-part-11-callerargumentexpression-and-throw-helpers/)

> Will constructing message templates with string builders on-the-fly lead to performance problems?

By the way, [this method](https://github.com/fedarovich/interpolated-logging-demo/blob/master/InterpolatedLoggingDemo/StructuredLoggingInterpolatedStringHandler.cs#L37) uses a new overload
`StringBuilder.Append(ref System.Text.StringBuilder.AppendInterpolatedStringHandler handler)`
This overload also uses the new string interpolation mechanism.

The author of the [origin repository](https://github.com/fedarovich/interpolated-logging-demo) (@fedarovich) wrote an article about this approach. There are some comparisons and benchmarks there:

- [Structured Logging and Interpolated Strings in C# 10](https://habr.com/ru/post/591171/)

**Comment by bartelink** [comment]
>I believe this behavior is simular to Serilog (with manual template parsing).

The point is that in normal real Serilog, you write `Log.Information("The value is {total}", 1 + 1)`, and the json is reliably always `[{"total": 2}]`. There is no "with manual template parsing".

If there isn't a proper workable solution that reliably gives a stable property name even with refactoring, that's a risk as you can't simply throw an exception to say "you passed 2+2, please use the special named syntax `{2+2:total}`" etc. Even if something like Serilog Analyzer was to trap these cases, it's still dangerous. 

What do I mean by dangerous? The fact that bad log entries not obeying the intended structure are silently propagating through the stores. If anyone has searches that rely on the structure, they can get broken. Or, if I am doing random queries that presume the presence of a field called `"total"` in the message, I can go a long way down the rabbit hole before I go on an an angry `git blame` chase ;)

**Comment by kulakovt** [comment]
@bartelink , what is the behavior of Serilog in this case:
`Log.Information("The value is {1 + 1}", 1 + 1)` ?
This is a closer example.

**Comment by kulakovt** [comment]
- [String Interpolation in C# 10 and .NET 6](https://devblogs.microsoft.com/dotnet/string-interpolation-in-c-10-and-net-6/) by Stephen Toub — a lot of under the hood details and  performance optimizations.

**Comment by bartelink** [comment]
@kulakovt I'd have to try but...

The rules match String.Format rules, i.e. `Log.Information("The value is {0}", 1 + 1)` is acceptable and names the field as `"0"`

Also consider that these conventions are also honored by NLog and MS.Extensions.Logging.

So my guess is that the field would be named `"1+1"`, and some search engines would cope well with it whereas others would not, but it is missing the point - nobody would want a message field to be named something other than a meaningful string - it's entire purpose is to be a _name_ used to identify a field for humans and/or humans generating search queries for alerts or dashboards etc.

I have read the article you linked, but the more relevant article in this case is to read the motivation and flow in serilog.net to understand why the name of the field being stable is pretty fundamental to structured logging, and no amount of syntactic sugar for the 90% case can outweigh losing trust in the thing being straightforward, consistent and reliable.

**Comment by nblumhardt** [comment]
Thanks for all the follow-ups!

@kulakovt -

> >  Will analyzing property names lead to perf problems?
>
> This is entirely the work of the compiler. After compilation, all property names will be just a string constants in the assembly. There is no penalty for runtime.

The interpolated string needs to be converted into a message template in order to work with Serilog (and much of the ecosystem). It's not possible to construct a valid message template that has a property named `1 + 1`, so your example of `"The value is {1 + 1}"` would be rejected by Serilog today.

Message templates need to have a fixed syntax that can be parsed by other tools - if the property names could be any C# expression, then the message template grammar would end up being a superset of C#, much like the interpolated strings themselves.

To avoid this, Serilog would need to scan through the text of the expression being passed through, to determine whether it could be used directly in a message template, or would need some kind of escaping or replacement. This is where the perf issues might start to creep in - we'd need some kind of caching to avoid having to do this every time an event is logged. Definitely need some further investigation of this.

> > Will constructing message templates with string builders on-the-fly lead to performance problems?
>
> By the way, this method uses a new overload
> StringBuilder.Append(ref System.Text.StringBuilder.AppendInterpolatedStringHandler handler)
> This overload also uses the new string interpolation mechanism.

When you write a log event like `Log.Information("Hello, {Name}", name)` today, Serilog gets the template `"Hello, {Name}"` as a fully-formed string, that the C# compiler embeds into your program binary. It passes this string down the pipeline as the message template text.

Interpolated string handlers don't see the whole message template in one go; they'd need to build it up from the parts that are incrementally seen by the `Append*()` methods. This could be beneficial in some ways - Serilog has to do the opposite, and pull the template apart into its components by parsing - but we'd again need some caching mechanism to avoid a whole lot of allocation on every logging call.

All fun stuff to explore and figure out!

I do sympathize strongly with @bartelink's point of view regarding the quality of events; structured logs are much more useful when property names are consistent and well-thought-out. But, this still requires knowledge and effort using Serilog today, so perhaps if we dig deeper and see just how good the interpolated string-based approach could be made, we might come up with some net-wins? Worth some thought, anyway :-) ...

(I'm wondering whether we can use some of C#'s other caller member attributes and/or source generators to drive the caching and property naming requirements... 🤔.)

**Comment by fedarovich** [comment]
I agree that name consistency is very important for structured logging. On the other hand I've seen so many times how interpolated strings were used instead of structured logging, so I think the suggested approach can be quite useful.

At the moment [my proof of concept](https://github.com/fedarovich/interpolated-logging-demo) does not handle expressions or even method calls. One of my ideas is to use additional `format` parameter in `AppendFormatted`. In this case we can specify the custom name like format (e.g. `LogInformation("{1 + 1:SomeName}"`). I guess it can work quite well together with a custom Roslyn analyzer, but I'm not sure whether it would be easy to create good and efficient analyzer for this use case.

**Comment by nblumhardt** [comment]
Thanks for dropping by, @fedarovich!

The main problem with `LogInformation("{1 + 1:SomeName}")` is that it's already quite common to use formatting with log messages, e.g. `LogInformation("{1 + 1:x8}")`. It'd be surprising if this printed a decimal number, and captured a property called `x8`.

Format strings are tricky because they're completely free-form and don't have any escape mechanism, but it'd be possible to work around this to some extent by figuring out an _almost format string_ grammar that adds capturing hints (`$`, `@`) and names, while being esoteric enough that it'd be unlikely to collide with realistic format strings in the wild (and would need some way to disambiguate, also).

Imagining we adopted `|` as the end-of-format-start-of-capturing-info character, we might then end up with `LogInformation("{1 + 1:|SomeName}")` and `LogInformation("{1 + 1:x8|SomeName}")`, for example, while a format string with a `|` in it might need doubling `||` to circumvent this mechanism. Support for `@` and `$` would be along the lines of `LogInformation("{1 + 1:@SomeName}")`.

Or something like that :-)

**Comment by nblumhardt** [comment]
(Fixed a typo in the last comment after posting, in case you read the initial version via email...)

**Comment by kulakovt** [comment]
I totaly agree with important role of property names. My heart bleeds when I imagine that we can approve camelCase rule for property name instead of PascalCase (if the string interpolation approach wins). But I believe that this is not the topic of this issue. Because in the current version of Serilog this is valid code (this will work):

`logger.Information("Hello {1+1}", 1 + 1);`

We have no way to prevent a user from doing this. They can always write the wrong names. It doesn't depend on string interpolation or the "classic" approach. That's why it's a topic for another discussion.

Now [MessageTemplateParser ignores](https://github.com/serilog/serilog/blob/dev/src/Serilog/Parsing/MessageTemplateParser.cs#L216) this invalid property name. This behavior can also be applied to property names from interpolated strings. Although I would prefer a compilation error.

> I'm wondering whether we can use some of C#'s other caller member attributes and/or source generators to drive the caching and property naming requirements...

Shure, we can solve a lot of issues with source generators. It can:

- stop the build if message have invalid property name or number of parameters
- parse message template during build time and cache it
- enrich message with static information (message id, project name, line number)
- check `LogEventLevel` before real work
- avoid some kind of reflection
- etc

Another great article from Andrew Lock:

- [Improving logging performance with source generators](https://andrewlock.net/exploring-dotnet-6-part-8-improving-logging-performance-with-source-generators/)

But this topic for another discussion :)

> LogInformation("{1 + 1:|@ SomeName}")

Looks too complicated. Maybe people don't need such sophisticated cases? I suppose, in this situation we can recommend them to extract the expression into separate variable (with a nice name). It will be useful for Serilog and code readability too. Otherwise, the current behavior will be applied (don't treat this part as a property name).

**Comment by nblumhardt** [comment]
Thanks for the reply!

> Because in the current version of Serilog this is valid code (this will work):

It's not valid Serilog usage:

![image](https://user-images.githubusercontent.com/342712/147165950-4f085897-3cde-4c19-b052-53dbb87b9eaa.png)

But the interpolated version that looks similar definitely is valid use of an interpolated string, so it'd be strange to do something other than capture the property somehow, in the interpolation case.

> We have no way to prevent a user from doing this. 

We reject it via the message template parser you've linked - any API can be misused, but we don't want to let invalid data propagate through the logging pipeline.

> we can solve a lot of issues with source generators

We'd need to solve the specific problem of unnecessary work at the call site; Serilog rejected the idea of log events as annotated functions on static classes early on (SLAB pioneered this), I think we'd need to figure out how to keep close to the current API.

> Maybe people don't need such sophisticated cases?

Worth considering --- Serilog is very much about sweating the small stuff, and achieving a predictable and consistent user experience, though. To meet that bar, ideally,

 - all uses of interpolated strings in logger calls would need to capture property values predictably (even if we fell back to indexers rather than names in these cases),
 - interpolated strings would need to behave pretty much identically to how they would with e.g. `Console.WriteLine()`, and
 - there should be some reasonably non-disruptive way to opt into core Serilog features like capturing with `@` or `$`, and assigning names to values.

Failing that, we might create more of a mess by having to give advice like: "use interpolation in these situations; use message templates in these others".

What do you think the chances are of being able to build an out-of-band package that tries out some ideas, by offering extension methods that sit alongside the Serilog API? Seems like it would be a nicer way to experiment with different ideas/patterns, before adopting anything in the core project.

**Comment by skomis-mm** [comment]
@nblumhardt out-of-band package would be good option and for the abstractions like MEL. Unfortunately, overload resolution prefer signature with string interpolation handler only if method defined on target type which makes the feature less usefull.

**Comment by bronumski** [comment]
I would argue that the implementation should be done as an extension to the Microsoft ILogger interface as opposed to a single implementation.  I have an example here which also supports the use of functions to safely resolve parameters. Also to get around the `$"{1 + 1}"` issue you can leverage the "format" field and use that to name the parameter. In fact you could argue that it would be better to force the explicit naming of the parameter via the format placeholder because the suggested structured logging convention is to use PascalCase as opposed to CamelCase. In most situations the value you want to pass in is going to be a camel cased local variable.

https://gist.github.com/bronumski/8ffbd37b9446794be4acc5a9a810c776

**Comment by fedarovich** [comment]
@bronumski I published a project named [ISLE](https://github.com/fedarovich/isle) (aka Interpolated String Logging Extensions) couple of weeks ago. It provides the same extension methods for `Microsoft.Extension.Logging.ILogger` as I proposed in [my article](https://habr.com/ru/post/591171/) but they are done in more efficient way as they build FormattedLogValues directly instead of creating a template string and passing it to the parser. It supports formats and alignments, and it also provides an extension method `Named` that can be used to give an arbitrary name to any argument if the user wants to, for example: `"${(1 + 1).Named("Calculated")"`.

It also provides several useful configuration options. In particular, it allows to set a function that performs argument name transformation, e.g. convert it from camel case to pascal case.

As for now, it is released only for Microsoft.Extensions.Logging, but I'm also working on a package that will provide similar extension methods directly for Serilog. Though as @skomis-mm mentioned, overload resolution won't select the extension method, so I have to stick to some alternative method named like LogInterpolated for it.

**Comment by bronumski** [comment]
@fedarovich - That is really cool. Had you considered hijacking the "format" field instead of using the `.Named` extension? Also in my implementation I have specific overloads on the string interpolator to handle a `Func<T>` . This safely resolves the delegate but only if the log level is enabled. It allows you to do things like:

```csharp
logger.LogInformation($"And also this {() => ExpensiveMethodCall(TimeSpan.FromSeconds(1)):Expensive}");

logger.LogInformation($"And not worry about {UnsafeMethodCall:Unsafe}");
```

**Comment by nblumhardt** [comment]
Thanks for sharing ISLE, @fedarovich! I don't think anything's moving forward here in core Serilog just now, but I'm still watching this space keenly.

Closing the ticket as stale, but further comments/suggestions/feedback here is welcome.

**Comment by espenrl** [comment]
@nblumhardt  One could consider to NOT create a message with parameters and rather just output a single string to Serilog. And with StringInterpolatedHandler it can be done in a highly performant way. And **it will work exactly as before**, and way more performant in case the logger is disabled (which is quite likely for trace/debug).

For most of my projects I stay away from parameter bases log messages and the log messages is written with interpolated strings. This is of course not mordern idiomatic logging, but far from all programs requires this kind of setup. I would guess most programs are not backed by a modern log processing system like Prometheus.
