### ISSUE TITLE
Force Destructuring when No Operator Is Supplied

### ISSUE THREAD

**Issue by troysteinbauer** [serilog/serilog#1649]
**Is your feature request related to a problem? Please describe.**

We have an external library which logs (though some adapters) to `Serilog` an instance of a class (`WebRequest : WebRequestBase`) which has a very large `.ToString()` output. I would love to be able to define a policy for that class which structures and reduces the quantity of the output.

However, it looks like [according to documentation](https://github.com/serilog/serilog/wiki/Structured-Data)
 > When Serilog doesn't recognise the type, and no operator is specified (see below) then the object will be rendered using `ToString()`.

**Describe the solution you'd like**

Need the ability to specify a policy which can be applied when no operator is present. Maybe this could be achieved by specifying types which when no operator is present, set to `Destructuring.Destructure` instead of `Destructuring.Default`.

```c#
new LoggerConfiguration()
    .Destructure.WhenNoOperator<WebRequestBase>()
    .Destructure.ByTransforming<WebRequestBase>(x => new {Url = x.Url, Method = x.Method})
    ...
```

I think the logic around this lives in [`PropertyValueConverter.CreatePropertyValue()`](https://github.com/serilog/serilog/blob/17043b56ce97becdbfd2a503ffc16fc77f52285c/src/Serilog/Capturing/PropertyValueConverter.cs#L131-L181), and I see there are interfaces to this class. Another potential solution be the ability to pass in custom implementations of `ILogEventPropertyFactory` and `ILogEventPropertyValueFactory` during `CreateLogger()` to allow overriding default behavior. Currently looks like there is no way to pass in a custom implementations since concrete `MessageTemplateProcessor` and (inside that) `PropertyValueConverter` are used.

**Describe alternatives you've considered**

I am unable to change `WebRequest.ToString()` implementation to reduce output, and I am unable to modify the logging from the external library to include destructuring operator markup to allow normal `Destructure` policies to operate.

**Additional context**

**Comment by nblumhardt** [comment]
Thanks for the heads-up, Troy. Unfortunately it's a bit of an edge case, and so not likely to make it into Serilog at this point, but you should have some options to intercept the event:
 * In your logging adapter (examine the types of event parameters and replace web requests with something else), or
 * By writing an `ILogEventEnricher` that checks events for the property in question, and replaces them.

Hope this helps,
Nick

**Comment by troysteinbauer** [comment]
I started down the route of making an `ILogEventEnricher` which scans for values of specific types to replace with a destructured version, but looking at `LogEvent.Properties`, the values are of type `LogEventPropertyValue`/`ScalarValue` holding the raw `ToString` format. This means I cannot identify by type and swap at that time.

The logging adapter is not as nice of a point of entry for this fix, but I think should work. Going down that route next. Still think the ability to force destructure when no operator is supplied would be a nice improvement.

**Comment by Falco20019** [comment]
@nblumhardt:
We have the same issue. We need to ensure that our generated data does not leak information. We were able to achieve this through the destructure policy since scalar conversion does not allow for `StructureValue` to be output. Any other transformation is also always only executed if the variable was marked for destruction.

I already tried the `ILogEventEnricher` route without success because of the findings that Troy also had (only `ScalarValue` available). I would also love to be able to define be able to define what `Destructuring.Default` means for specific types. This would have been very easily resolvable in `PropertyValueConverter`. The only idea I would be able to come up is inheriting from `PropertyValueConverter` and force that version to be used by the pipleine.

What did you mean by "adapter"? I would like to have a look but don't know where to start. We need this to happen on all sinks.
