### ISSUE TITLE
Leak from CachingMessageTemplateParser?

### ISSUE THREAD

**Issue by kjkrum** [serilog/serilog#1663]
I'm troubleshooting a slow memory leak in a .NET Core 3.1 Worker Service project. Object count steadily increases, and at the top of every heap diff sorted by count diff are `Serilog.Events.MessageTemplate` and `Serilog.Parsing.TextToken`. Their object graphs lead to the static variable `Serilog.Extensions.Logging.SerilogLogger.MessageTemplateParser`, which is an instance of `Serilog.Extensions.Logging.CachingMessageTemplateParser`.

My config:

```json
  "Serilog": {
    "Using": [ "Serilog.Sinks.Console" ],
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Warning",
        "Microsoft.EntityFrameworkCore.Database.Command": "Warning"
      }
    },
    "WriteTo": [
      {
        "Name": "Console"
      }
    ]
  }
```

Using Serilog.AspNetCore 5.0.0 and Serilog.Sinks.Console 4.0.1.

**Comment by kjkrum** [comment]
Looks like it _eventually_ frees those references, after some time longer than half an hour and shorter than four hours. Is there a way to clear the cache?

**Comment by skomis-mm** [comment]
Hi @kjkrum ,
This is usually happens when you pass dynamic strings for the message template parameter. 
Instead, use placeholders for dynamic parameters, so the message templates will be static and won't grow unexpectedly:
https://github.com/serilog/serilog/wiki/Writing-Log-Events#message-template-recommendations

**Comment by kjkrum** [comment]
@skomis-mm I'm already following that practice.

When searching for this issue, I found [this comment](https://github.com/serilog/serilog/issues/1579#issuecomment-843611736) on another issue:

>Serilog wasn't designed around a static instance - short-lived and throwaway loggers are fully supported.

That is not true if the MessageTemplateParser is static and can't be cleared.

**Comment by kjkrum** [comment]
There are only eight unique logging statements in my entire application, but there are thousands of cached templates.

```C#
Log.LogInformation($"Paused. [{delay}]");
Log.LogInformation("Checking new listings.");
Log.LogInformation($"Getting item {itemId}.");
Log.LogInformation($"Saved item {item.ItemId}. [{behind}]");
Log.LogInformation("Updating closed listings.");
Log.LogInformation($"Updated item {item.ItemId}. [{behind}]");
Log.LogWarning(e.ToString());
Log.LogWarning(response.StatusCode.ToString());
```

**Comment by skomis-mm** [comment]
@kjkrum , the interpolated strings expand to raw unique strings:
```csharp
// Log.LogInformation($"Getting item {itemId}.");
Log.LogInformation("Getting item 7194803f-6d47-4bf3-a594-093747eff5aa."); 
Log.LogInformation("Getting item 32d2241a-6247-4ed7-94ac-dccc6431b1d0.");
// and so on
```
and each one is cached by `Serilog` as distinct message template. 

Besides memory issues you observe it also won't get benefit from structured logging point of view: item ids are not captured as properties so structured-aware sinks won't take advantage from it. Instead log statements should look like:
```csharp
Log.LogInformation("Getting item {itemId}.", itemId);
```

**Comment by kjkrum** [comment]
Just realized that and facepalmed. Thanks.

**Comment by kjkrum** [comment]
On further reflection, I think this should be reopened but possibly changed from a bug to an enhancement request. Even though loggers are intended to be used with templates, and the number of templates may be small, a leak is a leak. A static cache does not fit with the stated design intention of supporting throwaway loggers.

I'd also argue that caching anything by default violates the principle of least surprise. Logging raw strings should not result in templates being cached. The solution could be as simple as not creating and caching a template if there are no params, or automatically using a template that gives the raw strings a name, equivalent to `LogInformation("{raw}", str);`.

**Comment by nblumhardt** [comment]
@kjkrum the cache size is limited to 1000 templates; do you have an object count of significantly > 1000 for class `MessageTemplate`?

https://github.com/serilog/serilog/blob/dev/src/Serilog/Core/Pipeline/MessageTemplateCache.cs#L69

**Comment by RyanYANG52** [comment]
In Microsoft.Extensions.Logging, there are also a 1024 cache for `LogValuesFormatter`, but they cache the formatter only if `(values != null && values.Length != 0 && format != null)` [link](https://source.dot.net/#Microsoft.Extensions.Logging.Abstractions/FormattedLogValues.cs)

I think convert template without property directly to text token make some sense, performance wise, and when person not careful. vs ide also has a analysis rule warn user if template is not a static expression [CA2254](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2254)

**Comment by nblumhardt** [comment]
Thanks for the additional input. Just looping back to add some more explanation:

>  The solution could be as simple as not creating and caching a template if there are no params, or automatically using a template that gives the raw strings a name, equivalent to `LogInformation("{raw}", str);`.

Serilog's APIs don't accept raw strings - whatever is passed to `Information()` etc. is a message template, even if it doesn't have any params.

E.g. consider:

```csharp
Log.Information("I know about templates and use {{ to log a literal left brace");
    - > I know about templates and use { to log a literal left brace
```

Hopefully this illustrates why these kinds of changes wouldn't be valid.

SerilogAnalyzer can detect and flag the logging of raw strings at development time - highly recommended if you're in a large codebase that suffers some problems here.

>  a leak is a leak. A static cache does not fit with the stated design intention of supporting throwaway loggers.

The cache is per root `Logger`, not static, just in case you meant literally `static` here.

Even at 1 kB per unique template, if the logging API is misused, we're probably talking about something close to 1 MB, which is unlikely to show up as a performance issue. If the API is used correctly (i.e. with message templates and not strings), the cache might be closer to a few kB for many apps.

If you're seeing more templates in memory than the cache limit implies, it's also possible that your process simply hasn't GC'd yet (.NET will often defer GC for a long time, when memory pressure is low), so that's another avenue to explore. Do let me know if you track this down to any kind of unintended leak, of course! :-)

I'll close this now as I think Serilog's behavior strikes a good balance across many different, and sometimes demanding, usage scenarios. It's always up for reconsideration, but we'd need a really well-researched, complete, high-performance alternative before there's any chance of making changes in this area.
