### ISSUE TITLE
Cannot log double curly brackets

### ISSUE THREAD

**Issue by iojOMlyzI06b8nWnWfxI1BW** [serilog/serilog#1666]
Log.Information("}}");

It only write 1 curly bracket to the log file.
Please check!

**Comment by nblumhardt** [comment]
This is because the argument to `Information()` is a message template, not a raw string; see https://messagetemplates.org for syntax. Thanks!

**Comment by iojOMlyzI06b8nWnWfxI1BW** [comment]
Why did you close the issue like that?
You know what cause the problem and you just close it instead of trying to fix it?
OK good for you
Im out

**Comment by bartelink** [comment]
If you follow the link Nick provided in his post and read it, you'll see that the first argument is expected to fit the rules of a message template. What you passed is not a well-formed message template. When you use a structured serializing logger library, you want the structure it gives you - of you wanted to dump random unstructured stuff to the console, you'd use `Console.WriteLine`.

Kicking the cat by responding as you did does not move anything forward - Nick, and many other people who write and maintain excellent libraries like Serilog carve time out of very busy lives for zero benefit other than the knowledge that they are helping the world - I would prefer that his time goes into considering deep questions in Serilog rather than to/froing with trolling posts like this. So please don't go putting stones in their shoes. If you feel this is wrong and it should be fixed, I suggest getting that opinion validated by asking on stackoverflow if anyone has good workarounds as the issues template suggests first. (If you look around this issues list, you'll find me being slightly argumentative here and there like this when it's warranted, but you will absolutely not find any of the ill-will of aggressive putdown and closing you are ascribing to Nick's posts anywhere - it's simply a guy trying to make the best use of his time in shepherding an extremely busy and successful OSS project)

FWIW If you do want to emit random text verbatim to the log, the minimal way to do that is to do `Log.Information("{0}", <text>)`, where `text` van be `}}` or anything else you wish (if you put `{0}` it will emit literally that.

**Comment by nblumhardt** [comment]
OP, just to add, "closed" doesn't mean "unwelcome" - it just means that this ticket isn't a bug. Because the issue tracker is very busy, we can't always respond in detail. There's also a lot of easily-fund discussion on this exact behavior if you google "serilog curly braces" so I hoped with the info posted in my reply you'd be able to find what you need. Please don't take it personally :-)

**Comment by iojOMlyzI06b8nWnWfxI1BW** [comment]
Log.Information("{0}", <text>) is what I need
Next time please dont close the issue without give the solution
Thank you

**Comment by bartelink** [comment]
"Next time" Please take the time to read the above stuff and take in the points. Going around with that entitled an attitude is not a good look - it's a big world out there and people with the competence and desire to write software of this quality without bugs and without any payment have the same amount of hours in their day as you do. If you actually follow the advice and links you will learn the point of structured logging, which is the real value here.

The other point that's been lost here is that the only way that this (low number of maintainers working on GitHub, millions of package downloads from hundreds of thousands of devs, questions and problems being solved) is to follow the advice of the issue template: questions need to go on stackoverflow.

The alternative is that we all go around thoughtlessly logging issues, kicking cats, and then offering the sort of thanks that your message conveys - we are not on twitter.

**Comment by iojOMlyzI06b8nWnWfxI1BW** [comment]
Well, you can just drop the Log.Information("{0}", text) and close this issue in 5 seconds but you chose the hard way.
You are wasting your time in this issue.
Please stop comment in this issue. Save your precious time.
