### ISSUE TITLE
How to customize file names when writing logs

### ISSUE THREAD

**Issue by xiaogewujiu** [serilog/serilog#1685]
There is a requirement to write to different log files for different services. According to the existing configuration, different files can only be written at a higher level. It is hoped that the file name to be written can be set when writing logs.

**Comment by nblumhardt** [comment]
Hi @xiaogewujiu 👋  thanks for dropping by. Unfortunately this tracker is only for bug reports and feature requests in the core Serilog project; in order to keep the maintenance workload reasonable we're unable to help with usage and related questions here. If you post your question to Stack Overflow and tag it with `serilog` it's likely you'll get and answer there. Thank you!
