### ISSUE TITLE
Serilog.Sinks.OpenTelemetri

### ISSUE THREAD

**Issue by hpaikrao** [serilog/serilog#1754]
**Description**
The main thing I want to implement is, I have to post logs into LocalStack awsclouwatch.
As we have post logs into the LocalStack awscloudwatch service using serilog the same need to implement using opentelemetry.

Since I can't find much on above statement, I thought to use serilog extension to post logs into the OpenTelemtry and use the existing flow of using serilog to see those OpenTelemetry logs in LocalStack awscloudewatch. 

For that I Used **Serilog.OpenTelemetry" Version="2.1.0"** nuget package but I am facing issues with
-  an extention method OpenTelemetry. 
-  Sdk.CreateLoggerProviderBuilder()
- not getting a reference of a class OpenTelemetrySerilogSink 
Since, above issues are with this nuget, just would like to ask,

Do Serilog provide any extension functionality compatible with OpenTelemetry so that I can able to push logs into the OT?

 Please suggest any solution around the same.

Below is the url which I have referred for above serilog-sink-opentelemetry implementation using OpenTelemetry extension method
https://github.com/open-telemetry/opentelemetry-dotnet.git

Refere Proj: OpenTelemetry-DotnNet - example -> LoggingExtensions -> Program.
                   OpenTelemetry.Extensions.Serilog

**Reproduction**
Code samples showing how you're configuring and calling Serilog to produce the behavior.

```
var openTelemetryLoggerProvider = Sdk.CreateLoggerProviderBuilder()
    .SetIncludeFormattedMessage(true)
    .ConfigureResource(builder => builder.AddService("Examples.LoggingExtensions"))
    .AddConsoleExporter()
    .Build();

// Configure Serilog global logger
Log.Logger = new LoggerConfiguration()
    .WriteTo.OpenTelemetry(
        openTelemetryLoggerProvider, // <- Register OpenTelemetry Serilog sink writing to openTelemetryLoggerProvider
        disposeProvider: false) 
.WriteTo.AmazonCloudWatch(cloudWatchConfig)
                    .WriteTo.Console()                    
                    .CreateLogger();
```

**Expected behavior**
Expected behaviour is, serilog will post logs into OpenTelemetry and using our existing flow, those logs would be added into LocalStack awscloudwatch.

**Relevant package, tooling and runtime versions**
Serilog.OpenTelemetry" Version="2.1.0"

**Additional context**
Please suggest any solution here.

Thanks...
Happy Coding....

**Comment by hpaikrao** [comment]
Thank you Nicholas for updates.
Any idea, when it would be possible?

**Comment by nblumhardt** [comment]
I think this depends on when someone's able to investigate/produce an initial version. The core Serilog project isn't driving this - new sinks are generally developed in the community.

Closing so that there's no confusion, but if you do find a solution out there already it'd be great to hear how you go 👍

**Comment by hpaikrao** [comment]
Sure... Thanks...

**Comment by julealgon** [comment]
> The core Serilog project isn't driving this

@nblumhardt would you mind elaborating why? OTEL is going to become _the_ standard moving forward. I think you (and the rest of the team) should reconsider your position on this one otherwise a lot of people will either end up with poor workaround solutions, or outright moving away from Serilog.

Also, wouldn't it be better to keep one of these open with an `up-for-grabs` label to indicate your intent a bit better?

**Comment by nblumhardt** [comment]
Hi Juliano! Thanks for the note.

It's all really going to come down to someone actually needing/wanting an OTEL sink enough to do the research and build one, right now. In the past, every relevant log destination (hundreds of them) has ended up with Serilog support that way. OTEL isn't any different - if someone wants it I think they'll build it whether there's an open issue or not :-)

The challenge is that like all standards, OTEL for logging is something of a lowest-common-denominator. For example, given that a Serilog sink already exists for Elasticsearch that understands all the intricacies of Elasticsearch clusters, indexes, etc., it's not likely anyone would choose a generic sink instead. The situation with other services is similar - I think this might only really change when new/exclusively OTEL logging destinations start to appear.

Are you planning to use a server/service for which OTEL would be the best transport, or where no useful Serilog sink currently exists? Or even just super interested in exploring OTEL? If so, that would be a golden opportunity to help shape something up. If you can stand up a GitHub repo and start hacking away on it, I'd be keen to help you identify useful prior art and unblock any issues that you hit. Let me know if so!

**Comment by julealgon** [comment]
> It's all really going to come down to someone actually needing/wanting an OTEL sink enough to do the research and build one, right now.
> 
> In the past, every relevant log destination (hundreds of them) has ended up with Serilog support that way. OTEL isn't any different

Fair enough. 

I still think this is a mistake on your end though. Once .NET7 launches in a few weeks, I think there will be a sharp incline in demand for OpenTelemetry logging, since the spec will most likely be finalized by them or right after. Other parts of the OTEL spec like metrics and traces are very advanced right now and the expectation is that logs will follow very soon. IIRC while "logging" as a whole has not been finalized yet, the json structure of the data has.

Ideally, I'd actually expect the Serilog team itself to have its own implementation in alpha or beta versions that are closely following the new developments in the actual OTEL logging spec, which is what all OTEL libraries are doing. For ex:
- https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs

Then you'd be in a position to very quickly flip into production-ready versions when the spec is actually finalized.

>  - if someone wants it I think they'll build it whether there's an open issue or not :-)

I think this oversimplifies the problem. Most developers are incapable of building their own sink, in most cases due to time constraints in their projects and/or the fact they cannot contribute to open source projects due to some company policy. These devs will either find workarounds, or they will implement the sink inside their company projects and not share with others.

As for keeping one issue open, I just think it makes the point across in a clearer way that "it is valid, and will be done eventually". As I mentioned, you can also advertise the fact that you want external contributions to create it. Of course, that's my personal reasoning... it's up to you on if you agree or not.

> The challenge is that like all standards, OTEL for logging is something of a lowest-common-denominator. For example, given that a Serilog sink already exists for Elasticsearch that understands all the intricacies of Elasticsearch clusters, indexes, etc., it's not likely anyone would choose a generic sink instead. The situation with other services is similar - I think this might only really change when new/exclusively OTEL logging destinations start to appear.

I can only speak for myself here, but I think you are very wrong on this one. There are huge benefits to using a OTEL sink compared to something like Elasticsearch: it keeps your entire codebase vendor-agnostic, while drastically simplifying the setup.

In conjunction with an external collector like the OpenTelemetry Collector Contrib project, you can then centralize your vendor-specific exports in a single place, even if the target monitoring application doesn't currently support the OTEL protocol natively. This collector can also scale independently as needed.

This is actually the current setup we are experimenting with: every application exports telemetry data using OTEL protocol, and we host a collector instance per environment that redirects everything to Datadog.

> Are you planning to use a server/service for which OTEL would be the best transport, or where no useful Serilog sink currently exists? Or even just super interested in exploring OTEL? If so, that would be a golden opportunity to help shape something up. 
If you can stand up a GitHub repo and start hacking away on it, I'd be keen to help you identify useful prior art and unblock any issues that you hit. Let me know if so!

As mentioned above, we are already fully embracing log exports using OTEL. For these projects, we are currently using the native basic `ILogger` implementation. Right now, the lack of a native OTEL sink would prevent us from using Serilog unless we relied on [the ILoggerSink indirection](https://www.nuget.org/packages/Serilog.Sinks.ILogger/). I would probably not be able to justify working on a brand new sink myself since that workaround would probably work.

I still want to explore using Serilog though even if just for the enrichment API.

**Comment by nblumhardt** [comment]
Hi @julealgon - thanks for taking all the time to reply thoughtfully - much appreciated!

I've had a bit more of a think and a dig around, it could be that our two positions so far in this thread are at the extremes, and there's an optimal viewpoint somewhere in the middle. In any case it seems like incubating something here is worthwhile; are you keen enough to follow along/test/provide feedback?

**Comment by nblumhardt** [comment]
https://github.com/serilog/serilog-sinks-opentelemetry - we can chip away here as time allows; I should be able to get a basic package build going later this week :-)
