### ISSUE TITLE
.NET 7 compatibility

### ISSUE THREAD

**Issue by sdudnic** [serilog/serilog#1767]
I try to upgrade a project containing Serilog to .net 7 using the (MS) [dotnet/upgrade-assistant](https://github.com/dotnet/upgrade-assistant)

The .NET upgrade assistant proposes me : 

>  i. Transitive reference analyzer
>         1. [Next step] Remove package 'Serilog.Settings.Configuration'
>         2. Remove package 'Serilog.Sinks.Console'
>         3. Remove package 'Serilog.Sinks.File'

Should I uninstall them?
Is Serilog to day compatible with .NET 7? (stable 7.0 version is issued several days ago by MS)

If not, please upgrade to support.

**Comment by bartelink** [comment]
There isnt bandwidth for the development team of the Serilog project to answer questions like this as github issues given the sheer number of systems planetwide that use Serilog. 

I'd recommend
a) trying it
b) if you run into problems, log a question, with full details on stack overflow; anyone that monitors this repo's issues and ever responsd also monitors the `serilog` t ag on SO

That said, given the question above, I'd advise:
1. Serilog supports all .NET versions; .NET has excellent backaward compatibility to stuff built for earlier versions
2. There's nothing about Serilog or .NET 7 that should change the packages that you'd need to use - I would not recommend reomving the suggested dependencies (Serilog.Settings.Configuration can define required sinks in the config file, so the File and Console sink packages wil continue to be needed)

If you need ANY follow-ups, please post on SO with a link to/from here (and don't forget to close this issue)

**Comment by bartelink** [comment]
I am extremely confident it's upward compatible - there would be hundreds of issues from people that have things not working if there was a problem. Are you aware how common usage of Serilog is? https://www.nuget.org/packages

The Microsoft upgrade assistant is just a tool - it's likely to be missing the context that the config file implies a required assembly.

Now, please do me the courtesy of re-reading my post; the key bits I want to re-emphasize is
a) This repo is for confirmed issues with repros. I don't want to get into a chat here and there are better ways to figure this out than burdening this repo with questions. 
b) there are better places to discuss this. I suggested Stackoverflow. Your upgrade-assistant issue is probably even a better fit - I believe that tool should provide more context in its messages such that lots of packages don't get swamped with questions/concerns of this kind

**Comment by SimonCropp** [comment]
@sdudnic i am using serilog on net7. works fine.

@bartelink suggest we close this one

**Comment by SimonCropp** [comment]
> Fine is fine. However, still unclear why the the MS upgrade tool recommends uninstalling the only Serilog of the entire project. You have no time to analyze, is fine, cause is not a blocking problem. However, would be better if we would understand the problem, not just saying that there is no problem.

@sdudnic agreed. and you should talk to the MS team that owns that tool.

**Comment by nblumhardt** [comment]
@sdudnic I think it's possible you're misunderstanding what that analyzer does/is telling you. Transitive references are dependencies-of-dependencies. The analyzer result is telling you that because packages your project depends on already have references to those Serilog packages, you can trim those out of your CSPROJ and everything will still work.

> would be better if we would understand the problem

I think the first step there would be for you to do what the analyzer is suggesting, and see whether Serilog logging in your project still works :-)

**Comment by skomis-mm** [comment]
> 1. [Next step] Remove package 'Serilog.Settings.Configuration'
> 2. Remove package 'Serilog.Sinks.Console'
> 3. Remove package 'Serilog.Sinks.File'

@sdudnic  It seems this is about `Serilog.AspNetCore` package which has transitive references. You probably don't directly use aforementioned packages in the code so can safely ignore the warning.

**Comment by skomis-mm** [comment]
> how can it work, if removed? or that is a joke :)

@sdudnic , are you doing upgrade from .NET Framework that has `packages.config` files? 

If yes, then @nblumhardt's suggestion is right. `packages.config` has flat list of dependencies. 
After the upgrade you will have `csproj` with `PackageReference`s that contains root dependency like `Serilog.AspNetCore` and transitive ones `Serilog.Sinks.File` etc. 

Analyzer says you can safely remove them since new style of `csproj` supports transitive dependencies that `Serilog.AspNetCore`  has.
