### ISSUE TITLE
What min netframework should serilog 3 support?

### ISSUE THREAD

**Issue by SimonCropp** [serilog/serilog#1820]

**Comment by SimonCropp** [comment]
my vote is net 48. Since all earlier net framework versions are trivial to update to net48.

**Comment by Numpsy** [comment]
Would you keep the ```netstandard2.0``` target, which then might be used by FW 4.7.2 as well?

**Comment by augustoproiete** [comment]
+1 for `net48` which comes pre-installed with Windows Server 2022

**Comment by nblumhardt** [comment]
`netstandard2.0` supports 4.6.2 and up, and with some caveats, does work on 4.6.1. From 4.7.2 it's pretty smooth, as @Numpsy mentions.

For the sinks, I would guess there are still a lot of cases where direct .NET Framework support will be needed, but for the core Serilog, do we gain anything much by targeting 4.x directly anymore?

What would be the major downsides of targeting `netstandard2.0` as a minimum?

**Comment by SimonCropp** [comment]
IMO the only reason we need to keep  kept netstandard2.0  is so we have support for UWP. It is a pain to build a specific target for UWP

given this https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0

> The versions listed here represent the rules that NuGet uses to determine whether a given .NET Standard library is applicable. While NuGet considers .NET Framework 4.6.1 as supporting .NET Standard 1.5 through 2.0, there are several issues with consuming .NET Standard libraries that were built for those versions from .NET Framework 4.6.1 projects. For .NET Framework projects that need to use such libraries, we recommend that you upgrade the project to target .NET Framework 4.7.2 or higher.

i would suggest either we keep an explicit target for net461. or add code to the netstandard2.0  target to throw for under net472 (for example). i would prob suggest also throwing for older netcore versions

it is why i phrased the discussion "What min netframework". i think we need to pick what the min fw we want to be able to provide support for. and we can work out what the best way to do that is.

**Comment by SimonCropp** [comment]
we should also consider the lifetime of serilog 3. given the 6 years serilog v2 lasted, any supported fws for serilog 3 could need to be supported for a similar amount of time.

**Comment by CaringDev** [comment]
`netstandard2.0`, includes all still-supported full framework versions, UWP, old-ish and new crossplat options. I'd consider not bothering about 4.6.1 (neither add extra support nor throw), as it's out of support for ~9 months already.

**Comment by skomis-mm** [comment]
Leaving only `.netstandard2.0` will introduce new dependencies with assembly redirects for TFMs < net472.

As long as `.netstandard2.0` is here, I don't see much reason to drop the .NET Framework TFMs (at least TFMs >= net472) in terms of support vs current `.netstandard2.0` support.

**Comment by SimonCropp** [comment]
i think no matter the outcome of this, we wont be supporting net46. so i made this pr https://github.com/serilog/serilog/pull/1827 that moves net46 to net461 and simplified the tuple code

**Comment by nblumhardt** [comment]
I think this one still deserves a bit of thought and discussion; perhaps we should give it a week or two to bake, since it's not going to hold up too much right now?

Just floating another idea:

What about if we were able to maintain and publish from a supported `release/v2` branch (forked from `main`) for the foreseeable future, and leave the older targets there?

Many if not most sinks are going to keep targeting Serilog v2 for a very long time. Sinks and client code targeting what we see as v3 right now will be using largely the same APIs as exposed by v2, and so they'll also very likely continue to work with v2.

This makes it very likely that projects on .NET Framework pre-4.7.2 that choose to pin their Serilog version to v2 will not be locked out of the ecosystem and still be able to consume updated sinks. These projects also aren't likely to be moving fast at this stage.

At some future point, when we decided to EOL a hypothetical `release/v2` branch, .NET 4.7.2 and 4.8 projects would _still_ be fully supported via the `netstandard2.0` target in v3.

I'm actually not deeply concerned about continuing to support even `net45` right now, but as Simon alluded to earlier, if we're maintaining v3 for 5+ years without dropping any targets, things could start to get awkward and painful before we're done, so the opportunity to set up an off-ramp here is hard to turn down...

The messaging/docs would be critical if we went this route, though.

**Comment by SimonCropp** [comment]
@nblumhardt 

> I think this one still deserves a bit of thought and discussion; perhaps we should give it a week or two to bake, since it's not going to hold up too much right now?

Happy to take the time.

Also just to be clear, I will advocate strongly for what i think is the best way forward. But ultimately it is your decision, and no bad feelings if we dont go the way u would prefer

> What about if we were able to maintain and publish from a supported release/v2 branch (forked from main) for the foreseeable future, and leave the older targets there?
> Many if not most sinks are going to keep targeting Serilog v2 for a very long time. Sinks and client code targeting what we see as v3 right now will be using largely the same APIs as exposed by v2, and so they'll also mostly continue to work with v2.

I dont know if this is true. I know i have been making changes under the assumption that all consumers would be updated to v3

> I'm actually not deeply concerned about continuing to support even net45 right now

I would prefer "if u r using an unsupported .net (eg 45) then continue to use serilog2". I know i would not want to be helping people with net45 probelms when i dont have it installed on any of my machines, and we dont run tests against it

**Comment by sungam3r** [comment]
> I know i have been making changes under the assumption that all consumers would be updated to v3
> I would prefer "if u r using an unsupported .net (eg 45) then continue to use serilog2". I know i would not want to be helping people with net45 probelms when i dont have it installed on any of my machines, and we dont run tests against it

So do I.

**Comment by glen-84** [comment]
[Support for .NET Framework 4.5.2, 4.6, and 4.6.1 ended on April 26, 2022](https://learn.microsoft.com/en-GB/lifecycle/faq/dotnet-framework)

I don't think that libraries should support EOL framework versions.

It could also have an impact on https://github.com/serilog/serilog-settings-configuration/pull/351.

**Comment by cremor** [comment]
I would go with the suggestions from Microsoft's [Open-source library guidance](https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting) and [.NET Standard overview](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0#when-to-target-net50-or-net60-vs-netstandard).

I think this would mean:

Support
- `netstandard2.0`
- `net461`
  Because of the problems `net461` apps have when they use a `netstandard2.0` package.
  (Targeting `net462` instead of `net461` will not prevent `net461` apps from using Serilog. They will just use the `netstandard2.0` assembly and have more problems.)
- `netX.0`
  Only if there is code in Serilog that requires it.

Remove
- `netstandard1.X`
- `netstandard2.1`
  ([We recommend you skip .NET Standard 2.1 and go straight to .NET 6.](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0#when-to-target-net50-or-net60-vs-netstandard))
- All `net4X` except for `net461`
- `netX.0`
  If there is no code in Serilog that requires it.

**Comment by Numpsy** [comment]
> * All `net4X` except for `net461`

Reposting my comment from https://github.com/serilog/serilog/pull/1849#issuecomment-1499184388 here...

The current Serilog 3 preview nuget packages depend on the System.ValueTuple nuget package in both .NET 4.6.2 and .NET 4.7.1 targets, and I wonder if it needs to for .NET 4.7.x? (I was asking because I recently had to fight a situation at work where Mend decided that System.ValueTuple was a route into an ancient version of System.Text.RegularExpressions in a .NET 7 consumer -couldn't find any evidence there actually was, but not having these dependencies when they're not needed helps with that sort of thing)

**Comment by nblumhardt** [comment]
Looping back to this, it's good having more input, thanks all 👍 

I've dug into what Microsoft's own packages are targeting, looked at the EoL dates for the various .NET SKUs, and what the reach of the various targets is. Here's where I've landed:

 * `netstandard2.0` and `netstandard2.1`
 * `net462`
 * `net5.0`, `net6.0`, and `net7.0`

`netstandard2.0` is an obvious one. ✔️ 

`netstandard2.1` does still provide [reach to Mono, Xamarin, and provides good compatibility with the .NET Core 3.x versions](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0#net-standard-not-deprecated) while avoiding the need for us to give them any more direct support.

`net462` is the earliest .NET SKU (except 3.5) that's still receiving security patches. While some people might be targeting earlier releases still now, it's highly likely that these will all but disappear in the next year or two, and in cases where they don't, either `netstandard2.0` or Serilog 2 are good options. Microsoft themselves assert that 4.6.2 covers 98%+ of .NET consumers.

`net5.0`, `net6.0`, and `net7.0` are all easy to support, in wide use, and by targeting them directly we avoid all possibility of worrying about compatibility quirks now or in the future. Adding `net8.0`, 9, 10, etc. to this list is reasonable in the near future, and if we decide to thin out the list of target SKUs in a future Serilog version, we can fairly easily drop some, in a compatible way).

What do you think? 👍 or 👎 ?

**Comment by SimonCropp** [comment]
@nblumhardt happy with all that. want me to PR it?

**Comment by nblumhardt** [comment]
Queuing one up sounds great @SimonCropp - think we should give the other maintainers a day or two to circle back around and :+1: it but I'm guessing it's reasonably well-aligned with everyone's positions from above (@skomis-mm ?).

**Comment by glen-84** [comment]
net5.0 is EOL. I [still think](https://github.com/VerifyTests/Verify/issues/784#issuecomment-1460683975) that supporting this is a bad idea.

**Comment by SimonCropp** [comment]
@nblumhardt dont we still want net471. since we get ITUPLE

```
  <PropertyGroup Condition=" '$(TargetFramework)' == 'net462' ">
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net462' ">
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
  </ItemGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'net471' ">
    <DefineConstants>$(DefineConstants);FEATURE_ITUPLE</DefineConstants>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net471' ">
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
  </ItemGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.1' ">
    <DefineConstants>$(DefineConstants);FEATURE_DEFAULT_INTERFACE;FEATURE_SPAN;FEATURE_ITUPLE;FEATURE_ASYNCDISPOSABLE;FEATURE_DICTIONARYTRYADD</DefineConstants>
  </PropertyGroup>
  ```

**Comment by skomis-mm** [comment]
@nblumhardt I am ok overall and I agree with @Numpsy and @SimonCropp and would also add:
-  `net47` (without `System.ValueTuple` dependency)
-  `net471` (to have `FEATURE_ITUPLE`)

Should be easy support as `net462` and less upgrade issues.

**Comment by nblumhardt** [comment]
Sounds good to me - thanks @Numpsy, @SimonCropp, @skomis-mm 👍 

Simon, is it okay with you to update your open PR along these lines?

I hope that at some point in the very near future, we'll be able to call 3.0 an RC, and ship it while these decisions are all still fresh and relevant :-) ... I know I've dragged my heels on getting many of our pre-release packages into RTM versions lately; I've resolved to turn that around and try to get everything out the door and into peoples' hands as soon as it's possible.

**Comment by cremor** [comment]
A few points:

A) If you want to target `netstandard2.0` (which of course you want 😃) but don't want to support EOL frameworks like `net461` or `net5.0` then you should document that somewhere. See also [Please stop lying about .NET Standard 2.0 support! ](https://andrewlock.net/stop-lying-about-netstandard-2-support/)

B)
> `netstandard2.1` does still provide [reach to Mono, Xamarin, and provides good compatibility with the .NET Core 3.x versions](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0#net-standard-not-deprecated) while avoiding the need for us to give them any more direct support.

Will Serilog actually offer anything in the `netstandard2.1` assembly that the `netstandard2.0` assembly doesn't offer? If not, why target it? Mono and Xamarin will also use the `netstandard2.0` assembly.

C)
> `net5.0`, `net6.0`, and `net7.0` are all easy to support, in wide use, and by targeting them directly we avoid all possibility of worrying about compatibility quirks now or in the future.

Which compatibility quirks?
Also, the same question as B.

**Comment by nblumhardt** [comment]
Thanks for the feedback, @cremor.

> A) If you want to target netstandard2.0 (which of course you want 😃) but don't want to support EOL frameworks like net461 or net5.0 then you should document that somewhere. See also Please stop lying about .NET Standard 2.0 support! 

We do at this point want to support .NET 5. For 4.6.1, anyone still targeting it will have learned to avoid `netstandard2.0` by now, I hope :-). If we run into any compat issues or confusion we can make a stronger statement at that time, though 👍 

> Will Serilog actually offer anything in the netstandard2.1 assembly that the netstandard2.0 assembly doesn't offer? If not, why target it? Mono and Xamarin will also use the netstandard2.0 assembly.

```
<PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' " />
<PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.1' ">
  <DefineConstants>$(DefineConstants);FEATURE_DEFAULT_INTERFACE;FEATURE_SPAN;FEATURE_ITUPLE;FEATURE_ASYNCDISPOSABLE;FEATURE_DICTIONARYTRYADD</DefineConstants>
</PropertyGroup>
```

> Which compatibility quirks?
> Also, the same question as B.

Language version compatibility differs across these, targeting the least of them means polyfills for some compiler dependencies --- etc., etc., really. This ain't our first rodeo :-).
