### ISSUE TITLE
why are only _logEventSinks disposed?

### ISSUE THREAD

**Issue by SimonCropp** [serilog/serilog#183]
So here https://github.com/serilog/serilog/blob/master/src/Serilog/LoggerConfiguration.cs#L106 we have 

```
    public ILogger CreateLogger()
    {
        Action dispose = () =>
        {
            foreach (var disposable in _logEventSinks.OfType<IDisposable>())
                disposable.Dispose();
        };

        var sink = new SafeAggregateSink(_logEventSinks);

        if (_filters.Any())
            sink = new SafeAggregateSink(new[] { new FilteringSink(sink, _filters) });

        var converter = new PropertyValueConverter(_additionalScalarTypes, _additionalDestructuringPolicies);
        var processor = new MessageTemplateProcessor(converter);

        return new Logger(processor, _minimumLevel, sink, _enrichers, dispose);
    }
```

But `IDestructuringPolicy`s, `ILogEventEnricher`s and `ILogEventFilter`s could all implement `IDisposable`. So why are they not clean up? Should any of them be disposed in the same way as `ILogEventSink`s?

**Comment by DanAvni** [comment]
@nblumhardt, I found an example scenario: I need to recycle the running IIS pool when OutOfMemory exception is thrown (My site sometimes got to a place that in the eyes of IIS the application pool is healty but for .NET it is only able to run a few pages and the rest throw OutOfMemory exception). The problem is that IIS does not know how to do that and I do not want to crash the process. 
So my solution is to write a LogEventFilter that looks to see if an OutOfMemory exception is being logged as the exception of the event. If it is logged I need to restart the IIS pool. But because the user running the IIS site is not an administrative user, the filter is not allowed to launch the commands needed to recycle the IIS pool. Instead, I am setting a global EventWaitHandle and there is another process looking at that handle to see when it is set to know it needs to recycle. It took some tweaking, but this is the general idea. The EventWaitHandle in the filter needs to be disposed when the IIS process terminates. Currently I disposed of it in the finalizer which is the best I could do but obviously if ILogEventFilter would support Dispose that would be better

**Comment by nblumhardt** [comment]
Thanks for the insight, @DanAvni 👍 

In this situation, instead of a filter, could you write your hook as a sink? It wouldn't have to actually write logs anywhere - could just inspect them - but it should receive all the same info that a filter does.

You can then hook into sink disposal to do what you need.
