### ISSUE TITLE
Access CorrelationId programmatically.

### ISSUE THREAD

**Issue by vejandla** [serilog/serilog#1909]
I am implementing on a hosted service in .net core 3.1 which will be triggered from a function app.

My logger have an correlationid enricher, i wanted to programmatically access the correlation id created before the hosted service get triggered and pass it to my hosted service quque. 

How can I programmatically access the correlationid enricher in the webapi controller?

**Comment by augustoproiete** [comment]
@vejandla This is the repo for the core Serilog library - which has no knowledge of correlation id, nor hosted services.

The best way to get answers on usage of Serilog is to post a question on [stackoverflow.com](https://stackoverflow.com/questions/tagged/serilog) including the `serilog` tag and details of the code you are using and some context the kind of app you are building

https://stackoverflow.com/questions/tagged/serilog

**Comment by vejandla** [comment]
@augustoproiete the question is more or less related to how to access a enricher value outside the context of logger? (i gave an example of CorrelationId, doesn't have to be the same)

It could be environment enricher
ThreadId or anything?

**Comment by bartelink** [comment]
The point here is that this is there is a better forum for raising questions that align a bit with serilog - stack overflow. This repo is for the core Serilog repo - have a look [a the download count](https://www.nuget.org/packages/serilog) and ask yourself is maintainer time best spent on answering questions here.

The other answer is that you can simply read the code, which will reveal (I'm guessing to a degree)
- it's just Execution Context, Async Local and friends propagating values
- it's not exposed, because it's an internal implementation detail of the enrichers; exposing these things would lead to a lot of mess in diverse codebases around the world.

Best step now is to close this question and formulate a new SO question along the lines of "I am doing this with Serilog in my xyz app which is using these frameworks. I want to do <thing> but <this thing I am doing> has <problem>. Is there any good way to solve this?"

Seriously - there's a very low number of watchers on this repo. Any of them that will answer also watch the `serilog` tag on SO.

**Comment by nblumhardt** [comment]
`Activity.Current.TraceId` and `Activity.Current.SpanId` provides those values; `Thread.CurrentThread.ManagedThreadId` provides the threading one, etc. - I think this is something best left out of the Serilog's realm of responsibility, since the correlation id likely doesn't exist solely for Serilog's purposes anyway - Serilog is just another consumer.

Closing as not planned, but thanks for raising this all the same.
