### ISSUE TITLE
AddJsonFile not reload on net6.0/7.0

### ISSUE THREAD

**Issue by andmattia** [serilog/serilog#1925]
**Description**
I clone the repo https://github.com/serilog/serilog-settings-configuration/tree/dev

**Reproduction**
Execute the sample app and change 
```json
"MinimumLevel": {
      "Default": "Verbose",
      "Override": {
```
but no reload happen

**Expected behavior**

move from debug to verbose logging

**Relevant package, tooling and runtime versions**

**Additional context**

**Comment by nblumhardt** [comment]
Hi! Thanks for getting in touch; apologies for the slow delay - this repo is only monitored by a small team. The best way forward with this would be to post the whole code sample to Stack Overflow, where a few more knowledgeable folks will be able to check it out.

The sample you're running doesn't contain any verbose-level log statements so I don't think this is the full picture - you'll need to show how you're generating the verbose-level events.

(A PR or failing test case over in serilog-settings-configuration would be another good option if you've had a chance to investigate more since raising this.)

Thanks again!
