### ISSUE TITLE
Do not cache templates with no values

### ISSUE THREAD

**Issue by raymondpwilson** [serilog/serilog#1941]
We have a modern, large, .Net C# codebase and use Serilog for our logging infrastructure.

Our use case for Serilog is almost always in the form of 'raw' logging, where the template part of the Log.*() calls do not have any values (ie: the logged string is fully constructed in the context of the Log.*() statement.)

Serilog's template caching behaviour does not provide any benefit in this use case as almost every log statement will present a novel 
template to Serilog. This means all cache management activities in Serilog within our system are overhead for no benefit, both from memory and processor perspectives.

I would like Serilog to have the behaviour (by default, or by configuration) where templates with no arguments are not cached as doing so provides no benefit.

We appreciate Serilog provides very powerful logging capabilities that we don't fully utilise (though we may do so in the future), however the size of our codebase makes it impractical to re-engineer the totality of our logging infrastructure to switch to template + value logging, not to mention the additional bugs that would be inevitably added.

**Comment by nblumhardt** [comment]
Hi Raymond, thanks for dropping us a line!

There are a few subtleties and consistency issues around this that make it unappealing to implement in Serilog itself; there are a couple of options you might consider instead (in addition to just ignoring the existence of the cache).

Is your code using Serilog directly, or is it using a legacy logging API that's adapted onto Serilog?

If it's the former, using Serilog directly, then your best bet is to use SerilogAnalyzer to spot literal strings in log statements, and incrementally fix the code. Serilog has always had the API it does now - arguments to `Log` are message templates, and if this is ignored, Serilog can produce unexpected output.

E.g.

```csharp
var name= "{{Raymond}}";
Log.Information($"Hello, {name}");
// {{ and }} are escape sequences, so they're collapsed:
// [19:05:38 INF] Hello, {Raymond}
```

Besides, fixing the code will be the most enjoyable, productive, and beneficial option in the long run. Structured logging with full message templates is just a wonderful place to be! 🌞

Otherwise, if you _are_ using Serilog but can't allocate time to fix the code, creating a wrapper around Serilog's `ILogger` and implementing your own message template caching in there would give you pretty good bang for the buck. If you set `Log.Logger` to your own wrapper around Serilog you can reuse Serilog's template parsing and caching however you wish, and then forward events on to a wrapped `Logger` via its (explicit) implementation of `ILogEventSink.Emit()`.

If you're _not_ using Serilog directly, then your best option is to change your adapter to treat `log.Information("X")` as if it's `log.Information("{Message}", "X")` - or to do something with `MessageTemplateParser` and `ILogEventSink.Emit()` as suggested above, before forwarding to Serilog.

Hope this helps!
Nick

**Comment by raymondpwilson** [comment]
Hi Nick,

Thanks for the rapid and detailed reply!

For grins, I searched one portion of our solution for log statements. There are about 5,000 of them in that portion!

We do already have the Serilog analyser that is hilighting the logging with a complaints that the template should not change between invocations. It makes sense why now I understand more about the templating.

Suffice it to say, changing all the code is probably not going to happen, at least in the short/medium term, if ever.

We use Serilog directly (injecting it's implementation against the ILogger asbtractions) so we may likely need to take your wrapper suggestion. Some thought required.

I'm not objecting to the API, or that it's been that way a long time, or that it needs to change. Just that a 'template' with no values seems to be, well, just a string (unless templates are cleverer than I thought and can do useful things even without fields).

Food for thought here for sure.

Raymond.

**Comment by bartelink** [comment]
Some low level techniques that were useful for me in migrating from NLog https://stackoverflow.com/a/49639001/11635
i.e. to get the most efficient short-circuiting of the caching, the `TextToken` piece may be useful

In general, I'd suggest to keep it simple though; as Nick says, the main thing you want to make sure is that you're not putting variable input into the `template` argument, with the risk of it containing tokens that are meaningful as template fields (via doing `log.Information("{message}", formattedMessage)`)

**Comment by raymondpwilson** [comment]
@bartelink : Thanks for the pointers. I will look into them.

@nblumhardt : I see you have closed this ticket. I am curious though: Are there use cases for templates with no fields that mean treatment of the template as a dumb string in this case is invalid?

**Comment by raymondpwilson** [comment]
Something I did not mention is the volume of logging we do, which is in the range of 1-2Tb/week.

**Comment by bartelink** [comment]
I'd say try the `TextToken` mechanism, which will subvert the normal parse and cache mechanism (and also not parse embedded tokens).

You'll find that the general perf of Serilog is excellent, as all the key paths have been well optimized. While 2TB pw is not low, it's far from out of the ordinary for Serilog systems in the wild - the level of ubiquity can be extrapolated from the nuget download counts pretty easily.

In general, the concept is that the escape hatches outside of the normal usage might not be completely obvious, but they exist; all you need to do is some minor wrapping, without every special case getting its own top level method. This policy has stood Serilog well over time. I'd suggest in this instance that you give this approach a try as ultimately any 'log without parsing' scheme is going to be this in a dress anyway, given that all messages travel to the Sinks as `LogEvent` in any case.

**Comment by raymondpwilson** [comment]
Looking into our code a bit.. .We use the Mircrosoft.Extensions.Logging abstractions and inject the LoggerFactory from that namespace and use the Serilog SerilogLoggerFactoryExtensions.AddSerilog() to inject Serilog into the logging pipeline.

I am not sure how to intercede with Serilog here to provide wrapped Log*() methods.
