### ISSUE TITLE
Custom expression template is not working 

### ISSUE THREAD

**Issue by AsuraKev** [serilog/serilog#1974]
Hi there,
I am using the serilog Azure sink and using the compact json formatter and have configure an output template like below:
![image](https://github.com/serilog/serilog/assets/52765572/d68806d9-19aa-409f-9356-726302875416)

however when i visit the actual log its logging output like this:
![image](https://github.com/serilog/serilog/assets/52765572/0816808e-0508-4f51-bbf2-d39eccdfdc7e)

any ideas?

thanks

**Comment by nblumhardt** [comment]
Hi! Expression templates need to be configured using `ExpressionTemplate`, they don't work at all with `CompactJsonFormatter`. This post has some examples: https://nblumhardt.com/2021/06/customize-serilog-json-output/

If you need a hand getting expression templates working with the Azure Blob Storage sink via JSON, posting your config (as code rather than a screenshot) to a new Stack Overflow post tagged with `serilog` will get the right eyes on it. This repository is for the core Serilog library, only monitored by its maintainers, and isn't the right one for this question.

Hope this helps,
Nick
