### ISSUE TITLE
Consider adding a first-class Google Cloud Logging compatible JSON stdout formatter to Serilog

### ISSUE THREAD

**Issue by lol768** [serilog/serilog#1986]
**Is your feature request related to a problem? Please describe.**

Serilog currently has no first-class support for formatting JSON logs in a way which Google Cloud Logging understands, as far as I can tell.

It can encode to a compact JSON representation, but it seems to be using a format which [Serilog has made up](https://clef-json.org/). Do any cloud providers support ingesting logs in this format?

**Describe the solution you'd like**

Serilog to adopt e.g. the `Redbox.Serilog.Stackdriver Nuget` package, bring it back up to compat with Serilog v3 (i.e. by merging something like https://github.com/redboxllc/stackdriver-serilog/pull/15) and ship it as a maintained first-class citizen.

**Comment by nblumhardt** [comment]
Hi Adam, thanks for dropping by!

https://github.com/redboxllc/stackdriver-serilog/blob/master/src/Redbox.Serilog.Stackdriver/StackdriverJsonFormatter.cs is only a handful of LoC - your quickest and easiest option would be to grab that file, plus the log level mapping function, and drop it into your app.

Because there are hundreds of JSON log formats in common use out there, Serilog can't build and maintain first-class support for them all. Aside from community projects like the one mentioned above, we do however ship `ExpressionTemplate` to enable generating pretty much any reasonable JSON format out of the box.

Stackdriver logs using `ExpressionTemplate` would look something like:

```csharp
// dotnet add package Serilog.Expressions
using Serilog.Expressions.Templates;

Log.Logger = new LoggerConfiguration()
    .WriteTo.Console(new ExpressionTemplate(
        "{ {timestamp: @t, message: @m, fingerprint: ToString(@i, 'x8'), severity: ToString(@l, 'u'), exception: @x, ..@p} }"
    ))
    .CreateLogger();
```

Not sure how picky StackDriver is about levels, you can make a more precise mapping using `if @l = 'Verbose' then 'DEBUG' else ...` etc.

HTH,
Nick

**Comment by lol768** [comment]
Cheers, that gives me a starting point.

As the problem with the Redbox package was simply binary compat. (removal of optional second param for TypeToken constructor) - you're right, you can just copy/paste the class into the project and it'll work. I had a chat with the previous maintainers of the Redbox package (who left Redbox a while ago) and they've suggested a fork on NuGet might be nice to simplify things for other people who run into this problem. So I'm tempted to go down that route. The PR I opened updates it all for .NET 8 and the latest way Microsoft has come up with configuring an ASP.NET app.

The ExpressionTemplate example you've given me is interesting. I did look briefly at Serilog.Expressions prior to opening this issue but I'm not sure I appreciated how flexible it actually seems to be. Google Cloud _is_ picky about severities and does need them mapped to things that it understands but it sounds like that'd be possible with a chained `if`.

Hopefully with a bit of luck this issue will be indexed by Google for whomever next wants to deploy to GCP with stdout logging.
