### ISSUE TITLE
Can't unit test when using chained ForContext

### ISSUE THREAD

**Issue by chunty** [serilog/serilog#1991]
I'm using .net core 7 with Serilog 3.1.1

**Description**
Given the following example class:

```csharp
public class MyService
{
  ILogger _logger;  

  public MyService (ILogger log)
  {
    _logger = log
  }


  public void DoStuff()
  {
    _logger
        .ForContext("One", 1)
        .ForContext("Two", 2)
        .Error("Not happy");
  }
}
```

and the following example test:
```csharp
public class MyServiceTest
{
  Mock<ILogger> _loggerMock = new();  
  MyService sut;

  public MyServiceTest(ILogger log)
  {
   _loggerMock.Setup(x => x.Warning(It.IsAny<string>()).Verifiable();
    sut = new MyService(_loggerMock.Object);
  }


  public void DoStuffShouldLogWarning()
  {
     sut.DoStuff();
    _loggerMock.Verify(x => x.Warning(It.IsAny<string>()), times.once);
  }
}
```

I always get that Warning is never called because actually what happens is the first "ForContext" returns a new object.

I need to be able to verify that all the properties were added to the context and that I logged a warning.

**Comment by bartelink** [comment]
This is not a `bug` in Serilog that can be fixed by a rewrite or something; it's just how it works.

Questions like this are best asked on stack overflow, where there are far more people paying attention, and the best solution can be debated/upvoted. If you log it there and tag it `serilog`, the same people that will see this issue will see it there (don't forget to check for duplicates - mocking fluent builders is likely to be something that has been asked before).

**Comment by bartelink** [comment]
[double posted](https://stackoverflow.com/questions/77679318/how-to-unit-test-serilog-calls-when-using-forcontext)
