### ISSUE TITLE
Possibility to reuse log file between multiple instances of RollingFileSink

### ISSUE THREAD

**Issue by object** [serilog/serilog#200]
I am using RollingFileSink configured to produce a file per day. It accumulates messages in a single file as long as I create a single logger instance. But multiple logger instances log to different files. The way the application logs requires creation of an instance per log message (why I am doing this is described in issue #199), so I end up with a file per message which is of course absurd.

I wonder if RollingFileSink could be set up in a smarter way, so if multiple loggers write to the same file from the same appdomain (and perhaps from the same thread) they could reuse the same file. If not, creating workaround for issue #199 becomes hard.

**Comment by gstempeck** [comment]
4 Years later, I need the opposite functionality.  I have multiple instances created that each need their own rolling log because each instance is long-running in the background and needs to log to separate files.  Instead, I am creating new LoggerConfiguration() in those instances and using new "path" in each instance along with rollingInterval: RollingInterval.Day and I'm ending-up with the last instance created aquiring all the logs from prior instances.  Could #199 be causing this behavior?  How do I ensure I have a separate rolling log for each instance without being able to use Filters because its the same class and namespace?

**Comment by nblumhardt** [comment]
Hi @gstempeck - this one might need its own ticket :-)

One quick thing to try - give each log file a unique prefix (don't use overlapping names like `log*`, `log_1*` as you might inadvertently put them in the same logical set.)
