### ISSUE TITLE
Redaction of sensitive information

### ISSUE THREAD

**Issue by Falco20019** [serilog/serilog#2023]
We have the same issue as in https://github.com/serilog/serilog/issues/1649, therefore I'm not posting the full template here again.

We need to ensure that our generated data does not leak information. We can not do anything on `ToString` and also can't attribute it. We were able to achieve this through the destructure policy since scalar conversion does not allow for `StructureValue` to be output. Any other transformation is also always only executed if the variable was marked for destruction. But this means, that we MUST ensure that every developer uses destructuring correctly (which is nearly impossible).

I already tried the `ILogEventEnricher` route without success because of the findings that Troy also had (only `ScalarValue` available). I would also love to be able to define what `Destructuring.Default` means for specific types (i.e. being able to force it to destructure). This would be very easily resolvable in `PropertyValueConverter`. The only idea I would be able to come up is inheriting from `PropertyValueConverter` and force that version to be used by the pipleine.

We need this to happen on all sinks. We currently use the `ILogger` from `LoggerConfiguration.CreateLogger()` and not any adapter. I COULD wrap the DI registered instance to wrap it (basically introducing an adapter), handling parameters before passing, but this seems just like a big overkill and I hope there is a better way using Serilog.

The main issue is still that it's not possible to use any custom `ILogEventPropertyFactory` and/or `ILogEventPropertyValueFactory` implementation since `MessageTemplateProcessor` and `PropertyValueConverter` are internal.

**Comment by nblumhardt** [comment]
Hi @Falco20019; it sounds like your scenario is covered by https://github.com/nblumhardt/serilog-redaction - let me know if this does the trick for you.

**Comment by Falco20019** [comment]
I most probalby won't need the redaction sink, but the existance of `LoggerSinkConfiguration.Wrap` is a great hint that looks promising!

**Comment by Falco20019** [comment]
As already assumped, this approach is sadly not working since the properties are already processed into a `ScalarValue` loosing all information.

## Using default behavior (property is `ScalarValue`)
![image](https://github.com/serilog/serilog/assets/940619/d438e30f-093f-45f8-a042-f56573180b2b)

## Using destructure behavior (property is `StructureValue`)
![image](https://github.com/serilog/serilog/assets/940619/f75f1f74-ac40-4b81-9c5e-b7bb545d4922)

**Comment by Falco20019** [comment]
I created a PR for option 1 to show that it is aligning with the architecture of Serilog quite well and that it only needs minimal changes.

**Comment by nblumhardt** [comment]
Hi! Thanks for the follow-up. For comparison, why would you not:

1. Create an `IDestructuringPolicy` implementation for your target types that ignores the "hidden" properties, and,
2. Use redaction to try to catch any accidentally-logged sensitive data that makes it through?

I don't think you can avoid (2) in any scheme, because sensitive information can leak through in pre-formatted strings, exception messages, and so-on.

Consider this:

```csharp
log.Information($"Here is {channel}");
```

There are many variations on this where your custom scalar conversion policy will be circumvented by someone pre-formatting a string.

Redaction is a necessary safety net, and once it's in place, the existing `IDestructuringPolicy` mechanism does exactly what you need.

Let me know if this helps! Thanks for the PR all the same 👍

**Comment by Falco20019** [comment]
We already did the destructuring policy, but since it‘s not about exactly one type but hundreds of types, redaction is not possible (only knowing that they use attribution to mark sensitive fields and inherit from a common ProtoBuf type).

The PR is only a PoC to convey the idea and I would even need it to work for inherited types and not just one type.

**Comment by Falco20019** [comment]
I added the MCVE as a separate branch based on the PR to show why it's needed and how it would be used:
https://github.com/Falco20019/serilog/commit/6adf142d5f510551b042730ec0b80290e6d30919#diff-86f1ea85f8823db5ebf82a426a402d13d27bd9a688919c8a4565aa915176111c

If you have a better idea on how to solve this issue, I would greatly appreacite to use it instead of needing to change the API.

For context, the `protos/user_credentials.proto` would be specified in another assembly and not be known to the main application. So it's not possible to reference it when defining the logger. The base type `IMessage` is known and would be used for the configuration. The generated logger would be dependency injected into the other assembly containing the generated `UserCredentials` and that would also be the place where the log would happen.

I hope this clarifies a bit my use-case and why redaction is not possible.

**Comment by nblumhardt** [comment]
Thanks @Falco20019.

Although we could implement the kind of thing you're suggesting, it'd still be trivial to bypass:

```csharp
// Any type that implements `ToString()` by calling `ToString()` on its members...
var info = new
{
    // One of the deserialized protos...
    Response = apiResponse,
};

// Logged object is not of a type matched by any of the policies...
Log.Information("Processing of {ResponseInfo} complete", info);

// -> Leaked `ToString()` representation of the proto.
```

The root of the problem seems to be a type carrying sensitive information, which includes that information in its `ToString()` representation. (I know the bulk of the type is generated by an external tool; not sure what options you'll have to modify it..)

The combination of a destructuring policy for correct `@` usage, plus a fix for the `ToString()` issue, would be tighter. (Is there an option to use a custom type for the sensitive fields, instead of plain `string`, so that you can control `ToString()` output?)

**Comment by Falco20019** [comment]
@nblumhardt Any more information/input given my last post if you would consider the PR?

**Comment by nblumhardt** [comment]
Hi! Sorry about the slow turnaround, a bit buried this past week.

I sympathize with where you're stuck, but I think https://github.com/serilog/serilog/issues/2023#issuecomment-1988038143 is accurate - an optimal solution requires some support in the protobuf implementation for C#.

Given the difficulties with obtaining that, I understand why having some partial fallback support in Serilog would be useful, but what you're proposing is still as fragile as just requiring `@` and a custom destructuring policy. If you can miss one usage of `@` in code review, it's just as easy to miss someone using string interpolation or an explicit `.ToString()` somewhere, which both circumvent the protection you're proposing.

Since there's overhead and complexity involved in adding the feature to Serilog, I don't think it's a good bet, sorry.

> There was a discussion about this on https://github.com/protocolbuffers/protobuf/issues/1160 but as you can see, the recommendation is to make sure your logging is taking care of it

From what I can tell that thread ends with [a link to a commit adding `debug_redact` support to the proto language](https://github.com/protocolbuffers/protobuf/issues/1160#issuecomment-1370085012), so perhaps what you need is on its way? Good luck either way!

**Comment by troysteinbauer** [comment]
I believe https://github.com/serilog/serilog/pull/2024 would also solve my issue described in #1649, where I have no control over the object being logged or the log message template itself. In my case, the logging is coming from a third party library which is not 'structure logging aware', and thus doesn't use `@` anywhere in their log statements, but do pass the full object.

**Comment by nblumhardt** [comment]
Thanks again for opening this. Closing as not aligned with the current design, but appreciate all the work you put into this and the related PR - thanks @Falco20019!
