### ISSUE TITLE
Upgrade guide for version 3 or 4?

### ISSUE THREAD

**Issue by dmrickey** [serilog/serilog#2079]
In the wiki I see a guide for upgrading to version 2.0. Are there any equivalent documents for upgrading to v3 or v4?

**Comment by nblumhardt** [comment]
Hi! Thanks for reaching out. The 1 &rarr; 2 upgrade was a bit more involved than any of the later ones, since the API was substantially redesigned.

Upgrading between versions since then is generally just a matter of updating the NUPKG; the major breaking changes have just been TFM changes.

See also:

 * https://github.com/serilog/serilog/releases/tag/v3.0.0
 * https://github.com/serilog/serilog/releases/tag/v3.1.0
 * https://github.com/serilog/serilog/releases/tag/v4.0.0

HTH!
