### ISSUE TITLE
MinimumLevel on a nested logger cannot override the default 

### ISSUE THREAD

**Issue by alrz** [serilog/serilog#2098]
**Description**

MinimumLevel on a nested logger cannot override the default 

**Reproduction**
```cs
       loggerConfig.MinimumLevel.Information();
       loggerConfig.WriteTo.Logger(loggerConfig => loggerConfig
                    .MinimumLevel.Error()
                    .MinimumLevel.Override("Microsoft.Hosting.Lifetime", LogEventLevel.Information)
                    .WriteTo.Console());
```
**Expected behavior**

Errors and anything in Lifetime namespace with information or higher level is logged.

**Actual behavior**

Only errors get logged. Note that the same config for the top-level logger works as expected.

**Comment by nblumhardt** [comment]
Hi @alrz, thanks for reaching out.

This is a known limitation mentioned in the API documentation for `WriteTo.Logger`:

https://github.com/serilog/serilog/blob/dev/src/Serilog/Configuration/LoggerSinkConfiguration.cs#L152

`WriteTo` configures sinks, these are targets generated by the logging pipeline. There's no way for a sink to instruct the outer logger to generate events that it wouldn't otherwise generate - the flow is one-way only.

There's a more detailed thread discussing this in the tracker somewhere I believe. Hope this helps.

**Comment by nblumhardt** [comment]
Sorry, the relevant comment is this one:

https://github.com/serilog/serilog/blob/dev/src/Serilog/Configuration/LoggerMinimumLevelConfiguration.cs#L105

This is a separate limitation of sub-loggers, also a known limitation we've decided to leave as-is for now.
