### ISSUE TITLE
Serilog destructures only public properties of the object.

### ISSUE THREAD

**Issue by konste** [serilog/serilog#228]
It seems to me that public fields of the object should be destructured in the same way as public properties. I had an objects which exposed fields instead of properties and was very much puzzled why I don't see anything about it in the log. Converting all such objects to expose properties is not an option - there are just too many of them.

**Comment by SimonCropp** [comment]
@nblumhardt the FDG are explicitly for frameworks. they are not meant to be applied as-is to business code. 

The idea behind "dont expose public fields" is that when a dif assembly references you, you want to be able to optionally change the member get/set code without needing a breaking change. hence it make sense for frameworks since their very nature means they are all consumed by other assemblies.

but that logic does not hold in most business code. ie if the only thing consuming a member  is inside to the current assembly, then a public field is no diff from a public property, since it is a non breaking change to (at any point) change between them

Given the majority of the consumers of serilog are not frameworks (most dont like to take a dependency on a specific logging lib) would you re-consider support for this?

**Comment by nblumhardt** [comment]
Hey @SimonCropp - it's a fair suggestion :+1: but I think there's now too much water under the bridge to switch the default behavior here. Perhaps a `Destructure.IncludingPublicFields()` extension would be an option? Not sure what the impact would be, but definitely open to considering it/discussing with the rest of the Serilog crew.

**Comment by SimonCropp** [comment]
the reason i ask is a colleague spent a few hours yesterday trying to work out why some members were silently not rendering.

he had

    public List<ItemUpdated> ItemUpdatedMessages = new List<ItemUpdated>();
    public List<ItemUpdating> ItemUpdatingMessages = new List<ItemUpdating>();

instead of 

    public List<ItemUpdated> ItemUpdatedMessages { get; } = new List<ItemUpdated>();
    public List<ItemUpdating> ItemUpdatingMessages { get; } = new List<ItemUpdating>(); 

it is pretty easy for someone to forget the `{ get; }` and then silently those members dont get logged. and in the context of that type (that had 20 other properties) it was pretty easy not to notice the missing members in SEQ until u actually need them in a production scenario. for a while we also mistakenly thought those list were empty when logged, so wen down that rabbit hole.

**Comment by SimonCropp** [comment]
hear is another person with the same issue https://github.com/serilog/serilog/issues/1175#issuecomment-396298382

**Comment by SimonCropp** [comment]
and +1 for an opt in setting

**Comment by SimonCropp** [comment]
would you like a PR for this?

**Comment by nblumhardt** [comment]
@SimonCropp sounds great; there are a couple of alternative ways I could see this working - either a global or a per-type/predicate option; what do you think about enabling both? `Destructure.IncludingPublicFields()` (or a better name) would be global, while `IncludingPublicFields<T>()` and `IncludingPublicFields(t => ...)` (names?) might be the more selective options. The main aim of the selective forms would be to introduce this into existing code where suddenly enabling field serialization everywhere could have unintended consequences for log bloat. Thoughts?

**Comment by SimonCropp** [comment]
@nblumhardt so i have a starting point, can u point me to the line of code where u use reflection to enumerate the properties?

**Comment by nblumhardt** [comment]
Hmm discovered a bit of code rot when checking this; it's in `TryConvertCompilerGeneratedType()` - which, despite the name, converts non-compiler-generated types, too 😆 ... https://github.com/serilog/serilog/blob/dev/src/Serilog/Capturing/PropertyValueConverter.cs#L281 .... better naming suggestions appreciated (`TryConvertStructuredValue()`?)

The closely-related [`GetPropertiesRecursive()`](https://github.com/serilog/serilog/blob/dev/src/Serilog/Capturing/GetablePropertyFinder.cs#L24) is also (no longer?) recursive... naming improvements gratefully accepted there, also!

**Comment by v-zubritsky** [comment]
Hi! Have it ever been implemented anywhere? Have encountered the same issue and don't want to invent a bicycle. Having an extension method would be quite nice

**Comment by nblumhardt** [comment]
@v-zubritsky https://stackoverflow.com/questions/46152092/serilog-serializing-fields HTH!
