### ISSUE TITLE
PeriodicBatchingSink should flush on unhandled exception

### ISSUE THREAD

**Issue by konste** [serilog/serilog#357]
PeriodicBatchingSink class subscribes to two events:
     AppDomain.CurrentDomain.DomainUnload += OnAppDomainUnloading;
     AppDomain.CurrentDomain.ProcessExit += OnAppDomainUnloading;

DomainUnload event is never raised in the default application domain.
ProcessExit event is only raised when the process exits normally, but when the process exits because of unhandled exception (which is the most interesting case from the log perspective) ProcessExit event is NOT raised. UnhandledException event is raised instead.

IMHO it would be very helpful if PeriodicBatchingSink subscribes to all three events.

Thank you!
Konstantin

**Comment by nblumhardt** [comment]
Thanks for the suggestion. It's pretty common to subscribe to `UnhandledException` and set `e.Handled = true` as a "global catch block" in some kinds of apps. This would be incompatible with the way the sink is flushed currently, which is to join with the worker thread (and any synchronous flush in this method could cause trouble for some apps).

I don't think we can take this one on as a bug; it's an interesting improvement that can be made, but needs a bit of design work. Happy to discuss the ins-and-outs if you decide to take a shot at it, but will close this ticket for now.

Thanks!

**Comment by konste** [comment]
I researched it a little further and it seems e.Handled = true you mentioned is something specific for WPF and Silverlight and relevant to Application.DispatchUnhandledException event.

For AppDomain.UnhandledException event there is no way to "catch" it and prevent process from exiting within 2 seconds if IsTerminating event handler parameter is true.

As far as i can tell, AppDomain.UnhandledException is what you get INSTEAD of ProcessExit in case of abnormal termination. You cannot guaranty that the sink would be flushed in this case, but at least it is better to try, than not to try and guaranty losing the most important pre-crash log events.

< sent from mobile device >

On Jan 17, 2015, at 2:33 AM, Nicholas Blumhardt <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the suggestion. It's pretty common to subscribe to UnhandledException and set e.Handled = true as a "global catch block" in some kinds of apps. This would be incompatible with the way the sink is flushed currently, which is to join with the worker thread (and any synchronous flush in this method could cause trouble for some apps).

I don't think we can take this one on as a bug; it's an interesting improvement that can be made, but needs a bit of design work. Happy to discuss the ins-and-outs if you decide to take a shot at it, but will close this ticket for now.

Thanks!

-

**Comment by nblumhardt** [comment]
Thanks for the follow-up. I'll take a look at `e.IsTerminating` to see whether we can use that to determine which scenario we're in.

**Comment by chuwik** [comment]
I looked a bit into this, since I'm facing this problem (can't log unhandled exceptions in console apps because the PeriodicBatchSink isn't subscribed to UnhandledException). Hope this helps:

Application.DispatcherUnhandledException
- Exists only for Silverlight and WPF applications.
- Gets called if there is an unhandled exception in the UI thread.
- Its EventArgs (of type DispatcherUnhandledExceptionEventArgs) has the e.Handled property.
- You can set this e.Handled property to true to prevent the app from crashing, and in this case AppDomain.CurrentDomain.UnhandledException won't be reached. Otherwise it will.

AppDomain.CurrentDomain.UnhandledException
- Gets called whenever an unhandled exception happens in the domain.
- Its EventArgs (of type UnhandledExceptionEventArgs) has the e.IsTerminating property.
- Indeed is what you get instead of ProcessExit in case of abnormal termination.

So, in WPF and Silverlight apps an unmanaged exception in the UI thread will trigger:
1. Application.DispatcherUnhandledException 
2. If e.Handled wasn't set to true in previous step => AppDomain.CurrentDomain.UnhandledException

And outside the UI thread:
1. AppDomain.CurrentDomain.UnhandledException

In other type of applications (at least simple console ones) an unmanaged exception will trigger:
1. AppDomain.CurrentDomain.UnhandledException

So as far as I can tell, I think it'd be fine to hook "CloseAndFlush" to AppDomain.CurrentDomain.UnhandledException, and it'll work for WPF/Silverlight apps as well as long as the dev doesn't manually do e.Handled = true. That would be a scenario we wouldn't be covering; but it isn't covered now either, I believe.

It may be worth hooking up to AppDomain.CurrentDomain.UnhandledException, but maybe also exposing the method to "CloseAndFlush" so that devs can hook it up manually in more specific scenarios (like when they want to do the e.Handled=true stuff, and there may be others in other type of applications we may be missing). 

Hope this makes sense!
Enrique

**Comment by konste** [comment]
Thank you Enrique! That matches my conclusions.

Konstantin

**Comment by nblumhardt** [comment]
Thanks for the research! Should the sink be flushed only when `e.IsTerminating` is true? Thanks!

**Comment by konste** [comment]
Yes.

Quote from MSDN: Beginning with the .NET Framework version 2.0, this property returns true for most unhandled exceptions, unless an application compatibility flag is used to revert to the behavior of versions 1.0 and 1.1. The reason is that most unhandled exceptions in threads, including thread pool threads, are allowed to proceed naturally, which normally results in termination of the application. For more information, including a list of cases in which the runtime does not terminate, see Exceptions in Managed Threads<https://msdn.microsoft.com/en-us/library/ms228965(v=vs.110).aspx>.

Konstantin
