### ISSUE TITLE
Logger for current context

### ISSUE THREAD

**Issue by mookid8000** [serilog/serilog#375]
I don't know if I am using Serilog wrong (or in a non-idiomatic way ;)), but I am doing this a lot:

    static readonly ILogger Log = Serilog.Log.Logger.ForContext(MethodBase.GetCurrentMethod().DeclaringType);

at the top of all classes that need to log stuff. As you can see, I like to use the type as the context.

I would love it if Serilog could get the type as if by magic, so that I could do this:

    static readonly ILogger Log = Serilog.Log.Logger.ForCurrentContext();

and then Serilog would walk the call stack and get the calling type and then return a logger for that context.

1. Would anyone else be interested in that feature?
1. Should I call it something else? Put it somewhere else?

Of course I could easily just do it in a static class somewhere in my own code, but if this way of calling `ForContext` is preferred by people, we might as well encourage that usage with a(n even) niftier API :)

**Comment by mookid8000** [comment]
oh I see now that the fact the Serilog is a PCL makes it difficult (maybe even impossible?) to do this....

**Comment by nblumhardt** [comment]
Howdy! That is indeed niftier - historically I've kept away from these APIs because they introduce a reflection cost that would be paid even with logging turned off. But, I'm sure that is not a big deal for most people.

How do you solve the "stack" problem when it's wrapped up in a method? Capturing the current call stack and walking up is very slow, but the other option (trying to force inlining) will be thwarted by the compiler (IIRC callsites for `GetCurrentMethod()` are special-cased).

In any case, it'd be cool to publish as an _Extra_ to gauge interest (many of our "extra" packages do well, e.g. http://www.nuget.org/packages/serilog.extras.appsettings).

Cheers!

**Comment by nblumhardt** [comment]
Howdy again - closing this since it's not certain we can move forward; would love to see this out there if you end up figuring something out. We're encouraging most of these into independent projects (a-la https://github.com/serilog-metrics/serilog-metrics so we'd be happy to help promote it if you put one together. Cheers!

**Comment by mookid8000** [comment]
fair enough :smiley:
