### ISSUE TITLE
[ElasticsearchSink] Exceptions not logged to Elasticsearch

### ISSUE THREAD

**Issue by tynor88** [serilog/serilog#384]
We are having an issue with logging exceptions with Serilog and the ElasticsearchSink.

Versions used:
Elasticsearch.NET : 1.4.1
Serilog: 1.4.168
Serilog.Sinks.ElasticSearch : 1.4.168
Elasticsearch: 1.3.2

We are using the overload which takes an Exception and it doesn't seem to be logged in ElastichSearch. We are worried that we have missed alot of serious errors in our systems. Here is an example:

Logs fine:
`Log.Error("An error was thrown. Exception {Exception}", e);`

Does NOT log to Elasticsearch:
`Log.Error(e , "An error was thrown.");`
where e is an Exception

We tried enabling the File sink, and there we have no problems. So it seems to be a bug somewhere in the Elasticsearch sink or in Logstash/Elasticsearch.

**Comment by mivano** [comment]
We recently noticed the same behaviour. The cause was pretty hard to find. It is not Serilog as the error will be logged to other sinks but it is persisting this kind of event to ElasticSearch. The ES sinks is doing a bulk post to ES to deliver a set of events and does not act on the return result coming in from ES. That might be an improvement; raising issues to the Serilog selflog so it is more clear.

But the errors are visible in the ES logs in the end. Most likely you will see something about expecting an object but getting an EOL. What is happening is that the ES sink is serialising all the events to JSON. If you are using the ES sink in its default way (so for example using the AppSettings reader), it will use a null for its serialiser. Although that is fine, it will basically use the ToString on every object it tries to serialise. See here https://github.com/serilog/serilog/pull/244 and here https://github.com/serilog/serilog/pull/289 

So this means that an exception will be logged as a string. However, ES itself will expect an object (assuming you have ran the mappings). And that will not fit.

The solution is simple; pass along the serializator like this

```csharp
var serializer = new ElasticsearchJsonNetSerializer();
var log = new LoggerConfiguration()
    .WriteTo.ElasticSearch(period: TimeSpan.FromMilliseconds(5), serializer: serializer)
    .CreateLogger();
```

This will use the ElasticSearch.NET serializer and will generate an object again. However; we found out that this serializer is having some issues. See https://github.com/elasticsearch/elasticsearch-net/issues/1228 and we also noticed even stack overflow exceptions in the simple json library which is used here. So no final solution yet. The sink is however pretty configurable now, but also a bit more complex and unfortunately misses at this moment the ability to alert on issues when saving the data to ES. 

@Mpdreamz did you noticed similar problems? Particularly that stack overflow is giving us a lot of troubles and the fact that the default serializer is now null caused us to miss a lot of errors in the logs too since we create the sink using the appSettings trick.

**Comment by Mpdreamz** [comment]
@mivano seeing as how you are like 20 minutes away from me maybe we can pair on this next week somewhere? Not sure if @zidad who reported https://github.com/elasticsearch/elasticsearch-net/issues/1228 is a colleague but it would be great to have a dedicated moment to tackle this head on and get the sink to a stable condition.

**Comment by tynor88** [comment]
Nice find @mivano, i was trying to debug the ES Sink myself, but i didn't get this far. I wonder how this has worked for us before, without using another serializer?

Let me know if there is anything I can help with or test.

**Comment by zidad** [comment]
@Mpdreamz Yes @mivano's colleague :). Looking forward to looking into this!

**Comment by mivano** [comment]
@Mpdreamz good plan. I will try to make a simple repro scenario first and send it to you for initial look. We are located at Schiphol oost and can meet there. Do you have an email address for me?

**Comment by Mpdreamz** [comment]
@mivano my nickname at gmail, I was a bit optimistic about this week, Wednesday onwards my calendar is full, maybe tomorrow or next week Monday?

**Comment by mivano** [comment]
Closing this one as the implementation as described in #394 would solve this issue.
