### ISSUE TITLE
Support jsonformattter while logging to eventhub

### ISSUE THREAD

**Issue by kanchanm** [serilog/serilog#403]
Will be great if there was an easy way to log messages in json format while logging into eventhub. 

@BenGale @nblumhardt

**Comment by kanchanm** [comment]
@BenGale, do let me know if you have any plans/thoughts here.

**Comment by nblumhardt** [comment]
Creating an overload of `.AzureEventHub()` that accepts an `ITextFormatter` instead of `outputTemplate` and `formatProvider` seems like it would make life easier (currently the configuration method just creates a `MessageTemplateTextFormatter` by default: https://github.com/serilog/serilog-sinks-azureeventhub/blob/master/src/Serilog.Sinks.AzureEventHub/LoggerConfigurationAzureEventHubExtensions.cs#L84)

However, you can actually do this today since the sink class is public:

```csharp
    .WriteTo.Sink(new AzureEventHubSink(eventHubClient, partitionKey, new JsonFormatter())
```

This is the approach the file sinks also take, but discoverability is not great.

**Comment by kanchanm** [comment]
Thanks @nblumhardt 
This should work. Do agree that the overload would make it much discoverable/easier.

**Comment by nblumhardt** [comment]
I'll close this for the time being, but if anyone feels the urge to jump in and figure out the overload that would be great. Thanks all!
