### ISSUE TITLE
Message templates don't support dots in parameters

### ISSUE THREAD

**Issue by dabutvin** [serilog/serilog#404]
```
this.Logger.Information("Started proccessing message at {Message.StartTime}", DateTime.UtcNow);
```

This doesnt work

**Comment by nblumhardt** [comment]
Thanks for the note. This one is by design - you can pass structured data using notation like:

```
Log.Information("Started proccessing message at {@Message}", new { StartTime = DateTime.UtcNow});
```

Dots within property names themselves aren't supported by many target sinks, so we chose the lowest common denominator here. It would be neat to infer structure from the dotted property names, but in practice this turns out to be a bit verbose.

HTH!

**Comment by posledam** [comment]
how sad it is when someone in the library decides for me whether I can use dots in the parameters of message templates or not.

due to some crooked receivers that do not know how to work with a dot, I cannot now normally pass parameters with a dot.

how did it happen?

**Comment by nblumhardt** [comment]
Hi Aleksy, that's not the case at all! From the project page, you can download this rather small project as a zip, or pull its source code. A couple of quick changes and you can set Serilog up to accept dots, etc.

You'll need to add one line to this function:

https://github.com/serilog/serilog/blob/dev/src/Serilog/Parsing/MessageTemplateParser.cs#L207

There's really no other way the project can work; if we accepted every suggestion or added every feature that's requested, Serilog would have become useless spaghetti a long time ago.

Hope this helps,
Nick
