### ISSUE TITLE
Unable to log to Seq instance with version 1.5.5 of Seq Sink

### ISSUE THREAD

**Issue by xclp** [serilog/serilog#416]
Have tested in a basic console app and can log to Console window but logs never make it to Seq. Rolling back to previous, known working version (1.4.8) works fine.

Serilog.Debugging.SelfLog.Out produces the following info:

2015-04-01T15:51:53 Exception while emitting periodic batch from Serilog.Sinks.Seq.SeqSink: System.TypeLoadException: Could not load type 'Serilog.Debugging.LoggingFailedException' from assembly 'Serilog, Version=1.4.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'.
   at Serilog.Sinks.Seq.SeqSink.<EmitBatchAsync>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Serilog.Sinks.Seq.SeqSink.EmitBatchAsync(IEnumerable`1 events)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.EmitBatch(IEnumerable`1 events)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()

**Comment by nblumhardt** [comment]
Ah - thanks Claire. This is the result of a bungled fix to #415 - checking it out now.

**Comment by nblumhardt** [comment]
I've fixed this in the Seq sink, I'll re-test and apply the same change across all of the sink packages when I'm sure it's succeeded.

NuGet 2.8 changed the dependency resolution algorithm to pick the lowest, rather than the highest, patch version that can satisfy a version spec:

http://docs.nuget.org/release-notes/nuget-2.8

We had the Serilog package dependency specified as `[1.4,2)`, but this resulted in a version of Serilog that was too low.

You can install packages like this by specifying `-DependencyVersion Highest` on the package manager command-line:

```powershell
Install-Package Serilog.Sinks.Seq -DependencyVersion Highest
```

...but, the usability of that is terrible. We'll instead use the specific latest version that the sink is built against as its minimum.

**Comment by nblumhardt** [comment]
Fixed. Thanks again!

**Comment by mnbbrown** [comment]
I seem to be having the same issue with Serilog 1.5.11 and Serilog.Sinks.Seq 1.5.17:

----
An exception of type 'System.TypeLoadException' occurred in ModHub.Logging.dll but was not handled in user code

Additional information: Method 'EmitBatch' in type 'Serilog.Sinks.Seq.SeqSink' from assembly 'Serilog.Sinks.Seq, Version=1.5.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' does not have an implementation.

---
```c#
return new LoggerConfiguration()
            .Enrich.WithProperty("osVersion", LogHelper.OSVersion())
           .WriteTo.RollingFile(folder + "\\log-{Date}.log")
           .WriteTo.Seq(settings.SeqURL, apiKey: settings.SeqAPIKey)
           .CreateLogger();
````

Any idea?

**Comment by nblumhardt** [comment]
Hi @mnbrown - thanks for reaching out. I don't hit this with the package versions you've specified, is it possible to try reproducing in a separate console app to verify it's not a build/stale assembly issue? Also, do let us know if you're using (or perhaps somehow referencing) the .NET 4 build of either of these.

**Comment by IanYates** [comment]
I've found this happens when I've got this situation...

Main web site - .NET 4.5
Helper assembly - .NET 4.0 - referenced by main web site  (and some other things which I still need to be .NET 4.0 because life's not fair)
Serliog and friends - referenced by both assemblies

If build didn't quite finish for whatever reason, the wrong Serilog ends up in the main web site's bin folder and this very issue happens.  Rebuilding the main web site solves it.

(This is how I encounter the referencing .NET 4 build, the issue @nblumhardt is describing)

**Comment by mnbbrown** [comment]
Thanks @IanYates and @nblumhardt! seems it was referencing a stale version of the assembly in the shadow copy cache. Delete the cache and rebuilding seems to have fixed the issue. 

More info here for anyone that stumbles across this issue: http://www.xerxesb.com/2008/05/22/shadow-copy-cache-hell/
