### ISSUE TITLE
New repositories owners/issues

### ISSUE THREAD

**Issue by mivano** [serilog/serilog#417]
All the sinks are now in separate repositories per #344 but some of them still have issue tracking enabled (like raygun, exceptionless, logentries). We should either enable them for all (or all having an explicit owner) or use the serilog repo for this.

Next to that, we might run into risks with sinks that do not have an owner. Like the MSSQL one that has a pull request in there for a couple of days already. I m happy to pick up for the ones I created once (like mssql, loggly, loggr, logentries, elmahio and elasticsearch). 

Might be good to list all the sinks and their owners anyway (#411) and see where we miss people?

**Comment by mivano** [comment]
And to add to this; for the work we do now in the Elasticsearch sink it might make sense to start using the issue tracker there to make sure the generic one wont get polluted by ideas, bugs etc for this specific sink. As long as there is an owner to watch that space, it might work.

**Comment by nblumhardt** [comment]
Thanks - I've added teams for the packages you mention above where they were missing, and added you to the owners group for each. I thought I'd pick others up as the opportunities arise, but good to have this ticket to track progress.

I'm happy either way regarding issue tracking. In some sense having a tracker on the more active sinks will keep noise down, but it'll also make it harder to collaborate across sinks (less eyes on each ticket).

Perhaps we try sticking with the current single tracker until the noise becomes a problem?

Cheers!

**Comment by mivano** [comment]
Cool. Just wanted to make sure that we do not miss outstanding pull requests. If you are fine with me accepting them in the sinks, then that would also alleviate some work from you. For issues it is not a big thing if they are in the same repro. I was just mentioning it since we had some ideas in the ES sink that we would pop as issues to keep track off.

**Comment by nblumhardt** [comment]
Seeking co-owners for https://github.com/serilog-web/owin and https://github.com/serilog-web/classic .... Separate org, but same needs for these.

The longer term goal of these projects is to create a consistent Serilog experience over a variety of .NET web app frameworks - e.g. so that request are always logged in (as much as possible) the same way, and enrichment always uses consistent property names etc.

(This will be great for enterprises with mixed app environments who are aggregating logs, and we could just about create the "NCSA log format" equivalent for Serilog-web-logs in the proces :-)

This org/project will also end up being central to getting top-notch Serilog support for ASP.NET 5 out there when it happens.

cc @paulblamire @merbla @jbattermann @damianh who have all (along with @mivano) contributed to these chunks in the past.

**Comment by damianh** [comment]
@nblumhardt Happy to help out with https://github.com/serilog-web/owin. (Is that name the final name?)

**Comment by nblumhardt** [comment]
Fantastic - you should have an admin invite; no, open to other names if you think that'd be a good idea?

**Comment by damianh** [comment]
Cool. 

Yeah... firstly owin, the spec, doesn't have anything defined for logging. This is actually an adapter for the logging in the katana poject (aka Microsoft.Owin). So, am thinking something like `Serilog.MSOwin`.

Anywho, I'll create an issue in the target repository.

**Comment by nblumhardt** [comment]
Ah - now I get the original name - makes sense, will see if I can come up with any other suggestions.

I "translated" it in the move mainly to make it easier to search for/find (e.g. googling "serilog owin")
