### ISSUE TITLE
Publish Debugging Symbols for Serilog.nupkg to SymbolSource.org

### ISSUE THREAD

**Issue by jamesbascle** [serilog/serilog#419]
When debugging code that uses nuget packages, it is very helpful to have symbols available.  To this end, I would ask that when your build server (or whatever process) publishes the Serilog NuGet packages, that it also builds and pushes the symbols packages to SymbolSource.org.

A side benefit of this is that it gets users familiar with the code and more likely to contribute to the project and submit bug fixes.

**Comment by nblumhardt** [comment]
Thanks James! At the moment, the issue stalling us is that automatically-generated symbol packages fail for `Serilog.nuspec` because of the multiple platform support. (All the sink packages have symbol packages published already.)

There's a `Build.ps1` script in the repository from which we'd hope to generate symbol packages; if anyone's able to take this on it should be a "grabbable" task, though I'm hazy on exactly where this failed last time so some investigation (and hair-pulling) is probably required :-)

Cheers!

**Comment by jamesbascle** [comment]
I see, are you saying that SymbolSource.org itself is not accepting the files, or that they are not being generated properly?

**Comment by nblumhardt** [comment]
Here's one of these failures - it's actually the ES sink rather than the core package, but the error IIRC is the same:

https://ci.appveyor.com/project/serilog/serilog/build/75

The problem seems to be that the symbol package needs to contain source files for all of the included PDBs?

I'm not 100% certain this is the issue with Serilog's NUPKG, but given the layout is identical this would make sense.

**Comment by nblumhardt** [comment]
The v2 build is doing this correctly.
