### ISSUE TITLE
ES sink uses connection timeout instead of request timeout

### ISSUE THREAD

**Issue by konste** [serilog/serilog#427]
ElasticsearchSinkOptions has property ConnectionTimeout with the default value 5 seconds. This is reasonable for connection timeout, but in ElasticsearchSinkState.cs it is used in SetTimeout
       new ConnectionConfiguration(options.ConnectionPool).SetTimeout(options.ConnectionTimeout)
which accordingly to [documentation] (http://nest.azurewebsites.net/elasticsearch-net/connecting.html) represents request timeout. Request timeout supposed to be much longer than connection timeout. In .NET default value for it is 100 seconds: see [here](https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.timeout(v=vs.110).aspx) 

I would recommend bumping up the default in ES sink.

Konstantin

**Comment by nblumhardt** [comment]
Well spotted - cc @serilog/owners-elasticsearch

**Comment by mivano** [comment]
Hmmm, yeah interesting one. @Mpdreamz what is your idea about this?

**Comment by mivano** [comment]
We are a bit stuck on this one. What should we do? PR and discuss it there? @Mpdreamz any ideas to add to this?

**Comment by konste** [comment]
We cannot do better than Elasticsearch.Net does and they cannot do better than .NET framework itself does. If real connection timeout is inaccessible, let's just rename our timeout explicitly to RequestTimeout, give it appropriate comment and correct default (i.e. 100 sec, not 5) and be done with it for now.

**Comment by Mpdreamz** [comment]
Elasticsearch.NET allows you to set both a request (Timeout) and `ConnectTimeout` separately. Using the HttpConnection we cannot set this anywhere on `WebRequest` `.Timeout` measures from start of request to end of request but if e.g a DNS lookup takes 30 seconds this is not counted towards the timeout. The thrift connection does take advantage of the separate timeouts.

+1 for obsoleting `ConnectionTimeout` in favour of less ambiguous `RequestTimeout`, not sure we should set to `100` by default though, the client itself defaults to 60 seconds but here we are dealing with a specialized use case, doing bulk inserts and we typically do expect those to complete within 5seconds. Maybe we can up to default to a more conservative `20s` ?

**Comment by konste** [comment]
-- Elasticsearch.NET allows you to set both a request (Timeout) and ConnectTimeout separately.

I don't see that! All they have is a property named "ConnectionTimeout" which is actually used as Request Timeout. And there is no second property. That's what caused the problem for us in the first place. @Mpdreamz do you see differently?

**Comment by Mpdreamz** [comment]
Elasticsearch.Net has [(Request)Timeout](https://github.com/elastic/elasticsearch-net/blob/develop/src/Elasticsearch.Net/Connection/Configuration/ConnectionConfiguration.cs#L282) and [ConnectTimeout](https://github.com/elastic/elasticsearch-net/blob/develop/src/Elasticsearch.Net/Connection/Configuration/ConnectionConfiguration.cs#L302) 

The sink only has [ConnectionTime](https://github.com/serilog/serilog-sinks-elasticsearch/blob/ba4dc887b3a2205d6b01c4a0b0de4bf4934ab0b8/src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkOptions.cs#L83) which I agree is named very ambiguously and taken directly from the old `connectionTimeOutInMilliseconds` parameter on the first version of the sink but was **always** meant to be used as the request timeout so no bug or mistaken identity here :). 

The [old request/connection timeout](https://github.com/serilog/serilog-sinks-elasticsearch/commit/c7683fff54da7f4f1a1fefcf51955cc23e655c64#diff-9511ec46e63272b225868494528dabf2R90) default in the 1.0 version of the sink was also 5 seconds hence the current default. 

I'm +1 on renaming it and upping the default (to 10s or maybe 20s not 100s) but since the assembly is signed this might be a problem if we follow the [json.net strong naming pattern](http://james.newtonking.com/archive/2012/04/04/json-net-strong-naming-and-assembly-version-numbers) in which we need to stay binary compatible to prevent MissingMethodExceptions. @nblumhardt can you confirm if its safe to rename properties in minor releases?

That said im also ok with *not* renaming the property and simply updating the xmldoc and changing the default. Its the least breaking option.

**Comment by nblumhardt** [comment]
@Mpdreamz I think a property rename is both source and binary breaking, so a major version bump would be needed here.

Another option is to leave the property, mark it as `[Obsolete()]` and introduce two new properties (one of which the old property would wrap). HTH!

**Comment by Mpdreamz** [comment]
Doh yeah that's what I initially suggested too :)

Out of curiosity does serilog change assembly version on each build? Or does it stay fixed only updating assembly file version?

**Comment by nblumhardt** [comment]
Historically we've kept a fixed `Major.Minor.0.0`, so assembly version only changes between minor releases. In the future (2.0+) I think changes on the major version only will be the way to go.

**Comment by konste** [comment]
-- Another option is to leave the property, mark it as [Obsolete()] and introduce two new properties (one of which the old property would wrap). 

This looks like the best we can do at his time. We would not break anybody and at the same time give new users both properties with meaningful names. I vote for this solution.

**Comment by nblumhardt** [comment]
Can this issue be closed? Can't recall whether I've seen any progress on this.

**Comment by konste** [comment]
There were no progress, but what's the rush to close it? Seasonal cleaning? Well if it feels like it stuck forever - let's close it.

**Comment by merbla** [comment]
Any interest in opening Issues list on the Elastic Search Repo?
