### ISSUE TITLE
RollingFileSink to roll over on FileSize

### ISSUE THREAD

**Issue by thinktainer** [serilog/serilog#428]
In our application it would be desirable to have the RollingFileSink as a reliable backup mechanism for when network logging fails. We would prefer to have the log file roll over when it reaches the file size limit rather than truncating (e.g.: log-{Date}-001.txt log-{Date}-002.txt). We are aware that this would make the disk usage unbounded, and would prefer to live with this tradeoff.
I have looked at the source code, and am curious if such a behaviour was ever planned when looking at https://github.com/serilog/serilog/blob/dev/src/Serilog.FullNetFx/Sinks/RollingFile/TemplatedPathRoller.cs#L71?
Is this a feature you would be open to consider including as a configurable option?

**Comment by nblumhardt** [comment]
Hi @thinktainer - thanks for getting in touch!

Have you looked at simply passing `null` for the `fileSizeLimitBytes` argument of `WriteTo.RollingFile()`? This will permit unbounded disk usage, but not truncate files at any size.

https://github.com/serilog/serilog/blob/dev/src/Serilog.FullNetFx/LoggerConfigurationFullNetFxExtensions.cs#L179

Roll-on-size is something I'd be interested to look into, but I'm not certain the complexity tradeoff would be a great one right now (unsure how much this would churn). If you end up having a chance to investigate any insights here would be valuable.

**Comment by thinktainer** [comment]
Hey Nicholas, thank you for getting back to me so fast.
We have considered growing the files much larger too, the problem with that is that the tooling for inspecting them at that size is less then ideal for our scenario; most of the times we need to log onto a deployed instance and inspect files there, so we would either need to split them with powershell or similar, or use a buffer based editor like vim.
I'm going to spike an implementation of this our end, and will get back in touch as soon as I have something a bit more tangible.
Another thing I have noticed is that the comment at: https://github.com/serilog/serilog/blob/dev/src/Serilog.FullNetFx/Sinks/RollingFile/RollingFileSink.cs#L49 seems to describe behaviour that I seem to not be able to get to work here (the files never increment the inc part). Can you elaborate what the intended usage for this behaviour is? Would you expect the files to roll over on sink initialisation in case they have grown too big, or depending on another condition?

**Comment by nblumhardt** [comment]
The increment occurs when a log file is locked, allowing a roll-over to a file with a numeric suffix. Useful when e.g. ASP.NET worker pools recycle in an overlapped manner. It'd be interesting to see if this same facility can be triggered by hitting the size limit - though IIRC there's an assumption in other parts of the code that there will never be more than 999 of these. Great starting point!

**Comment by thinktainer** [comment]
The churn as you anticipated looks considerable. From my point of view there are two obvious approaches to establishing if the `LogEvent` fits into the File. One would be tapping into the existing `CharacterCountLimitedTextWriter` and adding an event in case the limit is hit. The other one would be to format the event and then copy the stream, after the length is known. Do you see an alternative I may have missed? Do you favour any of these two solutions?

**Comment by nblumhardt** [comment]
Thanks for the follow-up; I'm not sure about either - perhaps a third, where size is only checked after the write (thus allowing slightly-bigger-than-specified files) might be a good alternative too, since it would avoid pre-formatting the event, but leave `CharacterCountLimitedTextWriter` mostly alone.

I wonder if reassembling the various parts to create `WriteTo.SizeRolledFile()` might not also be a reasonable option? The downside I guess is that eventually, roll-on-date-and-size will also be desirable to someone. As independent sink packages that might not be a problem - many focused sinks will be better to maintain than one ultra-complex one... Thoughts?

**Comment by thinktainer** [comment]
i think by changing the semantics of what max file size / max number of files to keep would allow for hiding the fact that there may be different implementations underneath from users.
from my experience the way log4net's configuration system works in that regard has given me the options I needed. My proposal would be be:
Have max file size configurable and allow for switching roll over based on size on or off. In case the limit is hit, and no roll over on days is specified the log would stop at that point.
Have maximum number of days to retain log files for as a configuration and be able to switch it off separately. In case the maximum number of days is hit, the files for older days are starting to be purged on roll over.
This would offer a fairly flexible configuration system, and the user could decide on the size / convenience tradeoffs.
How does that sound?

**Comment by thinktainer** [comment]
Another question: Would you be adverse to changing the path specification in case of a roll over on both date and size? My proposal would be to then store the daily logs in subfolders with a date naming convention and increment counters in the filename part.

**Comment by nblumhardt** [comment]
Not adverse to it - but moving it forward seems like something we could do more easily as a separate package, perhaps with a view to bringing it in and hiding the implementation differences as you suggest. In the long run, having a built in option is great, but going through churn/pain while we stabilize a new set of strategies (the current one took a while! :)) would be wonderful to avoid if we can. What do you think?

**Comment by thinktainer** [comment]
I now have a size rolling implementation factored out as a separate solution. I would like to get some feedback on it, and then starting the process of handing it over to you. The source currently lives at https://github.com/bedegaming/sinks-rollingfile, if you would like to take a look. Can you advise on how to best proceed from here?

**Comment by thinktainer** [comment]
@nblumhardt do you have time to look into the above any time soon?

**Comment by nblumhardt** [comment]
Will take a look and send some feedback ASAP, sorry it's taken a while - thanks for following up!

**Comment by thinktainer** [comment]
Hey Nicholas, just wanted to ping you regarding this?

**Comment by nblumhardt** [comment]
Hi Martin, the code looks nice. Lots going on so very patchy time available at the moment, apologies again for the lag :-)

It's taken me a bit to wrap my head around where you are going with it, I think I've figured out where we might not be in sync. When I suggested it could be developed as a separate package, I was thinking of a fully-self-contained one (e.g. _Serilog.Sinks.SizeRolledFile_) that could be published and validated over time, and then possibly integrated in the future.

From the Serilog project standpoint, figuring out the goals/naming/positioning of the thing needs some up-front consideration. E.g., initially, would just a pure size-based rolling file be a worthwhile thing to have, or would size/date rolling be the goal? Doing something clearly targeting the current gap, if it's possible, would help to avoid confusing users who are looking for "the rolling file sink".

If doing a focused size-based roller doesn't sound appealing, doing an _AlternativeRollingFile_ as a separate community project would be a great way to get something a bit revolutionary out on NuGet without the constraints of trying to fit something into the bigger picture.

There are pros/cons and other options, would be good to know your thoughts. There's a lot of work in this stuff I know, so nailing down a plan before investing more effort seems like it should pay off.

**Comment by thinktainer** [comment]
Hey Nicholas,
Thank you for getting back to me.
Here are a couple of thoughts regarding your comments:

The driving motivation for me to create this addition is to have a file sink that is able to handle both size and date rolling semantics. A size only rolling implementation whilst, feasible and possibly applicable to our problem would only be a stepping stone to the next evolution.

Another reason for me to consider the size rolling only option to be of less value would be that the implementation would likely need to change when introducing the date rolling behaviour at a later date.

So I'm currently favouring your suggestion of an _AlternativeRollingFile_ which could evolve on it's own and where we could stabilise the integration aspects to the core library iteratively.

I would very much appreciate any support you can dedicate to this endeavour, the most urgent ones being setting up an open source public build, and clarification regarding the permission to use the signing key of the core library.

Does that sound reasonable, and does that answer all your questions?

**Comment by nblumhardt** [comment]
Hi Martin,

Sounds like a good call. Happy to help where I can!

Community projects are usually self-run, i.e. you'd create a build for it yourself on something like AppVeyor (builds for OSS projects are free; great service).

It'd probably be best to generate your own key, it should only take a second in the VS UI - just delete the existing one and then go to the project's Properties > Signing and select the option to generate one there.

We list various community projects on the Serilog wiki here: https://github.com/serilog/serilog/wiki/Community-Projects - may serve as some examples of how they're set up; we can list the alternative rolling file here.

The move towards encouraging independent projects, rather than pulling everything into the Serilog project, is to help spread the load around things like issue tracking, builds, releases and so-on. There's a lot of activity around Serilog so it gets pretty hard to keep on top of otherwise :-)

Feel free to announce on the Google Group, Jabbr chat etc. when you're ready for others to jump in and try it out - happy to help get some attention to it.

All the best,
Nick

**Comment by nblumhardt** [comment]
Hey again Martin - if you decide to go further with this one feel free to reach out; getting the issue tracker under control so will close this for now :-) All the best!

**Comment by thinktainer** [comment]
Thank You Nicholas, I have now published the code in https://github.com/BedeGaming/sinks-rollingfile to https://www.nuget.org/packages/Serilog.Sinks.RollingFileAlternate/. In my opinion it's currently a stop gap, but I will give you a heads up when I'm ready to start promoting it. Thank you for all your advice and time.

**Comment by jarlelin** [comment]
I am currently using the serilog-sinks-elsaticsearch package, and it internally uses a durable log to store events before shipping it to elasticsearch. This is done using the rollingfilesink.

The configuration of the rolling file sink from the elastic sink is easily changable, but I was disappointed when I came here and saw that the choice of rolling on size as well as date was not added or prioritized. 

I would like to add to this issue with my own thouts here. The reason getting this feature configurable into this rolling file sink is that it again is used by other projects and maintaining or changing rolling file sink implementations is less convenient than adding configuration that in turn configures  dependancies.

I would much appreciate the retention policy to inlcude a configuration for rolling on size. Today your code rolls on date, and checks size for stopping to write. What you would need is a third option RollOnMaxSizeInsteadOfStopping. In fact the durable serilog sink doesn't even use the files-to-retain because it handles its own cleanup when reading from the files and shipping. (This is another feature I'd like to upgrade, but thats a story for another issue.)_
