### ISSUE TITLE
Support multiple sets of AppSettings using a custom prefix.

### ISSUE THREAD

**Issue by andrewcupper** [serilog/serilog#430]
At the moment AppSettings are read using `serilog:` as a prefix in the appsettings config section:
``` xml
<add key="serilog:using" value="Serilog.Sinks.Elasticsearch" />
<add key="serilog:write-to:Elasticsearch.serverAddress" value="http://localhost:9200" />
```
It would be useful to allow multiple sets of configuration to be read by supporting the use of custom prefixes, e.g.:
``` xml
<add key="serilog1:using" value="Serilog.Sinks.Seq" />
<add key="serilog1:write-to:Seq.serverUrl" value="http://localhost:5341/" />
<add key="serilog2:using" value="Serilog.Sinks.Elasticsearch" />
<add key="serilog2:write-to:Elasticsearch.serverAddress" value="http://localhost:9200" />
```
which could then be read as follows:
``` c#
var logger1 = new LoggerConfiguration()
  .ReadFrom.AppSettings("serilog1")
  .CreateLogger();
var logger2 = new LoggerConfiguration()
  .ReadFrom.AppSettings("serilog2")
  .CreateLogger()

**Comment by nblumhardt** [comment]
Thanks for the note! Some discussion is already underway here https://github.com/serilog/serilog/pull/332 but needs some more input. Thanks~

**Comment by andrewcupper** [comment]
The distinction is that I want to construct separate loggers (i.e. for different purposes), rather than log to multiple sinks of the same type.

**Comment by nblumhardt** [comment]
Ah I see - thanks for the clarification.

**Comment by nblumhardt** [comment]
Hi Andrew - thanks again for logging this; I think the best option currently is to copy/customize the appsettings support for your scenario (I expect somewhere along the line we may go further towards this, but for now I think the configuration system needs more "bake time" before we start extending it). Cheers!

**Comment by danielwertheim** [comment]
@nblumhardt having the same need. Two different logger configurations, both configured from appsettings but with different variations. With the current release, what is the recommended way to handle this? Gist/docs?

**Comment by caioproiete** [comment]
+1 I would love something like what is being proposed here (a prefix).

I have cases where I'm deploying more than one app in the same pipeline (e.g. client and server), and I'm not able to use config/variables transforms because they would apply the same values to both packages and they should have different log configurations each.

Having a prefix would solve that. At the moment I had to give up on using the AppSettings and had to write my own version of it w/ custom appSettings items using a prefix.

**Comment by nblumhardt** [comment]
Reopening again, thanks for all the feedback. (This might be a good candidate for a PR on the `dev-v2` branch if anyone is interested.)

**Comment by caioproiete** [comment]
I've just opened 2 PRs:

#550 targets v1.5 / `dev`
#551 targets v2.0 / `dev-v2`

Let me know what you think.

Cheers,
Caio Proiete

**Comment by nblumhardt** [comment]
@caioproiete thanks very much for the PRs, looking good.

Given that it's a binary breaking change (added parameter on the `AppSettings()` method, and it's late in the 1.5.x cycle, I'd prefer making the change in v2 only (still several months away I think). Would that be a huge inconvenience? // cc @serilog/core

**Comment by caioproiete** [comment]
@danielwertheim / @nblumhardt I've updated the PR with the default `serilog` prefix, and removed the need to have the `:` (colon) on the prefix.

Let me know what you think.

**Comment by caioproiete** [comment]
@nblumhardt Well, I already have a workaround (internal Serilog add-on library that implements this) so I don't mind waiting for v2.0, but I think it would save other people lots of time - as they have to incorporate a similar code into their apps or build a shared library to re-use in multiple apps.

Do you think that binary change is that big of a deal not to ship it in a v1.5.x? What is your main concern?

ps: I've put all the code into a Gist, in case someone wants to grab it into their apps, in the meantime:
https://gist.github.com/caioproiete/95144d6252aaed477c15

**Comment by IanYates** [comment]
It needn't be a binary breaking change if, instead of using default parameters, you overloaded the methods.  The old ones could even be marked as obsolete if you wanted to go that far.  I personally don't need this, and I think it's *excellent* to be wary of binary breaking changes, but perhaps the best of both worlds could be permitted here? (although you are increasing the API surface a little I suppose).

**Comment by caioproiete** [comment]
Thanks @IanYates. That's not a bad idea.

I actually thought about a proper overload instead of default value param, but @nblumhardt's [suggestion](https://github.com/caioproiete/serilog/commit/186492ef73218c5422a839d339e6787ab25e7140#commitcomment-13995956) in having the parameter self-document, made sense to me and seemed quite valuable to lose.

I'd be fine with the overload, if that was only to make it ship with v1.5.x, and then have the v2.0 implementation use the default value (as in v2.0 we're allowed  (and will do) change the API anyway).

Marking the other method as obsolete I'm not so sure... That means we're encouraging people to be explicit about the default prefix "serilog" when they shouldn't need to.

**Comment by IanYates** [comment]
Good point about the obsolete marking.  Just changing to the default parameter in 2.0 makes the most sense and forget all about obsolete :)

**Comment by nblumhardt** [comment]
Since this has been around so long, perhaps the effort of shipping the overload in 1.5 is worthwhile, with the default value approach in 2.0.

(Evolving methods with default parameters is a horrible pain, but as a user of the library I really like them, so I guess it's just the way things are going to be :-))

**Comment by caioproiete** [comment]
:shipit:
