### ISSUE TITLE
Provide custom configuration extension

### ISSUE THREAD

**Issue by artganify** [serilog/serilog#440]
I have a custom key-value style configuration facility based on some json files which I parse at startup and flatten them to a dictionary using prefixes for complex objects where as those prefixes perfectly match the Serilog AppSettings notation. So I could basically use my own configuration provider, do some json parsing and simply pass it to Serilog for logger configuration creation.

This is however not possible as many internal components of Serilog regarding to configuration are.. well.. internal.

Example configuration I'd like to load and parse...

    {
        "someKey": 258,
        "someOtherKey": "test",
        "serilog": {
            "write-to:RollingFile": {
                "pathFormat": "log-{Date}.log",
                "retainedFileCountLimit": 10
            }
        }

Which I'd then flatten out to..

    "someKey" => "258
    "someOtherKey" => "test"
    "serilog:write-to:RollingFile:pathFormat" => "log-{Date}.log".

(The last parameter notation could be replaced by a dot (.). Piece of cake.)

So, would it be possible to make the internal parts public, so devs can ship their own configuration without the need to rely on System.Configuration? Especially the class `KeyValuePairSettings` in `Serilog/Settings/KeyValuePairs`?

**Comment by nblumhardt** [comment]
Howdy! Thanks for getting in touch - the syntax you've cooked up looks nice.

This is all possible today, but the approach (if you want to use the built-in key/value syntax) is a little quirky in places.

In a nutshell, you can use `LoggerConfiguration.ReadFrom.KeyValuePairs()` within your `ILoggerSettings` implementation to achieve this.

Here's a place you can see it in practice:

> https://github.com/serilog/serilog-generator/blob/master/src/serilog-generator/Program.cs#L18

```csharp
    .ReadFrom.CommandLine()
```

The extension method adds a `CommandLineSettings` instance:

> https://github.com/serilog/serilog-generator/blob/master/src/serilog-generator/Configuration/CommandLineReader.cs#L14

```csharp
public static LoggerConfiguration CommandLine(this LoggerSettingsConfiguration settingsConfiguration)
{
    return settingsConfiguration.Settings(new CommandLineSettings());
```

Which uses the `ReadFrom.AppSettings()` method to hook into the key/value pair syntax:

> https://github.com/serilog/serilog-generator/blob/master/src/serilog-generator/Configuration/CommandLineSettings.cs#L19

```csharp
   public void Configure(LoggerConfiguration configuration)
   {
       var directives = CommandLineDslParser.ParseCommandLine(Environment.CommandLine)
            .ToDictionary(kv => kv.Key, kv => kv.Value);
       // <snip>
       directives.Add("using:_CommandLineSettingsSerilogFullNetFx", "Serilog.FullNetFx");
       configuration.ReadFrom.KeyValuePairs(directives);
```

There's just one tricky piece in there, which is the addition of the _Serilog.FullNetFx.dll_ assembly, since `KeyValuePairs()` is in _Serilog.dll_.

I think this could be more straightforward, and the whole key/value settings DSL put to the side, if we do something closer to what you say and expose the infrastructure for discovering sink configuration methods and so-on rather than tuck these away inside the key/value provider. I hope in the future we can do this, but we don't have a good enough understanding of the different scenarios yet to do it in a stable way.

Hope this helps, feel free to drop more questions in here. It'd be cool to see what you come up with!

Cheers,
Nick
