### ISSUE TITLE
non-breaking format for log template strings

### ISSUE THREAD

**Issue by jakeswenson** [serilog/serilog#445]
Has there been any thoughts into a template string format that doesn't break existing string.Format calls? I ask because I would absolutely love to move over to serilog at work, but the transition isn't easy, because if any component in our log wrapper calls string.format on the supplied format string it will fail.

Is there a way to customize the format string? It'd be great if it supported strings like:

`"Something Happened {{@LoggedObject}} {{SomeOtherProperty}}"` 

is this is made to a type that expects to be able to call string format on that string, it wont log what you expect, but it wont fail with a runtime error. We could then search our logs for this and correct our behaviors.

Specifically given the nice new logging abstractions in AspNet5 i think this is something worth spending time on...

**Comment by jakeswenson** [comment]
Perhaps another option would be do support something like
``` c#
var log = GetLog();
log.With(new { 
    LoggedObject = myObjectToLogPropertiesFrom, 
    someObject.SomeOtherProperty 
}).Warn("Something happened"); 
```

**Comment by nblumhardt** [comment]
Hi Jake, thanks for the note!

AFAIK the goal of the logging abstraction in ASP.NET is to allow general-purpose library/framework code to write generically to any underlying logger, not so much for application code to do this.

If you're writing code that can depend on Serilog, using Serilog's API directly makes sense. Passing Serilog-style message templates through the ASP.NET logging pipeline, while relying on there being a Serilog implementation at the other end, doesn't bring a huge amount of benefit IMO.

I think I'd go so far as to suggest the contract of ASP.NET 5's logger probably _requires_ standard .NET format strings - since the target use case is to permit log4net, NLog or Serilog to format and route the message on the other end.

Abstractions all come with a cost - in the case of ASP.NET 5's logging, the cost is being limited to the lowest-common-denominator set of logging features. Keeping its use limited to library code that actually _needs_ the generic flexibility seems like the right usage to me.

Applications - that make a call about which logging library to use - should conversely take advantage of the full feature set and specific APIs that they have access to.

(I'd hate ASP.NET 5 to herald the arrival of more logging stagnation in .NET! :))

This is all new territory though, so keen to hear what you think if it looks different from your perspective.

Cheers!
Nick

**Comment by nblumhardt** [comment]
One other angle - check out:

https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Framework.Logging.Abstractions/Internal/FormattedLogValues.cs#L13

...which may support the exact usage you're talking about; I need a quick refresher on how this works, will post more detail here.

**Comment by nblumhardt** [comment]
Hi Jake - I don't think we can move much on this ticket right now, since the scenario is an edge case and template format is pretty fundamental and constrained by existing behaviour.

If you need a hand with working around your existing code though, we have a few techniques you can lean on; there's a Jabbr chat linked from the serilog.net homepage, if you want to drop by and discuss some options I'd love to help figure something out.

All the best!

**Comment by jakeswenson** [comment]
@nblumhardt thanks! will take a look
