### ISSUE TITLE
ES sink - problems handling numeric property names

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#462]
By the looks of [this SO post](http://stackoverflow.com/questions/30594051/elasticsearch-with-serilog) using `"Typical {0}-style"` numbered format string holes with ES and Serilog causes issues for the indexer.

Not sure what constraints are being worked with on the ES side, but switching property names like `0` for valid identifiers like `_0` or `$0` is a strategy that works for other sinks.

Ping @serilog/owners-elasticsearch

**Comment by Mpdreamz** [comment]
The 2.0 template has a special provision for field names that are
completely numeric and likely stemming from non serilog log lines. (Usually
through other log framework adapters).

https://github.com/serilog/serilog-sinks-elasticsearch/blob/master/src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkState.cs#L144

And maps them to the safest best: strings.

That said either we have a bug or the users template is old/non existent.

I'm on holiday so I can't dive in but I'm suspecting the latter in this
case.

**Comment by rogeralsing** [comment]
I'm the OP of that SO post. 
It turns out that I was missing this `AutoRegisterTemplate = true`
Adding that makes it all work nicely. 
(The values are still reported as conflicting types inside Kibana. but at least the entries shows up and can be viewed)

While on this topic;
In Akka.NET our interal logging uses this old standard numeric based templates as we can plug in whatever logging framework we want.

Would it be possible to replace the numeric term with a synthetic one?
Make it configurable to replace `{0}` with either the type name of the provided value.
if the value is an DTO or Entity, it would make more sense to transform this into e.g. `{PurchaseOrder}` .
At least it would be possible get some value out of those log lines in ES/Kibana.

Another option could be to extract whatever text is on the left hand side of the term.

`"Akka Remoting is now listening on port {0}", portNumber`

Could be turned into:

`"Akka Remoting is now listening on port {AkkaRemotingIsNowListeningOnPort}", portNumber`
Even if that is sort of corny, its still better than a value that you can not identify in any way.

Maybe both options are just stupid, but I do think it would be nice to be able to extract some business value out of log entries that originate from logging adapters.

**Comment by IanYates** [comment]
Nice idea.
I've gone the other way in an open-source project that we're busy refactoring after a change of "ownership".  I have a PR there which uses Serilog-style logging placeholders and wrote an adapter so those still using NLog (on which the project originally had a hard dependency) could get the log text transformed into numeric-style placeholders.  It won't help you, but here's the PR (not yet merged, and I need to do some slightly improvements as per the comments) in case someone else is interested
https://github.com/fo-dicom/fo-dicom/pull/19

The ability to have Serilog (or, personally for me, even just having this in Seq) extract some semi-meaningful name for an positional template (like {0}) would still be quite handy

**Comment by nblumhardt** [comment]
@IanYates RE doing this in Seq, I'm guessing you've already discovered "Find on this type"? Does pretty much what you suggest, but via creating a filter like `$789af78a0 && @0 == "some value"`. Some shorthand might be nice, but I like the way the semantics are pretty clear in the current scheme. Hard to come up with some magic naming that isn't awful under certain pathological cases :-)

@rogeralsing thanks for the insightful follow-up. I think the discussion about automatically naming numeric placeholders is interesting, but I might close this ticket given the focus has shifted. If anyone wants to kick off another ticket with a proposal that would be cool (though I'm not sure if we could do this in a general enough way not to sometimes fall apart). Cheers!
