### ISSUE TITLE
ElasticSearch sink LogShipper bug

### ISSUE THREAD

**Issue by debwebdanmark** [serilog/serilog#469]
Hi.

It seems the LogShipper only reads the file in the bookmark file, and never updates this file reference.

It creates a file: serilogbufferfile.bookmark and a serilogbufferfile-20150610.json 

as long as the log is written to serilogbufferfile-20150610.json everything works fine. But when a rollingfile serilogbufferfile-20150610_001.json is created, no logs are sent to ElasticSearch. The bookmark is set to the end of file serilogbufferfile-20150610.json, but is never update to start bookmarking on serilogbufferfile-20150610_001.json

**Comment by mivano** [comment]
@mookid8000 sounds familiar to you?

**Comment by mookid8000** [comment]
I haven't noticed that, no - I "stole" the code from [Nicholas' Seq sink's HttpLogShipper](https://github.com/serilog/serilog-sinks-seq/blob/master/src/Serilog.Sinks.Seq/Sinks/Seq/HttpLogShipper.cs).... unfortunately I don't have time to investigate this right now, but maybe the Seq sink can provide a clue (I don't assume there's a bug in the Seq sink, so maybe there's a difference between the two?)

**Comment by debwebdanmark** [comment]
I forked the project and looked into it, and it seems the file is always locked when it tries to read it the second time to retrive the file length.

IsUnlockedAtLength(currentFilePath, nextLineBeginsAtOffset)

So I simply changed it to read this: 
currentFileLengthEqaulsBookmark = current.Length == nextLineBeginsAtOffset;

after it was done reading the file and sending the lines to elastic search.
Then I made the following to support multiple files:

    if (currentFileLengthEqaulsBookmark && !currentFilePath.Equals(fileSet.Last()))
    {
        string newFile = null;

        for (int i = 0; i < fileSet.Length; i++)
        {
            int k = i + 1;
            if (currentFilePath.Equals(fileSet[i]) && k < fileSet.Length)
            {
                newFile = fileSet[k];
                break;
            }
        }

        if (!string.IsNullOrEmpty(newFile))
        {
            WriteBookmark(bookmark, 0, newFile);
        }
    }

**Comment by nblumhardt** [comment]
Hi @debwebdanmark - just a thought (since this code is pretty widely used, so shouldn't have super-obvious bugs like this). Are you creating only one instance of the logger/sink, or are you configuring it multiple times? Multiple instances might be one possible cause of the locking issue. Any insights?

**Comment by nblumhardt** [comment]
@debwebdanmark any further info on what triggers this?

**Comment by debwebdanmark** [comment]
@nblumhardt nope. I use a single instance. Even tried using it in a unittest, but it was still locked. So at the moment I use my above fix, since it never continued.

**Comment by ewilansky** [comment]
I've experienced the same behavior with this sink. I enabled selflogging to the console:
Serilog.Debugging.SelfLog.Out = System.Console.Out;
and the thrown exception clearly shows what @debwebdanmark described:

2015-07-15T10:10:19 Exception while emitting periodic batch from Serilog.Sinks.Elasticsearch.ElasticsearchLogShipper: System.IO.IOException: The process cannot
access the file 'c:\logs\serilogfilebuffer.bookmark' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions o
ptions, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean
bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Serilog.Sinks.Elasticsearch.ElasticsearchLogShipper.OnTick()

I'm getting his fork to test the solution. Thanks for putting something together. Perhaps with more testing you could submit a pull request?

**Comment by nblumhardt** [comment]
@ewilansky thanks for the additional information. Another possibility - are you running under IIS? Just clutching at straws - hard to figure out how this code works for the Seq sink but not the ES one, since they're so similar in every other respect.

This may be a red herring: `because it is being used by another process` but it's also possible there's actually another process actually locking the file... It's tricky to track it down, but finding the responsible process would help if possible.

**Comment by ewilansky** [comment]
Hi @nblumhardt, 
I'm logging from a console/service app. In this case, IIS isn't involved. However, you are right that another process is locking the file. Originally, to run the console/service app, we were using a framework that would spawn multiple processes. Today, we switched away from that in favor of Akka. In this case, we can spawn multiple actor systems, which is then spawning multiple threads instead. The result is that we get a single buffered serilog file and it also improves our story using the Rolling Log File sink since we aren't running into conflicts there too, thus fewer rolling log files. 

Thanks for the quick response. I would say this isn't a bug in the Serilog ES sink, but instead warrants a caution about how logging is done from an application that will spawn multiple processes that attempts to access the bookmark file. It would be cool to have a feature in the Serilog ES sink that would create multiple bookmark files, one for each process. I would consider this a feature request and not a bug.

**Comment by nblumhardt** [comment]
@ewilansky thanks for the follow-up, great to have the additional info.

@debwebdanmark does this sound like it might explain your observations? I.e. is there a possibility of any other process locking the bookmark file?

Cheers!

**Comment by B-Esmaili** [comment]
Hey there. What is the outcome of this topic? I see no additional config introduced in newer versions (related to this issue) and still I get same error. anyone has any advice on how to resolve the issue?
