### ISSUE TITLE
Avoiding params array and boxing allocations when the level isn't enabled

### ISSUE THREAD

**Issue by justinvp** [serilog/serilog#479]
Hi Nick!

I'm really loving Serilog! In addition to all the structured logging goodness, I like the simple usage that the static `Log` class provides:

```c#
int x = 1;
int y = 2;
int z = 3;

Log.Debug("The values are {X}, {Y}, and {Z}", x, y, z);
```

However, this results in 4 heap allocations (the params array allocation and 3 box allocations for the value types) even when the debug level isn't enabled. Such allocations aren't immediately obvious to most developers unless they're aware of the issue.

This can be avoided by checking `IsEnabled` before the call:

```c#
if (Log.IsEnabled(LogEventLevel.Debug))
    Log.Debug("The values are {X}, {Y}, and {Z}.", x, y, z);
```

But then I have to remember to always check `IsEnabled` before the actual call to avoid the allocations when the level isn't enabled, which isn't as nice as simply calling `Log.Debug`.

It'd be nice if there were some built-in generic overloads (up to ~3-4 parameters), similar to `String.Format`'s and `Console.WriteLine`'s arg0, arg1, and arg2 overloads, but generic. The implementation inside such overloads could first check `IsEnabled` and only allocate the array (and box any value types) if the level is enabled.

NLog provides generic overloads along these lines for this reason.

Something like:

```c#
public static class Log
{
    ...

    [MessageTemplateFormatMethod("messageTemplate")]
    public static void Debug<T0>(string messageTemplate, T0 propertyValue0)
    {
        if (IsEnabled(LogEventLevel.Debug)
            Logger.Debug(messageTemplate, new object[] { propertyValue0 });
    }

    [MessageTemplateFormatMethod("messageTemplate")]
    public static void Debug<T0, T1>(string messageTemplate, T0 propertyValue0, T1 propertyValue1)
    {
        if (IsEnabled(LogEventLevel.Debug)
            Logger.Debug(messageTemplate, new object[] { propertyValue0, propertyValue1 });
    }

    [MessageTemplateFormatMethod("messageTemplate")]
    public static void Debug<T0, T1, T2>(string messageTemplate, T0 propertyValue0, T1 propertyValue1, T2 propertyValue2)
    {
        if (IsEnabled(LogEventLevel.Debug)
            Logger.Debug(messageTemplate, new object[] { propertyValue0, propertyValue1, propertyValue2 });
    }

    // TODO add overloads for the other levels

    ...
}
```

Similar overloads could be included for `ILogger` as extension methods.

Users would then be able to simply call `Log.Debug`, which would be a no-op with no allocations when the level isn't enabled, for the most common number of parameters.

Of course I could always implement my own custom static `Log` class and `ILogger` extension methods that do this for my own projects, but I thought it might be worth having these (or something like them) built-in so all Serilog users could benefit.

I'd be happy to submit a Pull Request, if you're open to the idea.

**Comment by nblumhardt** [comment]
Thanks for the suggestion Justin, makes a lot of sense.

Let me give some thought to the mechanics of this. Changing the `Log` static class seems like a no-brainer.

I think in the absence of better options, extension methods on `ILogger` would work, but hitting different overloads depending on whether `using Serilog` is present would be nice to avoid. Weighing up whether it's a "v2" kind of change... :-)

Cheers!

**Comment by nblumhardt** [comment]
Hi Justin,

With the impending VS2015 release, I suspect we're going to end up wanting to make some breaking changes in the assembly layout, so it's probably not a bad time for us to start collecting up some of the `breaking` tickets so we can make the most of the opportunity.

Here's how we could do this one:

1. Submit a PR against `dev` for the `Log` class static methods - this'd go straight in to a Serilog 1.5 update
2. To restore the "symmetry", submit a PR to the (just created) `dev-v2` branch; this'd roll into Serilog 2.0 at an opportune moment

Does that sound reasonable, and not too much fiddling around?

Cheers!

**Comment by nblumhardt** [comment]
(It'd probably work best if the `dev-v2` change came after the `dev` changes merged, since I think there'd be an implementation dependency.)

**Comment by justinvp** [comment]
Sounds good to me! I'll get started on an initial PR for the first part, for Serilog 1.5.

**Comment by justinvp** [comment]
I submitted #484 for the first part.

For the second part, you want the overloads added directly on the `ILogger` interface (hence the v2 breaking change), or something else?

**Comment by nblumhardt** [comment]
Thanks - will check out the PR ASAP, may take a day or two.

I was definitely intending we'd add these to the interface. There's also an abstract base class option I've been re-thinking, and an interface + ABC option too, but in the short-term having the overloads on the interface in the `dev-v2` branch sounds right.

CC @serilog/core

**Comment by nblumhardt** [comment]
Sorry about the previous vague comment - doesn't look like my coffee was strong enough this morning...

I think there are two ways we could go about extending `ILogger`:

1. Stick with the current design: add the overloads to the interface, and to ease the task of updating third-party implementations ship an abstract `Logger` base class that lets others implement `ILogger` cheaply/stably by supplying only `Write()`*
2. Make the first change, but also make `LoggerConfiguration.CreateLogger()` and `ILogger.ForContext()` return `Logger` instead of the interface, effectively deprecating the interface and instead going for the more stable abstract base class design

With a bit more thought I end up favouring 1), since 2) causes just as much churn up-front, creates "legacy" and has no guarantee it will actually pay off in future anyway.

It's still also a possibility we'll postpone breakage, if we don't end up with enough motivating changes from [the current list](https://github.com/serilog/serilog/labels/breaking%2Fv2) and ASP.NET 5/DNX support to make it worthwhile this time around. Unless we start to accrue some of this work on the "v2" branch though, we'll never reach that tipping point :-) I just have to mention it since it's therefore possible PR number 2 could take some time to get across into master.

_* The internal implementation would stay as-is, to avoid paying for the extra virtual dispatch :)_

**Comment by nblumhardt** [comment]
This is now down on the v2 list as #585 - we're just going to add the methods to the interface and accept the breakage. Any help there would be appreciated. Closing this ticket in favour of the new one :-)
