### ISSUE TITLE
Email-Sink: Send batch only if there is an error

### ISSUE THREAD

**Issue by fabsenet** [serilog/serilog#481]
Hi!

What is the best way to configure the email sink to send only errors but to also contain the last 100 messages (not erros) as well?

I obviously want to have context to work with, when I get an error mail but I only want to get mails, if there are errors?

Thanks!

**Comment by nblumhardt** [comment]
Hi Fabian,

This notion's been discussed here before under the moniker "transactional logging", but it poses some significant challenges to implement generically in Serilog so we haven't managed it so far. For server apps the biggest challenge is to collect events relevant to the work being done, e.g. per HTTP request or so-on, since busy apps could easily generate 100 irrelevant messages from other threads/tasks between events relevant to the triggering exception.

It's possibly something that could be done in a sink-specific way, at least as a proof-of-concept. If you decide to have a shot at it, your experiences would be interesting to share.

Cheers,
Nick
