### ISSUE TITLE
LogEvent.Properties - breaking change in .NET4.5

### ISSUE THREAD

**Issue by swiftytom** [serilog/serilog#492]
I use Serilog in a .NET 4.0 project, therefore the net40 DLL version is chosen by Nuget and that's what it's compiled against. Then this project is published as a Nuget. 
Then I use this Nuget in a .NET 4.5 project, Nuget sees the dependency on Serilog, pulls the package and chooses net45 version. Then I get this exception at runtime, everytime a custom sink's Emit is called and tries to have a look at log event's Properties:

 Caught exception System.MissingMethodException: Method not found: 'System.Collections.Generic.IDictionary`2<System.String,Serilog.Events.LogEventPropertyValue> Serilog.Events.LogEvent.get_Properties()'

That's because the net45 version has different signature (IReadOnlyDictionary instead of IDictionary). Is this intended, or is it a bug?

**Comment by nblumhardt** [comment]
Hi @swiftytom - thanks for getting in touch. Unfortunately, Serilog was originally built for .NET 4.5+ and only later back-ported to .NET 4.0, at which time some APIs had to change in incompatible ways because of the absence of these types on .NET 4.

The workaround in your case is to manually change the Serilog.dll reference in the downstream project to point to the .NET 4 version of the DLL in the NuGet package, rather than the .NET 4.5 location NuGet will choose.

Cheers,
Nick

**Comment by swiftytom** [comment]
I see, thanks for the info. In the end I solve it as you suggest - by adding two new build configurations in the old projects which have <TargetFrameworkVersion> set to 4.5, and in .csproj I use these configurations to conditionally create references to either net40 or net45 versions of Serilog from it's package folder. More info on: http://shazwazza.com/post/multi-targeting-a-single-net-project-to-build-for-different-framework-versions/
