### ISSUE TITLE
Support LoggingLevelSwitch on a per-sink basis

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#505]
Sink configuration methods accept a `restrictedToMinimumLevel` parameter of type `LogEventLevel`. Augmenting this or replacing it with `LoggingLevelSwitch` would permit individual sinks to be manipulated at runtime. May assist with #485 and similar issues.

**Comment by caseymarcallen** [comment]
@nblumhardt We are looking at the Serilog.Sinks.Seq sink and have modified it to accept a `LoggingLevelSwitch` instead of a `LogEventLevel` so the min level that is returned from the HTTP call to the Seq server can be exposed to the rest of the application rather than being hidden inside the internal `_minimumAcceptedLevel` variable. 

Our specific use case is that we are exposing a route in our MVC website so that web clients can log from javascript. We then use the website and the Seq Sink to forward this information on to the internal Seq Server. We do however want to expose that min level back to the javascript so that they only post the log events over the network back to the server if the level is greater than the min level as configured by the Seq Server API Key. Hence we want access to that `mininumAcceptedLevel` value that the sink if using.

I was about to submit a pull request against the Seq Sink, then noticed this thread here. What are your thoughts on the `SeqSink` using a `LoggingLevelSwitch` internally instead of a `LogEventLevel` and allowing the switch to be passed in via the `SeqLoggerConfigurationExtensions.Seq()` extension method instead of the `LogEventLevel`. It's not a Serilog global solution like you are proposing here, but it suits the Seq Sink purpose.

**Comment by nblumhardt** [comment]
Hi Casey, thanks for the info. Good to validate there's more than one scenario for this.

To avoid too much version compatibility juggling, I'll tackle the core Serilog change ASAP, probably in the next few days. Some help propagating this out through the various sinks would be great, if you're still keen to jump in once the foundation is laid!

**Comment by caseymarcallen** [comment]
Sounds good. Happy to help where I can.

**Comment by nblumhardt** [comment]
The foundations are there in #511 - a little stalled on deciding how it should go out (1.5, 1.6, 2.0, ...) - thoughts appreciated on that one.

**Comment by caseymarcallen** [comment]
@nblumhardt I've implemented the functionality in the Seq Sink and while testing various scenarios noticed that if you are logging with an API key to Seq and have the min level set to something against the Seq API Key, if you then delete that key Seq will continue to report back to the Seq Sink the previous API key min level. I would have expected it to start reporting back null. Bug in Seq or by design?

**Comment by nblumhardt** [comment]
@caseymarcallen thanks for the heads-up. Sounds low-pri, but likely a bug. Created https://github.com/continuousit/seq-releases/issues/334. Cheers!
