### ISSUE TITLE
Destructuring child objects such as byte from byte[]

### ISSUE THREAD

**Issue by johnkattenhorn** [serilog/serilog#506]
I guess this is similar to another issue I raised #493, I'm trying to put in a 'global' destructure; something like
     .Destructure.ByTransforming<byte>(bytes => "0x" + ((int)bytes).ToString("X2"))

I'm hoping that this would allow me to add a context property or de-structure a message which had a byte[] in it into the format 0x00,0x00 etc. but instead I simply get System.Byte[].

What I'm trying to avoid is lot's of destructure config for lot's of the classes with the only thing changing is the way I'm outputting a particular byte array.

**Comment by nblumhardt** [comment]
Hi John - implementing `IDestructuringPolicy` directly might be a cleaner option for this scenario; not sure if the "transforming" option will do the job here.

You still need to trigger destructuring with `@`-prefixed property names, so if it isn't behaving as you'd expect this might be something to check.

**Comment by johnkattenhorn** [comment]
Ah cool, so if I do something like Log.ForContext("Message",message,true) I should still use the @ ?

I'll build out a little test and try out the IDestructuringPolicy.

**Comment by IanYates** [comment]
@johnkattenhorn  - I don't think you need the "@" since you're passing true (the tone on your text that I've got in my head reads as though you suspect this too and are just double-checking :D ).  

But certainly you'd need the "@" if you're doing a Log.Debug("Problem due to {@something}", something).

**Comment by nblumhardt** [comment]
That's correct - you don't need the `@` if you're using `ForContext()` since the Boolean parameter fulfills that role, it's only part of the templating syntax.

@johnkattenhorn it could be that Serilog's scalar conversion policy for `byte` and `byte[]` are taking precedence over your custom policy; it'd be interesting to hear what your investigations turn up. The relevant code is in https://github.com/serilog/serilog/blob/dev/src/Serilog/Parameters/PropertyValueConverter.cs#L99

**Comment by nblumhardt** [comment]
Feel free to comment/reopen if there's anything we need to do here. Closing for now as this ticket is a bit long in the tooth :-)
