### ISSUE TITLE
Any plans for ports to other languages?

### ISSUE THREAD

**Issue by oliverjanik** [serilog/serilog#516]
I'd be particularly interested in golang port :+1:

**Comment by nblumhardt** [comment]
Hey Oliver!

I'd absolutely love to see a golang port - seems like Serilog-style logging would be very useful for the kinds of apps people are building in Go. I don't have the time to attempt it, but I'd be happy to help in any way I can if you decide to give it a shot :-)

Other languages:

* JavaScript - @ashelydavis and I (mostly Ashley of late :-)) have been working on https://github.com/structured-log/structured-log for Node and the browser
* F# - not a complete logging library yet, but @AdamChester has been implementing the core templating/capture system in https://github.com/adamchester/MessageTemplates

I'm also chipping away at some Rust macros to do similar things, but they might not see the light of day for a long while :-)

I've also wanted to try a Java port for some time, since Java 8 makes implementing nice APIs much easier than that task was in earlier versions.

**Comment by oliverjanik** [comment]
Awesome, JS port will come in handy, for sure!

I'll have a peek at Serilog core to see how much of a commitment the golang port would be.

Thanks for the answer!

**Comment by jyee-ctm** [comment]
FYI if anyone pops into here the JS library mentioned above has not been maintained for a long time.
Another fork has popped up which has resolved some of the issues of structured-log: https://github.com/davisb10/serilogger.

Disclaimer: I cannot vouch for the security of the library. structured-log had the backing of Serilog (trusted) but not this.
So take it as your own as logging could potentially be a target for supply chain vulnerability.
