### ISSUE TITLE
Create repository serilog-sinks-exceldna

### ISSUE THREAD

**Issue by CaioProiete** [serilog/serilog#522]
Hello,

I've created a Serilog Sink for the [ExcelDna](https://github.com/Excel-DNA/ExcelDna) LogDisplay, so we can visualize logs from the Excel Add-ins.

Could you please create a repository "**serilog-sinks-exceldna**" and give me access to push to it?

Thanks,
Caio Proiete

**Comment by nblumhardt** [comment]
Hi Caio! Thanks for getting in touch, this sounds very interesting.

We've changed how we accept third-party sinks into Serilog because of the maintenance and support challenges that a large number of projects incur. We're still open to including new sinks as you've suggested, but we now encourage contributors to set up and publish sinks independently to gauge interest and work through the early stages of taking feedback/issues and so on.

There's now a growing [third-party sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks#third-party) section on the wiki to help promote additional sinks - we can add ExcelDNA there too when it's ready.

Once the sink has been published and in use for some time, new sinks can come into the Serilog project via a repository transfer if there's a benefit to be had.

There's some more discussion in the (lengthy) #344 ticket - let me know if you need a hand with anything along the way.

Cheers,
Nick

**Comment by CaioProiete** [comment]
Hi @nblumhardt,

Thanks for the prompt reply.

No problem. I'll proceed as you described, and later send a PR to the update the third-party sinks when it's available on NuGet.

Questions*:
- Is it OK to use the name `serilog-sink-exceldna` in this case, being a third-party sink?

- I see some official sinks are signed with the Serilog certificate. Is that a requirement? ExcelDna is not signed, so I couldn't do it.

* Sorry if any of these questions are answered on #344. Didn't read that yet.

**Comment by nblumhardt** [comment]
Awesome, thanks Caio.

* Yes, absolutely fine by us
* No, signing's not required
* #344 is a bit of a dog's breakfast, so feel free to post more questions here :+1:
