### ISSUE TITLE
Hardcoded colors for Console Sink

### ISSUE THREAD

**Issue by pardahlman** [serilog/serilog#525]
Looking at the code for [`ColoredConsoleSink.cs
`](https://github.com/serilog/serilog/blob/dev/src/Serilog.FullNetFx/Sinks/SystemConsole/ColoredConsoleSink.cs#L42), the different log levels has hard-coded colors. It would be a nice touch if this was configurable.

**Comment by nblumhardt** [comment]
Thanks for the feedback! I'm a bit hesitant to consider this because there are always hidden costs to weigh up against configurability. For example, `ConsoleColor` doesn't necessarily work the same way across platforms.

The design goal of this sink is not ultra-ambitious, with alternatives now being considered as separate packages, see for example https://github.com/serilog/serilog-sinks-literate which ships as a separate package. If you are interested in exploring a more feature-complete coloured console option it'd be interesting to see! (There's also a third-party alternative rolling file, doing similar things: https://github.com/BedeGaming/sinks-rollingfile.)

Cheers! :-)

**Comment by pardahlman** [comment]
Ah, perfect @nblumhardt -- thanks!
