### ISSUE TITLE
Seeking guidance on how to use LogContext.PushProperty after a task is await'd

### ISSUE THREAD

**Issue by sstorie** [serilog/serilog#529]
I have an issue I'm hoping to get some guidance on. I am using Serilog in a number of situations, writing custom log sinks to help, and it's working out very nicely. However, I have run into a situation I'm not sure how to resolve.

I have applications where I want to include an employee ID value with my logs, but the employee ID is not known until a user logs in (so I can't set it at configuration time). To handle this I wanted to simply push this value using `LogContext.PushProperty(...)`. My problem is that my process for logging a user in is asynchronous (using async/await), so when I know the value to push I'm no longer on the initial thread.

The end result is that properties I push only last until the method that pushes them completes, and then control returns to the original thread, and the context reverts to what it was before I async/await'd in the login process.

To demonstrate this I created a very simple demo WPF application and write-up here: https://github.com/sstorie/SerilogDemo.Wpf/tree/develop

I assume this is the intended behavior of Serilog, so I'm not insinuating this is a bug of any kind, but I'm wondering if there's a good pattern to follow in a situation like this. How can I push a value to the context when it's not known until after I await some task?

**Comment by sstorie** [comment]
Ok, I guess posting an issue is my version of [asking the duck](http://www.rubberduckdebugging.com/) :)

One solution here is to not push the value on to the log context from the async method, but instead return it to the caller and push it there. This brings the value back to the original thread, and then pushing it onto the context behaves as I was expecting. This could be troublesome in a situation where you have many properties that might be set, and need to be returned, but I don't have that case right now.

**Comment by IanYates** [comment]
The LogContext is async/await aware (there's a better term than that which escapes me at the moment) - it doesn't matter so much what thread you're on but the wrapped Task.Run(()=>...) stuff going on makes the context difficult to flow around.

Also, the LogContext likes to have its pushed properties added and then disposed of in the correct order (stack/FILO order).  I suppose pushing a couple of properties at the very beginning which are never popped doesn't technically violate this :)

If I was in your shoes I can think of two approaches
1. What you've suggested.  That way you needn't worry about flowing the context around and don't have to reason about it
2. Replace what is effectively your global logger instance with a new logger that has the extra property weaved in.  So long as you always fetch the logger from this instance you'll be right.  If you do pass this logger around then you could get different loggers in different areas depending on whether or not they were initialised before or after the login.  One way around this is to pass a Func<ILogger>() around instead, or make your own ILogger implementation which then defers to the global one.

And I'm the same about asking the duck :)  Although too often I wait ages to post a question because I keep thinking it through.  Usually I end up not having to ask because I've worked it out (and should really blog about it!), so when I do ask it's a massive dump of my entire thought process.

**Comment by merbla** [comment]
@sstorie how did you go with this?

**Comment by sstorie** [comment]
@merbla I actually don't have a solid solution yet. For the moment I've decided to let this sit and will probably come back to it at some point in the future. I'd like to explore Ian's second solution a bit, but have had to focus on other work so haven't had the time yet.

If you happen to attempt a solution at this I'd love to hear more about how it goes (I'll do the same too).

**Comment by nblumhardt** [comment]
Not sure this is something we can address with `LogContext` - by definition it's based on the ambient call context, so short of passing an `ILogger` around there's not a lot that can be done for spawned threads.

One option:

```csharp
var parent = LogContext.Export();

Task.Run(() =>
{
   LogContext.Import(parent);

   Log.Information("Here 'tis");
});
```

_Export_ and _Import_ probably aren't great names, but you get the idea... Thoughts?

**Comment by nblumhardt** [comment]
Feel free to post/add notes if there's anything we can do here.

**Comment by sstorie** [comment]
Will do. Thanks!
