### ISSUE TITLE
WriteTo.Logger() does not use Destructure settings of nested logger

### ISSUE THREAD

**Issue by skwasiborski** [serilog/serilog#539]
Hi,

I would like to be able to set different destructure max depth or destructure policy for nested loggers. I would like to have detailed (deep) log in Seq/mongo and very flat in console. My console logger is created in the WriteTo.Logger() call.

Currently parent Destructure options are used.

**Comment by nblumhardt** [comment]
Hi - this one is a pretty deep implication of how the logging pipeline works - destructuring is applied at the point of event creation. I think we have to close this as by-design, because making it work otherwise would require a fundamental redesign that would not otherwise be desirable.

I'll post here if I think of a workaround. Thanks for getting in touch!

**Comment by skwasiborski** [comment]
If so it would be nice if configuration would throw exception when trying to set destructure max depth on nested logger. If you would like I can try to make pull request with such change.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. Unfortunately I don't think the way the API is organised would support making this change, but let me know if I'm mistaken here. Cheers!
