### ISSUE TITLE
Azure Cloud Services Definition Does Not like Serilog: format

### ISSUE THREAD

**Issue by johnkattenhorn** [serilog/serilog#544]
Azure Cloud Service Definition files does not like:

`<Setting name="serilog:minimum-level" />` , it errors with
`Name is invalid, The value "serilog:minimum-level" is invalid according to it's data type` 

Removing the colon (:) makes it valid again. I've seen this issue #536 which seems like I might be able to change the format without making a code change. Does anyone know if this is possible ?

**Comment by iamkoch** [comment]
Seems you can either

1. Add an Azure-Friendly name to SeriLog
2. Stick it in an app.config
3. Use your own key and set this programmatically in the WebRole.cs / WorkerRole.cs OnStart() method

Personally a PR for 1 and implementation of 3 make the most sense to me.

**Comment by nblumhardt** [comment]
Yes, pretty much. I think 3 is realistically the best option to pursue, since CSDEFs are probably not the only related format, and adding extension points to handle all of this generically will build in complexity we might not want to carry forwards.

Another option could also work:

_4. grab the source of `ReadFrom.AppSettings()` and customise it for your app_

Not always appealing but could help here.

@johnkattenhorn what do you think?

**Comment by johnkattenhorn** [comment]
I think we will end up with (3) or (4) in the end. (Right now we dodge the problem by leaving them in the .config file).
