### ISSUE TITLE
Additional payload limiting controls

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#565]
Serilog allows destructuring depth to be controlled, which prevents the accidental serialization of some massive object graphs.

The two remaining causes of unanticipated payloads are:
1. Very long strings
2. Very large arrays or dictionaries

Significant thought will need to go into the implications and design, but it seems like the v2 release is a good time to consider introducing _maximum string length_ and _maximum collection count_ controls on `LoggerDestructuringConfiguration`.

These would either default to "off", or to some very large/permissive values.

**Comment by nblumhardt** [comment]
Mentioned: https://groups.google.com/forum/#!topic/serilog/aPRsprV5PMs

**Comment by IanYates** [comment]
I too am interested in something like this.  I haven't had time to dig into the destructuring code but I ran into a nasty problem, only visible when I had verbose logging enabled, where I logged out an object from a PDF library we use.  I've since written manual destructuring code to handle it nicely but the several hundred MB of stuff generated wasn't great for performance :sparkler: 

I was just logging an obscure type of PDF field that didn't conform to norms but I think that field object had references back to the document, which had references to every man and his dog, etc.  The limits here - max collection size & depth - may well have helped but I'm wondering if there's a way to design this such that once we start descending down a property path we could allow at most `x` KB of JSON to be generated.  That's still hard since the root object really needs a high `x` and several levels down you want `x` to diminish.  I guess it could drop by a factor of 10 or something each time.

The idea is that we can get something meaningful in the log (and upon seeing it recoil and go write a custom destructuring policy) rather than accidentally chewing up lots of processing time creating the log event.  In my case, I don't really test the code path with verbose logging turned on but would rely on using the LoggingLevelSwitch to throw production into verbose logging.  Instead of a crash and caught exception I got a really long pause :smile_cat: followed by the same (expected) crash/exception.  Testing probably wouldn't have caught this since it was on the failure path (hard to get to for a borked PDF field) and I tend to have the logger set for null logging for most tests.

It's a bit of a strange heuristic, and I'm not sure if it's easy to retrofit into the current pipeline, but I'd be happy to look at this in mid-April or so once v2 of Serilog is out.  Thoughts?

**Comment by nblumhardt** [comment]
JSON size would be difficult because that kind of serialization occurs later, but I like the idea!

Perhaps we could come up with an equivalent heuristic, like "nodes" where a node is a property, collection element, or _n_ string data characters?

Not going to be exact, but would be nice to keep it to a single semi-explicable metric rather than a variety of individual depth/width/char count controls....

**Comment by nblumhardt** [comment]
Just realised this is a duplicate of #530, will move discussion there.

**Comment by nblumhardt** [comment]
Ropening after looking at 530 again, not in fact a duplicate.

**Comment by nblumhardt** [comment]
Just a note for anyone looking for a shorter-term option, if the goal is to limit output rather than intermediate working set, then enrichers can be used to implement this. An example showing some simple string limiting: https://gist.github.com/nblumhardt/908ba2ba50bbde8d233702443aa4bb8a

**Comment by nblumhardt** [comment]
v2 is here and unfortunately this one will not make it in time. Hopefully post-2.0 we'll get some momentum on it!

**Comment by krajek** [comment]
I guess this issue can be closed after 'Payload limiting' PRs were merged.

**Comment by nblumhardt** [comment]
Thanks @krajek 👍
