### ISSUE TITLE
No way to add custom scalar conversion policy?

### ISSUE THREAD

**Issue by konste** [serilog/serilog#576]
Being accustomed with the ability to add custom destructuring policies I expected scalar conversion policies to be as accessible, but it does not seem to be the case. Am I missing anything?
My specific goal is to skip from log events all scalar properties with null values (not set).

Thank you!
Konstantin

**Comment by nblumhardt** [comment]
Hi Konstantin,

No, you haven't missed it - thought `IScalarConversionPolicy` is public, the API doesn't provide any mechanism for hooking one in. It's an omission that would be nice to fix in v2, where we could also review the mentioned interface to make sure it is going to "do what it says on the box" :-)

Regards,
Nick

**Comment by konste** [comment]
Thank you Nick! BTW speaking of v2 I can hear some vague ramblings about it, but nothing definitive and nothing from you! Am I looking at the wrong places or it is deliberately kept secret?

**Comment by khellang** [comment]
@konste It's sitting in the dev-v2 branch for now :smile:

**Comment by konste** [comment]
Without custom scalar conversion how to solve this problem:
Elasticsearch does not like strings longer than 32K. During logging we periodically hit ViewStateException (as inner exception to something else) and it has PersistentState property, which is the string and it tends to be much longer than Elasticsearch can chew. 

How to intercept appearance of those poisonous strings during object destructuring, so they are not sent to ES and rejected. We need to truncate them or replace with the placeholder.

I probably can tackle this very specific case with exception destructuring policy, but I would like to protect myself from extra long strings everywhere, not just in this particular property.

Ideas?

**Comment by nblumhardt** [comment]
Progress on v2 has been slow, but mostly because v1 is awesome ;-) .. The main goal of the release is to realign with the newer VS tooling and .NET platforms.

Soon we'll merge the work sitting in `dev-v2` across to `dev`, and things will start to move a little quicker. Taking things conservatively in anticipation of more churn...

I have raised an issue #565 to cover precisely this issue - until we tackle that I think making the change in the ES sink itself would be the most natural option. Hope this helps.

**Comment by konste** [comment]
I was able to intercept and truncate extra long strings in any property at ElasticsearchJsonFormatter level (part of ES sink).
