### ISSUE TITLE
Hello ColoredConsole?

### ISSUE THREAD

**Issue by qujck** [serilog/serilog#596]
Please can you add something to Getting Started describing how to see the ColoredConsole?

**Comment by JohnyMac** [comment]
Had the same exact issue, would be great if it's added to the wiki.

**Comment by merbla** [comment]
Hey @qujck @JohnyMac do you mean something like the following console app?

 - [Splunk Sample](https://github.com/serilog/serilog-sinks-splunk/blob/master/sample/Serilog.Sinks.Splunk.Sample/Program.cs)

**Comment by qujck** [comment]
Hi @merbla ,

getting started has this:

```csharp
var log = new LoggerConfiguration()
    .WriteTo.ColoredConsole()
    .CreateLogger();
```

but I've no idea how to see the stuff being logged.

**Comment by merbla** [comment]
@qujck was it specifically the console app or viewing the output in general/other sinks as well?

**Comment by qujck** [comment]
TBH I've been doing this for 5 minutes so I don't even know how to answer your question (***noob alert***)

**Comment by qujck** [comment]
The point is I'm not started and now I'm googling trying to figure out how to get started :-)

**Comment by merbla** [comment]
In the short term, does the following help?  

- New Console Project
- `Install-Package Serilog`

[Grab this code](https://gist.github.com/merbla/4e3fde401475b5522455)

**Comment by merbla** [comment]
Thanks @qujck @JohnyMac for the feedback.  Added to the [Getting Started](https://github.com/serilog/serilog/wiki/Getting-Started) page with a quick [example](https://github.com/serilog/serilog/wiki/An-Example-using-the-ColoredConsole-Sink).

**Comment by qujck** [comment]
Yes that works thanks, so is ColoredConsole only for Console apps?

**Comment by merbla** [comment]
If you are using Serilog with ASP.Net, Seq is a great place to start (especially local dev).  Also the following are probably also worth a look.

- https://github.com/serilog/serilog/wiki/Community-Projects
- https://github.com/serilog-web/classic

**Comment by JohnyMac** [comment]
Is there anyway i can run a console logging on a normal WinForms project ?

**Comment by qujck** [comment]
I'm wondering the same thing about web projects. It would be much nicer to be able to see the events as they occur rather than scrolling the wrong way through a text file after the event ...

**Comment by IanYates** [comment]
For web projects, set up VS so it runs IIS Express as a console app rather than using the little notification area helper thingy.  Then any console output is readily available alongside other stuff IIS puts out (the HTTP requests are listed as they are processed).

Let VS create settings in your applicationhost.config  ([Documents]\IIS Express\config) by running your site normally at least once.  (you can also edit this file manually).

Then, to switch to console-based IIS, and run the 64-bit version too if you like

Edit your csproj file in a text editor
Within your `<project>` node, add this   (note you may already have a good deal of this in your project file)
```
  <ProjectExtensions>
    <VisualStudio>
      <FlavorProperties GUID="{349c5851-65df-11da-9384-00065b846f21}">
        <WebProjectProperties>
          <UseIIS>False</UseIIS>
          <AutoAssignPort>True</AutoAssignPort>
          <DevelopmentServerPort>49528</DevelopmentServerPort>
          <DevelopmentServerVPath>/</DevelopmentServerVPath>
          <IISUrl>http://localhost/*******</IISUrl>
          <NTLMAuthentication>False</NTLMAuthentication>
          <UseCustomServer>True</UseCustomServer>
          <CustomServerUrl>
          </CustomServerUrl>
          <SaveServerSettingsInUserFile>False</SaveServerSettingsInUserFile>
          <servers defaultServer="IIS Express x64">
            <server name="IIS Express x64" exePath="c:\Program Files\IIS Express\iisexpress.exe" cmdArgs="/site:[[[NAME_OF_SITE_FROM_APPLICATION_HOST.CONFIG]]]" url="http://localhost:13876/" workingDir="{solutiondir}" />
          </servers>
        </WebProjectProperties>
      </FlavorProperties>
    </VisualStudio>
  </ProjectExtensions>
```

Most of that is unimportant - I just grabbed it from my csproj file.  The key bit is the `<servers>` node.  VS will then launch x64 IIS Express  (use `c:\program files (x86)\` instead if you want x86 IIS Express on x64 Windows).  Change the "url" attribute to suit too.

Open your csproj's properties.
Go to the "Web" tab
You should see the settings entered above reflected in the lower half of the tab in the "Servers" area.

Run your project using F5 or Ctrl+F5.

**Comment by qujck** [comment]
Thanks @IanYates

**Comment by merbla** [comment]
Thanks @IanYates I think I was missing the point from @qujck

**Comment by merbla** [comment]
@JohnyMac the Trace sink might work for you in WinForms
```
var log = new LoggerConfiguration()
    .WriteTo.Trace()
    .CreateLogger();
```

**Comment by JohnyMac** [comment]
Oh.. I didn't know Trace was supported, Thanks mate.
