### ISSUE TITLE
Could not load type 'System.Exception' from assembly 'Serilog, Version=1.5.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'

### ISSUE THREAD

**Issue by rajeshmuraleedharan** [serilog/serilog#606]
Hi I am getting "Could not load type 'System.Exception' from assembly 'Serilog, Version=1.5.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'" error when I deploy my MVC application to UAT server. It's working fine in my local and dev machine. But on UAT machine I am facing this error. Initially I thought it could be a .net framework issue and reinstalled .net 4.5 framework but no luck.
 
Following are the details
Server: Windows 2012
IIS: 8.0
Project Type: MVC (.net 4.5 framework)
Code where I initialize the logger
 Log.Logger = new LoggerConfiguration()
                          .MinimumLevel.Debug()
                          .WriteTo.Trace()
                          .CreateLogger();

Here is the trace config in web.config
<system.diagnostics>
    <trace autoflush="true" indentsize="4">
      <listeners>
        <remove name="Default"/>
        <add name="myListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="C:\Log\IdentityServer3.CustomUserService.log"/>
      </listeners>
![serilog](https://cloud.githubusercontent.com/assets/16232384/11702597/8fc93382-9e9d-11e5-9321-870fb5b85a4c.PNG)

    </trace>
  </system.diagnostics>

![Uploading Serilog.PNG…]()

**Comment by IanYates** [comment]
I've found similar weird things when having my main web site project reference some other projects in my solution and I haven't had my NuGet package versions in sync across the various projects.  If I built it funny then you'll get this sort of stuff. 

Other things worth checking
* Do you have any binding redirects in your web.config?  If so, what are they?
* Is the copy of Serilog.dll in your deployed copy actually what you expect it to be?  (compare to what's on your machine)
* Unlikely (since you'd probably crash earlier and you also mention 4.5 anyway) but is there a different version of .NET on your PC versus that in your UAT environment (eg 4.5 vs 4.5.1, 4.5.2, 4.6, 4.6.1)
* Is this happening on your very first web request or only on certain web requests?

**Comment by nblumhardt** [comment]
That's a very strange issue indeed! There may be some clues in your `Web.config` file, if you can post a redacted version of it?
