### ISSUE TITLE
Property Names with dashes/hyphens

### ISSUE THREAD

**Issue by colin-young** [serilog/serilog#642]
Doesn't appear to be supported well. If I do:

    _log.LogDebug("Added message {message-content}", message);

I get `Added message {message-content}` in my log message, but Seq will show a message-content property with the correct rendered value in the properties display.

I know there was another question about periods in the names and that those are not supported. Might be useful to update https://github.com/serilog/serilog/wiki/Writing-Log-Events with the rules for valid property names.

**Comment by nblumhardt** [comment]
Thanks for the note. This is probably worth a warning or deprecation of some kind in v2. It turns out that very few back-end storage options support dashed property names well. I'm not sure how to do that in a non-disruptive way; perhaps just making a note that "future versions won't support dashed properties" in the release announcement will cover it.

Updating the wiki now. Cheers!

**Comment by nblumhardt** [comment]
> Property Naming - Property names should use PascalCase for consistency with other code and libraries from the Serilog ecosystem.

> While accepted by Serilog, dashed-names are not compatible with many back-end data stores and so are strongly discouraged.

Perhaps that's enough for now; I'll close this but also make a note when we announce v2.

Thanks Colin!

**Comment by colin-young** [comment]
Thanks! That's exactly what I was looking for before I started to experiment with names.
