### ISSUE TITLE
Sink for Xamarin

### ISSUE THREAD

**Issue by tlhintoq** [serilog/serilog#647]
You have another project that is supposedly a sink for Xamarin for cross-platform use - but I for one can't figure out what to do with it or how to use it.  VS15 says there's no projects in the solution... There is no documentation... Bringing the .cs files to the respective platform projects doesn't let the PCL know they exist... A few breadcrumbs of help documentation would go a long way.

**Comment by nblumhardt** [comment]
Howdy - thanks for the note. Xamarin support is in need of some attention, as you've pointed out. In this case it is a bit painful because the Xamarin tools aren't readily available for CI, and very few of the Serilog developers (if any?) have Xamarin licenses. Ideally someone with a deeper interest in Xamarin could take some of this on.

**Comment by nblumhardt** [comment]
(Assuming this is https://github.com/serilog/serilog-sinks-xamarin)

**Comment by merbla** [comment]
Relates to #363

**Comment by nblumhardt** [comment]
I have updated the README of that project with the following message:

> This sub-project needs an active maintainer. Without an owner/owners who both have the knowledge and software licenses required to support Xamarin, we've been unable to move this forwards. Please raise an issue on the Serilog tracker if this is you :-)

https://github.com/serilog/serilog-sinks-xamarin
