### ISSUE TITLE
rate control in serilog-sinks-email

### ISSUE THREAD

**Issue by fabsenet** [serilog/serilog#653]
Hi,

I managed to send some 100k emails inside my company over the weekend because of an application continiously logging errors and errors are configured to yield emails.

What is the best practice here?

Should we implement some kind of rate control of not sending more than 10 emails in a time window of an hour or so?

**Comment by fabsenet** [comment]
see https://github.com/serilog/serilog-sinks-email/pull/13

**Comment by nblumhardt** [comment]
Thanks for the report and PR, sorry to hear about the mail flood :-|

Since email is one of several sinks that would benefit from rate limiting, what do you think about going in a slightly different direction with something like:

```csharp
Log.Logger = new LoggerConfiguration()
  .WriteTo.Console() // etc.
  .WriteTo.Logger(l => l
    .Filter.PerMinuteInExcessOf(100)
    .WriteTo.Email(...))
  .CreateLogger();
```

It's less obvious/ergonomic, but keeps each sink from eventually taking on a dozen different configuration options. Would love to hear your thoughts.

A slightly hacky version of the method is here: https://gist.github.com/nblumhardt/d3baa1ea511242951e78

**Comment by IanYates** [comment]
Clever approach - and I don't mean "clever" as in "obscure" or "tricky" as we so often mean in programming circles :)

I suppose emailing should be one of those rare things so it's probably limited to warnings or worse anyway, but since this is being applied generally, could it be useful to maintain multiple PerMinuteInExcessOf values for various levels of logging from verbose through to fatal?  That way error and  fatal could be set to perhaps 100, warnings at 10 and others at 1 or 2.  

I suppose someone could take this to the extra and use a Func<Message,GroupBucket> to really discriminate if it was so desired.  That's probably (and should be) rare but it could be used behind the scenes to implement the common simple API.

**Comment by fabsenet** [comment]
Okay I have thought deeply about it and discussed it with a colleage.

Your filter solution might be a clever implementation, but from my point of view, it is not very useful.

Consider the error log events e1...e1000 being generated.
My solution configured to max=3 mails will give you mails containing: e1, e2-e101,e102-e201. All others will be swallowed. I can trust the system that I really received e1..e201 without gaps.

The rate limiting solution from @nblumhardt will silently remove some messages from inbetween. If you want to analyse something from it, you never can be sure, there was something removed from inbetween. This gets worse times 10 with the suggestion from @IanYates to allow different rates for different error levels.

Something else: In my solution, if I want to get not more than 5 mails per hour, I simply put a 5 in right spot and I am done. If I want to archive the same thing using rate limiting, what rate do I have to choose? The best case is, you provide some kind of formula. But isnt the actual number dependant on the way the batching is implementes? 

I am going to test this next: From my observations, the first email only contains a single log event and after this, every mail contains 100 log events but what would happen, if I emit 2 errors and never ever emit anything again. will I receive the second email? In either way, this yields an interesting follow up question: If I allow only a really low rate of errors, will I either receive the second error mail way too late or will I receive many mails all with only one or two log lines? Both is not very desireable.

Last point is easy: Why is the rolling file sink allowed to have a parameter about how many files are okay while basically the same thing on the email sink is "too many configuration parameters"?

**Comment by fabsenet** [comment]
the rate limiting approach might be useful somewhere else.

Consider a class always emitting the timing of an executed operation but you really are not interested in every timing but you maybe want to see some timings now and then. There you could apply the rate limiting and would not need to change the actual emitting code.

**Comment by fabsenet** [comment]
okay i tested the batching part. It either batches 100 log events into one mail or it batches all log events from 30 seconds.
Even the lowest rate limiting would yield 120 mails/hour per server and process and also the lowest rate limiting would remove way to many events. I would basically get many thin mails instead of a low amout of full mails.

I hope, I got my point through by now.

**Comment by fabsenet** [comment]
I testest https://github.com/serilog/serilog-sinks-email/pull/13 to my best standards :smile: and we are running this now at our company as a kind of private fork.

**Comment by nblumhardt** [comment]
Hi Fabian, thanks for all the follow-up!

> Why is the rolling file sink allowed to have a parameter about how many files are okay while basically the same thing on the email sink is "too many configuration parameters"?

Sorry about the lack of clarity in my statement there. I meant to emphasise "different". The rolling file sink is the only one that stores a set of rolling files, so it makes sense that its implementation should be there.

All sinks could potentially benefit from rate limiting - networks can be saturated, databases can be filed, etc. - so having a consistent way to represent the limit among various sinks would have the benefit of consistency/predictability.

I think you make some good points on how the limiting might best work - sliding vs hopping window - but I think that's orthogonal to the API (we could use either rate limiting algorithm in either option).

Whether per-minute or per-hour is appropriate is also a variable, I see how per-hour is more useful in your case.

If the sliding window is used, it might be possible to use fractional per-minute or per-hour values to gain some flexibility.

Great discussion, will try to make some time to dig in deeper. @serilog/core any thoughts?

**Comment by nblumhardt** [comment]
Moved to: https://github.com/serilog/serilog-sinks-email/issues/14 (see #450)

**Comment by fabsenet** [comment]
I opened this issue in february together with a working pull request which would only require a click on the merge button. @nblumhardt had his own ideas about how to solve the issue and then .... nothing!

4 months have passed without any working solution for rate limiting in the nuget package. The risk to use the current package is not feasable and I am not sure, whether this will change or not. I am still using a private build of the email sink.

Did something happened in the meantime regarding rate limitation? what is the plan here?

**Comment by nblumhardt** [comment]
Hi Fabian,

I'm sorry to hear you have to maintain a forked version of the sink. This does illustrate the problem we both face though: you may not want to keep one version of this code working - I am hesitant to maintain a separate rate limiting implementation in 50 or more different Serilog sinks that could benefit from it, as I did my best to explain above.

Before opening a PR it's usually a good idea to [propose your changes first](https://www.igvita.com/2011/12/19/dont-push-your-pull-requests/); otherwise, it can take some extra effort for everyone to get on the same page.

If you're still interested in solving this one, do you think the rate limiting algorithm from your proposal could be wrapped up in a sink-neutral API? I think it'd be a great addition to the Serilog toolkit if so. If not, let me know why - I didn't mean to shut down this discussion by closing the issue, I'm just trying to keep the tickets for the various sinks in the corresponding trackers. Both the PR thread, and the new issue thread above, are still open.

Cheers,
Nick
