### ISSUE TITLE
Can you have optional properties control leading whitespace?

### ISSUE THREAD

**Issue by stajs** [serilog/serilog#663]
Firstly, love your work, thanks for sharing. Secondly, I apologise in advance for my whitespace OCD. I'm mainly asking with `RollingFile` in mind, but I think it applies to most sinks (at least `LiterateConsole`).

## Example 1

Say I have a template like this:

```
{SourceContext} {Message}
```

If I have set the context, I might get this output:

```
SomeClassName Awesome message.
```

If I have **not** set the context, I might get this output:

```
 Awesome message.
```

Note the leading space, which I would like to avoid.

## Example 2

Say I have a template like this (because I want to make it easier to scan the source vs the message):

```
<{SourceContext}> {Message}
```

If I have set the context, I might get this output:

```
<SomeClassName> Awesome message.
```

If I have **not** set the context, I might get this output:

```
<> Awesome message.
```

I would like to avoid the empty `<>`.

## Relevant

- How to conditionally emit the property - https://github.com/serilog/serilog-extensions-logging/issues/9
- Closed PR that floated the idea of controlling whitespace for optional properties - https://github.com/serilog/serilog/pull/66

**Comment by stajs** [comment]
## Strawman

Being totally ignorant of your internal implementation of these format strings, as a user I'd like _something_ like this:

```
{SourceContext:<{0}> | }{Message}
```

... to output this, if context is set:

```
<SomeClassName> | Awesome message.
```

... and this, if context is **not** set:

```
Awesome message.
```

Note, no leading space.

**Comment by nblumhardt** [comment]
Thanks @stajs. OCD is a valuable trait in an API designer, in my humble opinion :-)

I don't think Serilog's current output templates are going to be able to cover this - diverging too far from .NET standard format string compatibility will get hard to manage and will seem unpredictable to newcomers. Currently the format strings work identically to .NET's `{0} {1}` strings, with named "hole" support being the only twist.

However.... all of this is handled via `ITextFormatter`, a public interface that most sinks support (at least internally) in order to switch between human-readable and JSON output. The most common use of this is to write JSON to log files.

Would implementing an alternative language entirely for this task be reasonable? I.e. `HandlebarsTextFormatter` could be used as an output formatter and thus support all manner of conditional goodies. A simpler syntax implemented e.g. with Sprache might also work.

Currently you can plug this in as:

```
.WriteTo.Sink(new RollingFileSink(..., outputFormatter: new HandlebarsTextFormatter("{{SourceContext}} {{Message}}")))
```

In the long run a nicer way of plugging it in would be desirable, but to kick the tires and try out some concepts independently you (or someone keen) could publish this as a separate NuGet package today and get some feedback.

Just a thought, anyway!

Thanks for weighing in, keen to hear what you think.

**Comment by stajs** [comment]
I see what you did there ;P

I might be able to find some tire-kicking time in a few weeks. Also, I've found myself now preferring to use the new string interpolation format (`$"Some inserted {(var.HasValue ? var : string.Empty)}."`). So I'm wondering how the new format could possibly play nice with the classic `{0}` positional holes.

**Comment by nblumhardt** [comment]
Let me know if you ended up getting traction with this; closing as it's been a while. Thanks for the original suggestion!

**Comment by stajs** [comment]
TBH, life got in the way and I forgot all about this. Sorry to leave it hanging.

**Comment by nblumhardt** [comment]
@stajs no worries at all, thanks!

**Comment by bonesoul** [comment]
@stajs can you post your final template string with your last "some inserted value" example?

**Comment by stajs** [comment]
@bonesoul I'm sorry mate, but I didn't end up doing anything. :(
