### ISSUE TITLE
LogEvent aggregator / advanced filtering

### ISSUE THREAD

**Issue by vradzius** [serilog/serilog#664]
Hello,

I need to log only when exception occurs some log entries till debug level, after and before occurance How better to implement that?

I tried implementing my own aggregating sink which uses other sinks, but got problem accessing them as many sinks classes is not public. So I cannot construct them to pass to my aggregating sink.

Copy those other sinks implementation to my project is not a long term solution.

Any help welcome.

**Comment by IanYates** [comment]
Maybe instead of doing it at the sink level you could write your own ILogger instead?  To keep things simple (for some definition of simple) you could log to an RX observable  (I myself just did this last week in LinqPad and it worked really well).

From the observable you could use some RX operators to do things like buffer or delay your observable stream of events and unleash the buffered/delayed stream when the main stream gets a log event with warning/error/fatal level.  After X events or Y seconds pass you could then close the tap on the buffered/delayed stream.

All the while you're still subscribing to your main observable and forwarding on those log events to another Serilog logger which is actually wired up to various sinks.

There's a bit of experimentation to be done with regards to enrichers (you'd need them to apply before log events hit the observable) but the general idea is fairly sound.

Of course if you're unfamiliar with RX then you could code the buffering by hand without too much effort but it'd be harder to change (X number of events, Y seconds of events, etc - easily composed with RX but harder with timers and manually managed lists).

The key thing here is that you can have one Serilog pipeline configured to write to another Serilog logger.  This is a handy extension point to use for your buffering.

**Comment by IanYates** [comment]
See https://groups.google.com/forum/#!topic/serilog/TVZZDCtvwdE for another use case of loggers writing to other loggers
