### ISSUE TITLE
CLS compliance lost after move to DNX

### ISSUE THREAD

**Issue by jonorossi** [serilog/serilog#687]
The `CommonAssemblyInfo.cs` file was updated to include the `CLSCompliant` attribute in #538 and #542, however with the move to DNX this file got dropped.

I noticed this trying to make `Castle.Services.Logging.SerilogIntegration` CLSCompliant on .NET Core using Serilog 2.x beta.

Would you take a PR to add the file back with a single line?

**Comment by nblumhardt** [comment]
Hi Jonathon,

Yes, this sounds fine. We're in the process of breaking all of the individual projects out of this repo however, so adding the attribute to `AssemblyInfo.cs` might be preferred, since there won't be a reason for a "common" file in the future.

(@khellang has done the most work in this area so could spot something I'm missing here.)

Cheers,
Nick
