### ISSUE TITLE
Exception StackTrace information sometimes missing

### ISSUE THREAD

**Issue by patrick-steele** [serilog/serilog#701]
Just installed Serilog version 1.5.0.0 from nuGet along with Seq and I'm seeing an issue similar to one from last year reporting [missing stack trace information](https://github.com/serilog/serilog/issues/399).

This is just a simple console app that I'm playing around with to see Serilog's capabilities.  After messing with this I finally found that it seems to lose the stacktrace information if I **don't** pause the application before it closes.

Here's my sample code:

	class Program
	{
		static void Main(string[] args)
		{
			Log.Logger = new LoggerConfiguration()
				.WriteTo.ColoredConsole()
				.WriteTo.Seq("http://localhost:5341")
				.CreateLogger();

			var pause = false;

			try
			{
				throw new ArgumentNullException("oops");
			}
			catch (Exception ex)
			{
				//Log.Information("Stack trace: {StackTrace}", ex.StackTrace);
				Log.Error(ex, "Got an error with pause = {Pause}", pause);
			}

			if (pause)
			{
				Console.WriteLine("Press any key...");
				Console.ReadKey(true);
			}
		}
	}

If I run it with `pause = false`, I don't get my stack trace information in the error message.  If I run it with `pause = true` (and it sits for a second or so after I see the "Press any key" prompt), then I'll see the stack trace information in the error message.

I'm wondering if this is just a rare race condition and the AppDomain is shutdown before serilog has a chance to grab the stack trace information.

**Comment by nblumhardt** [comment]
Thanks for the note Patrick! I am not sure Serilog is involved in this, because of the order things occur in. Here's the way things look in sequence:

1. Exception is thrown
2. Log event is created
3. (Background thread) exception is converted to a string with `.ToString()`
4. HTTP request with JSON is sent to Seq
5. Everything unloads

This points to some kind of problem in how `Exception.ToString()` captures its stack trace information - perhaps during appdomain unload, something that's assumed to be available from the background thread no longer is?

Just clutching at straws - I'm not aware of any way to "fix" exception details on one thread before passing it to another - would you mind try running `Console.WriteLine(ex.ToString())` _before_ calling the `Log` method in each scenario and see whether the behaviour changes?

Many thanks!

**Comment by nblumhardt** [comment]
(When I say "involved" I mean directly responsible for it - if there's a way we can work around whatever triggers this then it's fair game! :-))

**Comment by patrick-steele** [comment]
Thanks for the follow-up Nicholas.  The `Console.WriteLine(ex.ToString())` didn't change the behavior at all.  I did notice that when `pause = true`, if I hit the ENTER key quick enough, I won't get stack trace information so I definitely think it's related to the Application/AppDomain being shutdown before the stack trace information is obtained.

Anyway, it's probably a rare condition that wouldn't normally occur in a production environment.  Thanks!
