### ISSUE TITLE
Setting up Serilog when running unit tests?

### ISSUE THREAD

**Issue by jansoren** [serilog/serilog#703]
Is there a good way to set up Serilog when running unit tests so that they does not fail because of the logger? Preferable a way that I do not have to do every time I create a new unit test for my application.

**Comment by nblumhardt** [comment]
Hi Jan,

What kind of failure do you mean? Just leaving Serilog uninitialized should do what you need.

Regards,
Nick

**Comment by jansoren** [comment]
Excellent! I see that I get a SilentLogger. Is it possible to get it to always log to console, because most likely i've forgotten to configure the logger or I am in a unit test.

**Comment by nblumhardt** [comment]
```csharp
Log.Logger = new LoggerConfiguration().WriteTo.Console();
```

Done! :-)

**Comment by jansoren** [comment]
Superb :+1: 

I solved it like this:
```
if (Log.Logger.GetType().FullName == "Serilog.Core.Pipeline.SilentLogger")
{
  Log.Logger = new LoggerConfiguration().MinimumLevel.Debug().WriteTo.ColoredConsole().CreateLogger();
  Log.Logger.Debug("Logger is not configured. Either this is a unit test or you have to configure the logger");
}
```

Thanks mate :-)

**Comment by MitchBodmer** [comment]
I'm going to hijack this because it's the first Google result for "unit testing Serilog". If you're interested in unit testing your Serilog log output you can use the [TestCorrelator sink](https://github.com/Microsoft/serilog-sinks-testcorrelator)!

**Comment by Sigvaard** [comment]
@MitchBodmer Don't wanna be offensive, but why someone would want to test log output?

**Comment by MitchBodmer** [comment]
@Sigvaard no offense taken! It's a fine question.

**The short answer:**

To prevent regressions!

**The long answer:**

Often the nature/frequency/content of the log output your application produces is important enough that it's worthy of protecting with an automated regression suite. You may want to ensure that the right errors are produced by mission critical systems for alerting purposes, or just prevent yourself from overrunning a rate limited document database. In any case, having a way of checking that the log output you expect is produced can be very useful.

You could, of course, do something like writing to a file and then parsing that file to ensure it contains the elements you need. Unfortunately that method is often both arduous and fragile, requiring file IO in each test and breaking if the log format changes in a way that doesn't actually violate the business requirement.

Additionally if you've made the choice, as many Serilog users have, to use a global logger instead of passing an ILogger to every class that produces log output, you might face an additional challenge as you try to parallelize your tests. Since each class will be writing to the same logger, they will likely overwrite each other's logs and logger configurations leading to non-determinism in your test suite.

The sink above is a way of solving those problems, and providing you a way to get the fully structured log events from Serilog that we all love so much. That way you can more easily assert on properties of the event like level and timestamp and more intelligently look at the values of the properties you're interested in. No parsing required!

**Comment by cohen990** [comment]
In my case, I need to test to verify that sensitive data is not being pushed to our log aggregator

**Comment by micktion** [comment]
> @MitchBodmer Don't wanna be offensive, but why someone would want to test log output?

You're unit testing code which has components which inject the logger and log stuff?
