### ISSUE TITLE
When will Serilog 2.0.0 be released?

### ISSUE THREAD

**Issue by jansoren** [serilog/serilog#713]
Does anyone know when Serilog 2.0.0 will be released?

**Comment by khellang** [comment]
Hey @jansoren!

There are already quite a few pre-releases of 2.0 out on [NuGet.org](https://www.nuget.org/packages/Serilog):

![image](https://cloud.githubusercontent.com/assets/582487/14425833/7e40655a-ffea-11e5-8716-4a0b6cb9d8c2.png)

Because we're moving to also support .NET Core, we probably won't release anything "stable" until .NET Core RTM.

Is there anything particular you need from 2.0?

**Comment by jansoren** [comment]
I am using serilog-sinks-mssqlserver that gives an error when using Serilog 2.0.0. I have created a pull request that fixes this error (https://github.com/serilog/serilog-sinks-mssqlserver/pull/18), but they do not want to accept it before Serilog 2.0.0. is released with a stable version. I will ask them kindly to consider a beta version :-)

**Comment by nblumhardt** [comment]
Hopefully the RC2 version will bring us close to a complete/production-ready set of beta packages.
