### ISSUE TITLE
Dynamically adding / removing loggers....

### ISSUE THREAD

**Issue by natiki** [serilog/serilog#714]
Hi,

I am planning to use Serilog in an MVC application where by default I want to log to a SQL Server database. However there are times when I want to also do some UDP broadcasts when tracking down an issue while the website is running and I am logged into the webserver machine.

So while it seems pretty straight forward to add a logger at applicaiton startup:

```c#
var log = new LoggerConfiguration()
    .WriteTo.ColoredConsole()
    .CreateLogger();
```

are there any recommended approaches to vary the log sinks being written to? My plan is that I can hit a specific controller which reads some configuration data from somewhere and then reconfigures the logger. Now while I can blow away the previously created log configuration I am unsure what would happen while this is happening and other requests are coming in.

Can you recommend an approach?

**Comment by IanYates** [comment]
Loggers can write to other loggers - see https://github.com/serilog/serilog/wiki/Configuration-Basics#sub-loggers

So you can have your occasional UDP logger set up as another sink to which your main logger sends events.

Combine that with http://nblumhardt.com/2014/10/dynamically-changing-the-serilog-level/ and you can turn the UDP tap on or off as required (by changing its level to fatal or some more permissive level).  

I don't think there's a way to have the sink completely disabled  on demand.  If I had to do that today, and in a jiffy, I'd probably pipe it through a small RX observable where I could filter in there myself and have the RX pipeline end up back at the UDP logger.  

(side note: that's handy for use in something like LinqPad anyway where it knows how to dump RX observables.  If running via the command line you instead set up the Serilog pipeline to go to Seq instead of RX).

**Comment by natiki** [comment]
@IanYates Thanks for the pointers. Unfortunately the built in stuff won't really help. 

Once the logger is created via CreateLogger() it cannot be "modified". So whether the UDP logger is a sub logger or configured as part of the main logger they both have to be scaffolded at time of the logger construction.

And the serilog level is global so when you mess with that you may lose logs elsewhere depending on how the permissions have been set up.

I took your suggestion about Rx and did something similar for our implementation. As we have a configuration store I can detect changes in there and when a log request is invoked we spin up the new logger configuration before writing to it (based on the settings). In this way we can have various logging levels per sink as needed, never have to touch the global level. 

From a performance perspecitve in our web app we can still configure the logger "once" and store it globally and use for subsequent requests without the cost of spinning it up each time. We lock access to the log singleton and only rebuild it if we detect a configuration change eg. Turn UDP On, Turn Email Off etc.

**Comment by bhalbright** [comment]
I liked IanYates suggestion to use sub-loggers and logging level switch but I didn't find a simple example (maybe I didn't look hard enough). So I made a simple example, hopefully it is helpful (and correct):

```cs
var jsonLevelSwitch = new LoggingLevelSwitch(LogEventLevel.Information);
var textLevelSwitch = new LoggingLevelSwitch(LogEventLevel.Error);
var config = new LoggerConfiguration()
	.MinimumLevel.Verbose()
	.WriteTo.Logger(lc => lc
		.WriteTo.File(new RenderedCompactJsonFormatter(), Path.Combine("logs", "log_json.json"))
		.MinimumLevel.ControlledBy(jsonLevelSwitch))
	.WriteTo.Logger(lc => lc
		.WriteTo.File(Path.Combine("logs", "log_txt.log"))
		.MinimumLevel.ControlledBy(textLevelSwitch));

Log.Logger = config.CreateLogger();
Log.Verbose("Test verbose message 1");
Log.Debug("Test debug message 1");
Log.Information("Test info message 1");
Log.Warning("Test warning message 1");
Log.Error("Test error message 1");
Log.Fatal("Test fatal message 1");

jsonLevelSwitch.MinimumLevel = LogEventLevel.Verbose;
textLevelSwitch.MinimumLevel = LogEventLevel.Fatal;

Log.Verbose("Test verbose message 2");
Log.Debug("Test debug message 2");
Log.Information("Test info message 2");
Log.Warning("Test warning message 2");
Log.Error("Test error message 2");
Log.Fatal("Test fatal message 2");
```
