### ISSUE TITLE
IDestructuringPolicy for Exceptions

### ISSUE THREAD

**Issue by alex-y-su** [serilog/serilog#78]
As improvement it would be nice to run Exception serialization through collection of registered IDestructuringPolicy or special sort of destructing handlers.
Often we have business exception with extra fields which should be written: like ticked id or current user identity. Now we have to write this code to run business exception over destructing policies:
Logger.Error("An error intro {@exception}", exception);
Let me know if this sounds reasonable and I will try to implement it myself as a pull request.

**Comment by RehanSaeed** [comment]
@nblumhardt's implementation was good but I modified it to only use the reflection based destructurer if a custom one was not available. This should give better performance in the majority of cases. Perhaps this should be it's own Serilog Git repository.

https://gist.github.com/RehanSaeed/108baa92d459fc9cff35

**Comment by RehanSaeed** [comment]
There is a very good implementation I discovered [here](https://groups.google.com/forum/#!searchin/getseq/enhance$20exception/getseq/rsAL4u3JpLM/PrszbPbtEb0J). However, you had to choose between creating custom exception destructurers and a reflection based version.

I improved it slightly so it can use a custom destructurer if one is available or otherwise fallback on the reflection based one. This should give better performance. https://gist.github.com/RehanSaeed/e06374c06d06312b836d

Perhaps this should be a new Serilog Git repository? Ideally, this should be built in and enabled by default.

**Comment by nblumhardt** [comment]
Great gist! If you are interested in shipping and maintaining it, perhaps we could add a repo under https://github.com/destructurama ?

**Comment by RehanSaeed** [comment]
Sure, why not.

**Comment by RehanSaeed** [comment]
Started [here](https://github.com/RehanSaeed/Serilog.Exceptions).

**Comment by IanYates** [comment]
@RehanSaeed  - nice :)
