### ISSUE TITLE
Seq sink stops logging when Exception.ToString() throws

### ISSUE THREAD

**Issue by sebwerner** [serilog/serilog#793]
![u2exception](https://cloud.githubusercontent.com/assets/2035113/16402366/e3e75466-3ca0-11e6-8a7e-fa41bd57ba26.JPG)
if the exception.message throws an error, Serilog stops logging all further log requests.

**Comment by nblumhardt** [comment]
Hi Sebastian,

Thanks for the report. Which sink are you using? Does logging fail for subsequent `Log` statements, or just the current event (which would be #500 )?

Cheers!
Nick

**Comment by sebwerner** [comment]
Hi Nick,

I'm using seq as a sink. All subsequent logs fail. In my case I tried to log it as an error and return a 500. I checked in fiddler and notices that serilog stops sending messages to see after it encountered the exception shown above.

Thanks,
Sebastian

**Comment by nblumhardt** [comment]
Thanks Sebastian. Guessing this will be a bug in Serilog.Sinks.Seq, or Serilog.Sinks.PeriodicBatching. I'll have to take a quick look to work out where to move/fix the issue. On vacation this week so apologies for the slow turnaround, will jump straight on it when I'm back if no one spots the issue first :-) Cheers!

**Comment by nblumhardt** [comment]
Hi Sebastian,

I've had a look at this - I think the logging _should_ eventually kick off again, though the batch will be lost and since it grows in the process, will probably mean all of the events from when the issue occurs through about 10 minutes into the future will disappear.

I'm going to look at addressing this in the Seq sink itself - if JSON conversion fails, we'll just write to SelfLog and move on.

**Comment by sebwerner** [comment]
Thank you. You should not work on 4th of July;)

**Comment by nblumhardt** [comment]
https://www.nuget.org/packages/Serilog.Sinks.Seq/2.0.1-dev-00065 contains the fix, if you have a chance to check it out to make sure it hits the mark that'd be great. I'll push it through to master later in the week, all else being equal.

Have a great day off! :-)
