### ISSUE TITLE
Request to create a new Sink Repo for ReflectInsight

### ISSUE THREAD

**Issue by codematrix** [serilog/serilog#796]
Hi Team,

Initially, we had our own repo to support Serilog implementing our own sink . After speaking to the ReflectSoftware Team and @nblumhardt , it seemed logical and probably best, to put the ReflectInsight sink (**serilog-sinks-reflectinsight**) to where it belongs best - the Serilog project.

It would be great if the Serilog Team can create a new repo (i.e. **serilog-sinks-reflectinsight**) so that we can contribute to the Serilog project. We understand that we will be fully responsible to maintain the repo and that we will follow any guidelines set forth by the Serilog Team.

Thanks,

Ross Pellegrino
cc @calloncampbell

**Comment by nblumhardt** [comment]
Hey Ross! Thanks for the note.

The smoothest way to do this is usually to stand the repository up under your own organisation, add the code, build scripts and so-on, and then let us know when it is ready to transfer across (GitHub allows you to do this under the repository settings). Since many of us "watch" every repository under the Serilog organisation, taking this route keeps distractions to a minimum while the nuts and bolts are put together.

Regarding project structure, [Serilog.Sinks.File](https://github.com/serilog/serilog-sinks-file) is the best starting point at present. We have some tech debt left from the .NET Core release that will cause a bit of churn in our build system, but mirroring what we have in _s.s.File_ will minimise this.

Sounds like a plan?

Cheers,
Nick

**Comment by calloncampbell** [comment]
Hi Nick,
We have completed the work for this sink and I have a couple questions:
1. What is the process for getting the build setup on the Serilog AppVeyor account? 
2. What is the process for the NuGet package and API key?

Is this something you take care of once we transfer the repository?

Cheers,
Callon

**Comment by nblumhardt** [comment]
Hi Callon,

Yes, if you just grab the Build.ps1 and appveyor.yml from the repo mentioned above, the build should "just work" once we've moved the repository (I'll point appveyor to it then).

If the package has already been published, you'll need to add the `serilog` user on NuGet as an owner before publishing will work.

Cheers,
Nick

**Comment by calloncampbell** [comment]
Hi Nick,

Ok I've updated the Build.ps1 and AppVeyor.yml files and everything is building as expected. Question about AppVeyor.yml file, there is a nuget API key reference. Do I leave this as is or update it with our key? Also what is the process for publishing the nuget package? Is that done manually by us or through AppVeyor?

We publish our other nuget packages through AppVeyor so just wondering how this would work when the repos moves under Serilog.

Cheers,
Callon

**Comment by nblumhardt** [comment]
Leaving the keys as-is will cause the CI process to publish the package automatically.

Can you post a link to your work-in-progress repo BTW? Cheers!

**Comment by calloncampbell** [comment]
Thanks Nick. Here is link to our repository https://github.com/reflectsoftware/serilog-sinks-reflectinsight

Let us know if you have any feedback. We should be ready by end of the week to change the ownership.

Cheers
Callon

**Comment by calloncampbell** [comment]
Hi Nick,

We're ready to change ownership to Serilog. Can you also invite my colleague @codematrix to the group. Thanks.

Cheers,
Callon

**Comment by nblumhardt** [comment]
Looking good! The Build.ps1 and appveyor.yml are a fraction out-of-date; the ones in https://github.com/serilog/serilog fix some issues and include a new publishing key. We can fix that up any time between now and turning on the CI however.

Setting up the reviewers team now.

To do the transfer (I discovered this doing https://github.com/influxdata/influxdb-csharp) you need to send it to me personally (`nblumhardt`) so that I can add it to the org. Sending it to the org directly will fail IIRC.

Cheers!

**Comment by calloncampbell** [comment]
Ok I updated the Build.ps1 and AppVeyor.yml files.

**Comment by nblumhardt** [comment]
Hey guys, any update on this? Cheers!

**Comment by calloncampbell** [comment]
Nick,
Currently we have a sink for the Serilog Core project and now we’d like to add another project to support the full .NET Framework. I’ll try to get this done in the next day or two. 

Do you have guidelines for non CORE projects (build, layout, etc)?

If you want to proceed with the ownership transfer now we can do that, otherwise we can wait until we get the full framework project up and building. 

Thanks
Callon

**Comment by nblumhardt** [comment]
Hey Callon - looking good. Only one thing I noticed - the version number in project.json needs a trailing `-*`, e.g. `2.0.0-*`, in order for the build script to write the correct branch-specific suffix in there.

**Comment by calloncampbell** [comment]
Hi Nick,

Ok I made the version number change to project.json, added a sample project and published the nuget package for "Serilog.Sinks.ReflectInsight".

Should be ready to migrate over to Serilog. Let us know next steps.

Callon

**Comment by nblumhardt** [comment]
Great - thanks; in the repository, under Settings, you'll find "Transfer Ownership". As mentioned above you'll need to send it to `nblumhardt` rather than the Serilog organisation directly.

**Comment by calloncampbell** [comment]
Having trouble transferring the repository and getting the following error: "You can only transfer a repository from an organization to yourself at this time". 

Doesn't look like I can transfer the repository from our org account to you. I also tried to transfer to my personal account and then to you and same error.

Thoughts?

**Comment by nblumhardt** [comment]
Hi Callon; I can only find the info here: https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/

If that doesn't help, perhaps we side-step it and I create a repository here for you, that you can then copy and commit the code into? I can't imagine there's a lot of history to lose at this point.

Happy to work through doing it either way, let me know what you think.

Cheers,
Nick

**Comment by calloncampbell** [comment]
Hi Nick,

That article you sent https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/ helped.

Looks like the ownership transfer is working now. You should receive email confirmation or something like that.

**Comment by nblumhardt** [comment]
Done and done!

https://github.com/serilog/serilog-sinks-reflectinsight

Build is operational here:

https://ci.appveyor.com/project/serilog/serilog-sinks-reflectinsight

I've just kicked off a build, which failed on GitHub tagging (I need to update some perms) but the package was pushed successfully. I'll jump in now and create a `dev` branch as well so that everything stays sane when PRs arrive.

Cheers!
