### ISSUE TITLE
serilog 2.0 and quartz.net exception

### ISSUE THREAD

**Issue by agonzalezm** [serilog/serilog#802]
I have updated to serilog 2.0 and now get an exception in Quartz, any workaround or fix for it? It was workfin fine with 1.5

Method 'ForContext' in type 'Common.Logging.Serilog.SerilogInstanceWrapper' from assembly 'Common.Logging.Serilog, Version=3.1.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Common.Logging.Serilog.SerilogFactoryAdapter.GetLogger(Type type)
   at Common.Logging.LogManager.GetLogger(Type type) in c:\_oss\common-logging\src\Common.Logging.Portable\Logging\LogManager.cs:line 422
   at Quartz.Impl.StdSchedulerFactory..cctor() in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\StdSchedulerFactory.cs:line 135

**Comment by IanYates** [comment]
Very similar to #801 except this is for Common.Logging instead of NLog.  I saw another issue at Hangfire a few minutes ago (I'm catching up on my GitHub tracker subscriptions!) where LibLog is choking on Serilog 2.0 as well (https://github.com/HangfireIO/Hangfire/issues/606)

I'd give it a couple of weeks whilst .NET Core settles and everyone gets their packages in alignment.  Of course, I haven't checked the common.logging repo - they may well have a new version you can already fetch to fix this.

**Comment by agonzalezm** [comment]
No, common.logging version is the same i was using before.

I am not using .NET Core, just 4.5.1.

I reverted back to serilog 1.5.14 and everything works fine.

**Comment by nblumhardt** [comment]
Here is the PR on Common.Logging.Serilog: https://github.com/CaptiveAire/Common.Logging.Serilog/pull/16

Cheers,
Nick

**Comment by nblumhardt** [comment]
Common.Logging.Serilog 4.x should fix this: https://ci.appveyor.com/project/Jaben/common-logging-serilog/build/4.0.10
