### ISSUE TITLE
Support interpolated strings

### ISSUE THREAD

**Issue by togakangaroo** [serilog/serilog#810]
When you do `$"Hi there, {foo}"` that is not actually a string type but an implicitly convertible [FormattableString](https://msdn.microsoft.com/en-us/library/system.formattablestring(v=vs.110).aspx). If all the Serilog logging methods did not force the implicit conversion, instead offering an override that took the `FormattableString` directly, you could use interpolated strings for logging and still get structured output.

**Comment by nblumhardt** [comment]
Thanks for the suggestion. Unfortunately, usin:

```csharp
Log.Information($"Hi there, {foo}");
```

would produce less useful events than:

```csharp
Log.Information("Hi there, {Name}", foo);
```

since the first example does not name the property (it's just the generic `0`), while the second, does. For that reason we'd still encourage using the message template-based API, so adding additional support for `FormattableString` would probably just cause confusion.

**Comment by nblumhardt** [comment]
Hi @togakangaroo - thanks again for the suggestion. Closing as I don't think we'll head in this direction, but please do let us know if you think there's something I've overlooked.
