### ISSUE TITLE
Dual licensed (BSD)

### ISSUE THREAD

**Issue by 304NotModified** [serilog/serilog#822]
At NLog we really like to use the [C# implementation of Message Templates](https://github.com/messagetemplates/messagetemplates-csharp), which got extracted from this wonderful library. 

The NLog library is published under BSD and AFAIK we can't use Apache dependencies, at least not for the users who don't could use Apache licenced libraries. 

Is there a possibility to release the Message Templates as dual licensed? (Apache & BSD)? I could image this is too much to ask, just let me know!

**Comment by nblumhardt** [comment]
Hi Julian, thanks for getting in touch.

I'm not enthusiastic about pursuing dual licensing; because there are multiple contributors who'd need to agree, licensing changes aren't straightforward, and it would take some careful analysis that I am short on time for....

But, I'd love to be able to help. `messagetemplates-csharp` has a parser implementation but also the whole Serilog capturing machinery in there. I can't see NLog using the full data model (`LogEventPropertyValue` and friends) as-is, so is the parser the main piece that would be of benefit to you?

I've worked with the code enough to be able to put together a clean-room parser (roughly, the `MessageTemplateParser` class) without a huge amount of effort and would happily contribute such a thing to NLog under the BSD license.

At the NLog end, you'd then need to figure out the mechanics of taking a template plus a list of arguments and binding them into property values, and some support for rendering a template back out to text again (for console display and so-on).

What do you think?

Cheers,
Nick

**Comment by 304NotModified** [comment]
Hey Nick,

> I'm not enthusiastic about pursuing dual licensing; because there are multiple contributors who'd need to agree, licensing changes aren't straightforward, and it would take some careful analysis that I am short on time for....

Sure, no problem. I have to admit that changing the license of NLog itself would be also difficult. 



> But, I'd love to be able to help. messagetemplates-csharp has a parser implementation but also the whole Serilog capturing machinery in there. I can't see NLog using the full data model (LogEventPropertyValue and friends) as-is, so is the parser the main piece that would be of benefit to you?

Yes we need mostly the parser. 

> I've worked with the code enough to be able to put together a clean-room parser (roughly, the MessageTemplateParser class) without a huge amount of effort and would happily contribute such a thing to NLog under the BSD license.

Thanks(!) for the generous offer! I will create a new repository and will start there a new basic parser. Will be great to help me with the details :) :+1: 




> At the NLog end, you'd then need to figure out the mechanics of taking a template plus a list of arguments and binding them into property values, and some support for rendering a template back out to text again (for console display and so-on).

Luckily  that's an easy task for me :)



> What do you think?

Sound all great. I will close this GitHub issue as the license will not changed. This week I will create a new repository and put some basic parser and integration code into it. Will notify you when that's done.

One question, the unit test cases, is that a part I could copy so I'm sure the new implementation woud behave the same as the current one?

**Comment by nblumhardt** [comment]
Great! Let me know when there's a place to discuss the new parser, I have a few ideas to add :-)

The tests are also multi-contributor and covered by Apache 2, but perhaps you can use Apache 2 code in your test harness, as long as it's not going into the shipped binary? Not sure here either, sorry.

I would be inclined to come up with a declarative way to represent the tests anyway, so perhaps the same essential test cases could be written as one large data-driven spec? Happy to help with this also.

Cheers!

**Comment by adamchester** [comment]
I'd be happy to help with tests too, the F# impel had few tests not in serilog or C# versions too.
