### ISSUE TITLE
Improve MessageTemplateCache performance

### ISSUE THREAD

**Issue by DmitryNaumov** [serilog/serilog#823]
Next thing which shows up in our multi-threaded logging scenarios is contention in MessageTemplateCache. The problem is that on every Parse (which is always on hot path of Logger.Write) lock is taken even if parsed message template is in the cache. I suggest switch to ConcurrentDictionary and can submit a PR.

Also for the interned strings this optimization makes no sense, imo, as they're already in memory:
```
            if (messageTemplate.Length > MaxCachedTemplateLength)
                return _innerParser.Parse(messageTemplate);
```
So converting to
```
            if (messageTemplate.Length > MaxCachedTemplateLength && string.IsInterned(messageTemplate) == null)
                return _innerParser.Parse(messageTemplate);
```
may improve performance to those who use large message templates.

P.S. Why DateTimeOffset.Now is used as timestamp of LogEvent? Why not UtcNow? What if destination sink (like Seq) is located in different timezone, collecting log events from two or more different locations? As I understand now events happened in different locations but in the same time won't show in Seq near each other. But I may be wrong, which happens often :)

**Comment by nblumhardt** [comment]
Hey @DmitryNaumov, thanks for writing this up. I've been thinking about this contention point as well and would definitely appreciate a PR that improves performance.

`ConcurrentDictionary` sounds like one reasonable option, though it incurs quite a bit more latency than `Dictionary` IIRC. If you are keen to PR it up, would you be able to add to `Serilog.PerformanceTests` so that we can measure the difference between the implementations in both a single-threaded as well as a high-contention scenario?

Regarding `DateTimeOffset.Now` - it's used because it makes the naiive `logEvent.Timestamp.ToString()` call show in the current time zone by default. Sinks like Seq that use timestamps either use ISO 8601 format, which includes the offset and so gets converted correctly to UTC for storage (Seq is all UTC internally) or in a few there's a UTC conversion done before sending the event out on the wire. If I could go back in time I'd probably give `DateTime.UtcNow` preference, but the current scheme's doing the job :-)

**Comment by nblumhardt** [comment]
Just adding a couple more thoughts:

 * Could we switch to a much smaller per-thread cache (e.g. `[ThreadStatic]`) to achieve zero contention?
 * If the cache was per-thread, a circular buffer of up to 10 items would have similar performance to a dictionary lookup
 * If the cache was per-thread it'd tend to perform better when different threads are doing different things in tight loops
 * Could we win some performance back by optimising the parser? E.g. get rid of more allocations, switch to using a single discriminated-union `struct` instead of `TextToken` and `PropertyToken` that could be converted to the existing `class`es lazily to maintain compatibility?

I'd guess there's quite a bit to win by reexamining the overall approach, what do you think?

**Comment by DmitryNaumov** [comment]
@nblumhardt it's just my gut feeling but I don't think many applications using serilog would benefit from per-thread caching, just because usually 99.9% (imo) apps don't care about thread affinity. So I would start with ConcurrentDictionary just to remove readers contention.

Now about parser. Of course we need to optimize it, but I assume in most cases it parses every template once and then it is in the cache. Unfortunately the real life behavior can be different. Have you thought about performance counters or anything else to be able to collect stats on, for example, template cache hit/miss ratio?

**Comment by nblumhardt** [comment]
:+1: 

The one stumbling block for a "simple" `ConcurrentDictionary` port should be: https://github.com/serilog/serilog/blob/dev/src/Serilog/Core/Pipeline/MessageTemplateCache.cs#L60

`Count` is hugely inefficient in `ConcurrentDictionary`. Guessing we can work around this however.

Performance counters are interesting but a lot of fiddly work that I'm not excited about at this point :-) Perhaps extending `SelfLog` in such a way that various metrics collectors (or perf counters) could be plugged in would have less initial overhead? E.g. `SelfLog.Count("MessageTemplateCache.Hit")` and a matching plug-in provider interface.

As a way of getting this kicked off, perhaps the first step here is to get some benchmarks added for message template parsing in a variety of straight-line scenarios, and some concurrent/contended ones?

**Comment by DmitryNaumov** [comment]
@nblumhardt You're right, there are many surprises in CD after generic Dictionary, like cost of accessing Count, Keys/Values etc, I will be careful. But let me start with performance tests to practically demonstrate the problem of contention, if any :)
