### ISSUE TITLE
[dependency injection] support for unity

### ISSUE THREAD

**Issue by adrien-rose-cko** [serilog/serilog#844]
I have been using serilog for a while now and i saw that autofac has some level of supports when it comes to inject ILogger to a constructor...
How about the same sort of thing for Unity?

**Comment by nblumhardt** [comment]
Hi Adrien! I'm not up-to-date with Unity enough for this one right now, but feel free to adapt the code in https://github.com/nblumhardt/autofac-serilog-integration/ if there's anything that's useful.

I'll close this because the Serilog project isn't shipping these kinds of integrations, but if you need more info/have any questions please drop by https://gitter.im/serilog/serilog or post on Stack Overflow and I/other folks familiar with Serilog will do our best to help out.
