### ISSUE TITLE
Sink ownership

### ISSUE THREAD

**Issue by huysentruitw** [serilog/serilog#879]
We have created a simple Sink that sends log messages to an Akka.NET actor. I thought this might be a good candidate to mention on the sinks page?

Repository is https://github.com/CogniStreamer/serilog-sinks-akkaactor

**Comment by merbla** [comment]
Hi @huysentruitw, thanks for the link.

I will add it to the list of provided sinks over [here](https://github.com/serilog/serilog/wiki/Provided-Sinks).  We are not currently accepting new sinks into the organisation unless there is a strong case for it.  It is hard for the team to keep across all the technologies and frameworks in relation to the testing, issues and ongoing releases.

Of course you can raise tickets here and link back to the sink so that we can all help each other.

Thanks again for reaching out, 
Matt

**Comment by nblumhardt** [comment]
This is now listed.
