### ISSUE TITLE
Can't pass original object into logevent (aka Log a JSON Object)

### ISSUE THREAD

**Issue by wparad** [serilog/serilog#912]
For better or worse I actually want to log the exact object DTO.  No matter what we try it seems that I end up with destructured `LogEventProperty`s.  For example when my sink get's called from Serilog the logEvent I receive looks like:

My DTO:
```
class Request
{
	public string HttpMethod { get; set; }
	public Dictionary<string, string> Headers { get; set; }
}
```
Result logEvent Object:
```
{
  "Properties": {
    "Request": {
      "TypeTag": null,
      "Properties": [
        {
          "Name": "HttpMethod",
          "Value": {
            "Value": "POST"
          }
        },
        {
          "Name": "Headers",
          "Value": {
            "Elements": [
              {
              	"Name": "Content-Type",
                "Value": {
                	"Value": "application/json"
                }
              }
            ]
          }
        }
      ]
    }
  }
}

What I want my logEventObject to look like:

```
{
	Request: {
		"HttpMethod": "POST",
		"Headers": {
			"Content-Type": "application/json"
		}
	}
}
```

How can I do this?

**Comment by nblumhardt** [comment]
Hi Warren - which sink are you writing to?

If you want to get the exact object _in memory_ you can use `Destructure.AsScalar<HttpRequest>()` (or whatever the root type name is) and pass it as `"{@Request}"`. If you do this, you'll then need to make sure that any concurrent access to the log event's properties is safe according to whatever rules `HttpRequest` requires.

If you want to control JSON formatting precisely, you can use a destructuring policy to do this, though by the looks of your example its the previous situation that you're in.

Cheers,
Nick

**Comment by wparad** [comment]
I would like a generic way to ensure destructing as a scalar value without having to list out every type.  In my case, we could have very complex DTOs and specifying every single one of them as a Destructure wouldn't make sense.  It was really unintuitive, but what I did manage to do is convert the object to a json.net JObject before logging it, and then used the Destructure to bypass all of the serilog logic.

I spend a very long time trying to figure how to do this, and it seems like a total hack.

The sink doesn't matter for the most part, because it's use happens after the logevent event gets passed there.  At the very least the Destructuring guide should be pronounced as every request to do something like a wanted was answered with "just use @", and to which people were surprisingly happy, and no where in the docs have I seen a solution doing what I want. (Stack exchange, news articles, etc... all had to be answered by the owner of the is repository.)

The other problem with this is that I don't want to create a new object type, I need an anonymous type because I don't want to know all the properties in the bag.  Basically I'm hacking Serilog by logging a serialized string, and then deserializing it in the logevent render.  It makes our code look unhappy.

**Comment by nblumhardt** [comment]
Hmmmm, no, it sounds like you're on the wrong track here somehow. People are probably happy with _just use `@`_ because it generally "just works". Is it the `NameValueCollection` serialization that's the problem?

The sink matters, because the representation you're inspecting looks like Serilog's internal representation of structured data. To get the original structure back out you generally end up using `JsonValueFormatter` or similar.

If you can give us more of an idea of the end-to-end scenario we should be able to figure it out. Cheers!

**Comment by nblumhardt** [comment]
Ah hang on, I see you're not passing in a `NameValueCollection` - it looks like you're trying to serialize a `LogEvent` with JSON.NET - is that correct?

**Comment by wparad** [comment]
That's right, but I can give you the full details.

I am using the CloudWatch sink which takes a logevent and sends it to an API endpoint.  I have the DTO I want to send to the API on one side and the API on the other.  I am currently using Serilog to ferry to the object from the Logger.log method to the api.  But what I get out is a logevent.Properties object which doesn't match my DTO.

I found doing what you said works, but I have to first covert every log object object at the logsite to a JObject, and then destructure that to a scalar.  Then I can at sink time call scalarValue.Value to get back out my object so I can pass it in the API.

Do you have a better suggestion that poluting my log templates with log("{@MagicString}", JObject.FromObject(anonymous object) and poluting my sink formatter with JConvert.Deserialize(logEvent.Properties["MagicString"])

**Comment by nblumhardt** [comment]
Ah, makes senses - thanks.

You should be able to get a JSON document representing the complete event with:

```csharp
var formatter = new JsonFormatter();
var output = new StringWriter();
formatter.Format(logEvent, output);
var json = output.ToString();
```

`JsonFormatter` (included in Serilog.dll) produces a format that should work reasonably well with CloudWatch.

There are some alternatives out there too - see https://github.com/serilog/serilog-formatting-compact for one example (though CloudWatch doesn't like `@`-prefixed property names, or at least couldn't query them last time I tried). The source code for `CompactJsonFormatter` is deliberately very brief, so that it can be copied/pasted and modified to suit new schemas. You might consider using a version of it with `_`-prefixed names, if that suits CloudWatch better.

Cheers,
Nick

**Comment by wparad** [comment]
So although that solves the serialization problem, it fails to provide a solution that would allow injectiong in custom properties at log time.  Some of them are static, but others are dynamic, like the total number of calls so far.  Again, I could do this with a hack, I could deserialize the serialized string from the json formatter create a new object by composing the json object with my dynamic fields and then reserializing it.

I find it strange that we need to have a special json formatter to undo the serilogization of the original objects.  I can see where you are concerned about having the logger modifying the original object, but the fact that resulting object is not a straight forward clone of the original is counter intuitive.

I think if I come up with a generic enough DestructuringPolicy I may be able to get away without having the ugliness at the log call.

Thanks for your help,
Warren

We've discussed enough work arounds to satisfy closing this issue if you want.

**Comment by nblumhardt** [comment]
> allow injectiong in custom properties at log time

If a destructuring policy doesn't permit doing it elegantly, check out `ILogEventEnricher`. It's purpose is to add properties to events, or to objects attached to events, dynamically.

(If the code doing the logging has the information, `ForContext("Property", value)` is a quicker and easier way to do it.)

> strange that we need to have a special json formatter to undo the serilogization of the original objects

Capturing values through the internal object model lets pipeline components add, change or remove properties from objects, or modify the structure of the logged data. It's also the means by which log data is "frozen" so that it's both thread-safe and accurate to work with events on background threads. It also enables more exotic scenarios like [logging `JObject` from JSON.NET as-is](https://github.com/destructurama/json-net/), for example. Lots of interesting stuff to dig into :-)

Sounds like you're unblocked, I'll close the ticket but if you need any further help I'll keep an out here or on Stack Overflow.

**Comment by skomis-mm** [comment]
`JObject` acts like wrapper so with the help of custom wrapper type you can bypass serialization/deserialization with generic destructuring policy that can look like this:
```csharp
sealed class Wrapper 
{
    public Wrapper(object obj)
    {
        Object = obj;
    }

    public object Object { get; }
}

static class ObjectExtensions
{
    public static Wrapper Wrap(this object obj) => new Wrapper(obj);
}

// ...
class DestructureWrapperPolicy : IDestructuringPolicy
{
    public bool TryDestructure(object value, ILogEventPropertyValueFactory propertyValueFactory, out LogEventPropertyValue result)
    {
        result = null;

        if (value is Wrapper)
        {
            result = new ScalarValue(((Wrapper)value).Object);  // for thread safety implement Clone() logic 
        }

        return result != null;
    }
}
```
And at logsite:
```csharp
var request = new {
                    HttpMethod = "POST",
                    Headers = new Dictionary<string, string>()
                        {
                            ["Content-Type"] = "application/json"
                        }
                    };

logger.Information("{@Request}", request.Wrap());
```

It also adds more locality with custom `Wrapper` type than using public/global type so this policy will not take effect accidentally when you pass arbitrary `JObject` or similar public type.
