### ISSUE TITLE
Destructuring depth limiter should try to provide information when erroring

### ISSUE THREAD

**Issue by guillaume86** [serilog/serilog#915]
It would be useful to have a bit more information about the message or object type that triggered the destructuring limit, .

(I have a problem with the selflog outputing gigabytes of "Maximum destructuring depth reached." lines, but the repetition is probably due to the ElasticSearch durable sink trying over and over).

**Comment by nblumhardt** [comment]
Hi Guillaume - no, the sink itself won't attempt to destructure anything IIRC; sounds like you might be getting a message-per-log-event. Is there any chance you can dig further into this? It'd be great to know the cause, so we could figure out what info to add or where the self-log could be improved.

Thanks for the report!

**Comment by guillaume86** [comment]
Hi, 

Unfortunately I wasn't able to reproduce the issue yet, it occured 2 times recently in production (our app creates a selflog file by day, and 2 of the files are ~8gb with this line repeated) but no luck triggering it myself.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. How many log events per day do you generally create?

The events that trigger this message should still be getting written to ES; is it possible to search based on document size and see if that highlights the culprit? Cheers!

**Comment by guillaume86** [comment]
I have around 250.000 log events by weekday, I'll investigate tomorrow, I didn't know the event was still written but if it's the case I will maybe find something with the selflog timestamps and ES documents size.

**Comment by guillaume86** [comment]
I didn't find the problem in my ES logs, but I also use file sinks in a few places so it's maybe in one of those, I'll keep an eye on this.

**Comment by petersondrew** [comment]
This was closed without further discussing the original request, which was to display more information in the SelfLog when this happens. As I'm running into this now, I'd love to submit a PR that simply appended the runtime type information for the object it has failed to destructure to the error message. Would that be acceptable? It would be even nicer if there was a way to access the original log message, but I haven't dug in far enough to know if there's an easy/performant way to do so (especially since we only need it for the failure case).

**Comment by nblumhardt** [comment]
Hi @petersondrew - a PR would be welcome, thanks. I am not sure of all the constraints that code is working under, so there might be a bit of an exploratory process involved, but if we can do it in a way that won't have any other observable perf or reliability impact I think it'd be a worthwhile improvement 👍

**Comment by petersondrew** [comment]
Yes there is a little more too it than I had originally thought ;-)
I'm experimenting with some things now, one issue with the current implementation is that it seems a stack overflow exception can still be thrown for sufficiently wide/deep objects. I don't have a test case yet since it keeps crashing, so I'm trying a build that throws a destructuring exception on maximum depth reached in order to bail all the way back up to the message property level and log the property name there. That will at least get me a test case to work with. I may explore a non-recursive pattern to see if that gives us more flexibility.

**Comment by petersondrew** [comment]
In case you're curious - I'm suing Xamarin and it appears this is a problem with some of the members of the iOS Foundation library (NSMutableString, etc). I have a relatively flat dictionary object whose values are members of the Foundation library and I just need some custom scalar value converters in order to handle them properly. I do still want to find an elegant way of reporting the top level property name and type that triggered the maximum destructuring depth though.

**Comment by triple-vee** [comment]
I can reproduce this reliably in a WebApi service running in a K8 pod (and configures a Console sink). I turn on SelfLog and I see `Maximum destructuring depth reached.` for specific log lines that use Serilog's standard destructuring of POCO objects added as parameters. No circular references.

Maybe it's a stack issue (based on a previous comment)? Running the exact same code on my local Windows box produces no such errors. The service in the K8 pod is running on Alpine Linux. Maybe there's a smaller stack for processes on Linux vs Windows?

**Comment by triple-vee** [comment]
Hi, what's the best way to re-open this? I have a completely reproducible case where this error is generated when I turn on SelfLog. The OP is correct: each one of these selflog errors corresponds to an expected log that is silently dropped. So without selflog diagnostics, one would never know why expected log messages do not show up. This had me scratching my head for days when the happy path was definitely working but the expected log messages didn't show up.

**Comment by nblumhardt** [comment]
Hi @triple-vee - thanks for dropping by. A PR that adds type information to the `SelfLog` entry would be interesting to explore; I don't know what the implementation difficulty will be like, but seems worth a look.

There's no way this info can be surfaced without involving `SelfLog` in some way, though, that I can see.

**Comment by triple-vee** [comment]
@nblumhardt hey thanks for the prompt reply. I looked at where the error is being generated and there's very little context there. I'll have to stare at it some more.

Interestingly, I set maximum depth to 20 and still got the error. And more interestingly, the exact same service runs without selflog errors on Windows and default depth. I'm getting the reproducible errors running the service in a K8 pod with a linux/alpine container. I will try and reproduce it in a local K8 pod.

**Comment by R4cOOn** [comment]
I'm running in that issue as well.  

We have some extra logging during local development and we run into a massive amount of "Maximum destructuring depth reached." error.  
I'm guessing they're coming from EF because we have the "log query" option set.

It's impossible to work out which particular log entry is causing the issue.  
Wouldn't it be possible to dump the "raw" template so we can at least try to work out where the originating log call is?  
How would you recommend we track down the log call that generates these errors otherwise?

Cheers.

**Comment by sungam3r** [comment]
Hi. I have digged into this issue today and think that it can be relatively easy solved at the cost of performance - tracking current destructured object/property in asynclocal or threadlocal. I do not like performance drop and thought about some other way to deal with. Then I focused on statement _Wouldn't it be possible to dump the "raw" template so we can at least try to work out where the originating log call is?_ . Yes, message template can be passed or stored as context as well, but again - from my point of view it's not good to drag along the stack such info (may be wrong). Then I focused on _to work out where the originating log call is_ part. This effectively can be solved by such approach without performance drop on Serilog side:
```cs
 SelfLog.Enable(str =>
        {
            if (str.EndsWith("Maximum destructuring depth reached."))
            {
                var stack = new StackTrace();
                str = str + stack.ToString();
            }
            Console.WriteLine(str);
        });
```
This is how it looks like
![изображение](https://github.com/serilog/serilog/assets/21261007/b5270499-2aea-4078-8ec7-81f5e53eebfa)

Of course you may trim not important stack frames above and below.

**Comment by R4cOOn** [comment]
Thanks, your solution looks like a really good idea.  
I'll try it out!
