### ISSUE TITLE
Missing events in an EF Core app

### ISSUE THREAD

**Issue by arielcloud** [serilog/serilog#928]
https://github.com/aspnet/EntityFramework/issues/7313 describes the issue:

I'm using ef core in asp.net core app, enabled logging, and in my logs I can see every query my app do against db.

the problem is that for every transaction I can see in logs:

[Debug] Beginning transaction with isolation level 'Unspecified'.
but I can't see later in logs any indication if this transaction committed, or rollback.

in the issue above ef team said It seems to be an issue in Serilog.

thanks!

startup.cs:
in startup ():
```
Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .Enrich.FromLogContext()
                .ReadFrom.Configuration(Configuration)
                .CreateLogger();
```
in configure():
```
loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();
            loggerFactory.AddSerilog();
```
appsettings.json:
```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "ConnectionStrings": {
    "BI": "Server=.\\SQLEXPRESS;Database=BI;Trusted_Connection=True;",
   },
  "Serilog": {
    "WriteTo": [
      {
        "Name": "File",
        "Args": {
          "path": "../../log.txt",
          "fileSizeLimitBytes": "1073741824"
        }
      }
    ]
  } 
}
```

**Comment by nblumhardt** [comment]
Hi Ariel,

If you enable [SelfLog](https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics), e.g. `SelfLog.Enable(Console.Error)` do you see any diagnostics printed by Serilog?

Cheers,
Nick

**Comment by arielcloud** [comment]
I added this (`SelfLog.Enable(Console.Error)`); in startup.cs after `loggerFactory.AddSerilog();`.
run transaction again, searched for "error" in log file and found nothing.
thanks!

**Comment by nblumhardt** [comment]
The self-log output won't go into the file - it'll go into whatever `TextWriter` was passed in, so `Console.Error` in this case. HTH!

**Comment by arielcloud** [comment]
not sure where this console is. but tried run with cmd dotnet-run, and also no error there.
is this what u meant? thanks

**Comment by nblumhardt** [comment]
`dotnet run` should probably show the output. Sounds like the problem is elsewhere - if other events are getting to the log file, and no errors are being printed by SelfLog, chances are pretty good the event isn't getting through to the file sink.

If you have a minimal solution that reproduces the issue I can take a look, but otherwise I think you'll need to debug further (try setting "break on all exceptions" in VS) to track this down.

Hope this helps!

**Comment by arielcloud** [comment]
tried  "break on all exceptions" and no exception thrown. 
will try build minimal solution

**Comment by arielcloud** [comment]
I pushed new solution to [https://github.com/arielcloud/serilogMissingEvents](https://github.com/arielcloud/serilogMissingEvents)
I built it exactly by this tutorial: https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db
and then added the above configurations for serilog.
so u can run it. then go to /blogs and create one to see transaction.

**Comment by arielcloud** [comment]
also, tested with what AndriySvyryd suggest 

("You can see all the events if you enable Microsoft Debug-level logging by setting "Microsoft" to "Debug" in appsettings.json and redirecting the console output to a file by setting stdoutLogEnabled to "true" and setting stdoutLogFile to an existing path in web.config")

and it work for me.

**Comment by nblumhardt** [comment]
Thanks for the repro; I won't be able to take a look until next week, so "up for grabs" is anyone else is able to dig in :-)

**Comment by skomis-mm** [comment]
I checked this and indeed some events are not logging through `Serilog.Extensions.Logging` because of [how these events are passed in EF](https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore/Extensions/Internal/CoreLoggerExtensions.cs#L26) and [how they handled through Serilog provider](https://github.com/serilog/serilog-extensions-logging/blob/dev/src/Serilog.Extensions.Logging/Extensions/Logging/SerilogLogger.cs#L98-L107).

EF passes `null` for the `State` and non-empty serializer, which doesn't depend on state. IMO it's seems a bit of hacky since it doesn't say about any meaning to `null`. For structured logging this behavior is counter intuitive at least because it's primarily depends on the `State`. `ConsoleLogger` doesn't have this problem because it doesn't know how to log structured data so [they just use](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs#L101) this fallback serializer as is, passing `null` for the `State` parameter. At the same time not log anything if `State` is null as also seems not correct since `LogEvent` may have `EventId` at least and other properties attached to it (via Scope, for example).
