### ISSUE TITLE
AuditTo.MSSqlServer?

### ISSUE THREAD

**Issue by ThisNoName** [serilog/serilog#952]
The latest Serilog can do AuditTo.File and AuditTo.Logger, but none of the sinks are there.  Seems making a lot more sense to do AuditTo.MSSqlServer or AuditTo.EventCollector (splunk).  I tried chain them together like AuditTo.Logger(a => a.Filter.ByIncludingOnly(...  .WriteTo.MSSqlServer( ... but it fails silently.

Not sure where to ask.  Is this part of the sinks or the Seirlog main library?  Thanks.

**Comment by nblumhardt** [comment]
Hi @ThisNoName - thanks for the note. Auditing support is sink-specific, so an issue or PR to the MS SQL Server sink (https://github.com/serilog/serilog-sinks-mssqlserver) would be the way to move this forward. 

For auditing to work, the sink has to be modified (if necessary) so that it can reliably propagate all errors that may prevent a log event being written. Batched sinks like the SQL Server one don't currently have this option, but it'd be great to add.

Cheers!
