### ISSUE TITLE
Scope life cycle and dependency injection

### ISSUE THREAD

**Issue by plaisted** [serilog/serilog#968]
I have a aspnet core project and am using serilog.

In Startup.Startup I use:
```
Log.Logger = new LoggerConfiguration()
    .Enrich.FromLogContext()
    .WriteTo.RollingFile(env.ContentRootPath + "\\logs\\ExampleLog-{Date}.txt")
    .CreateLogger();
```
In Startup.Configure I use:
```
loggerFactory.AddSerilog();
```

In a class constructed using asp default dependency injection I use:

```
public class ExampleClass
{
    public ExampleClass(ILoggerFactory loggerFactory){
        _logger = loggerFactory.CreateLogger("Example.Logger");
    }
}
```

I am having unexpected behavior regarding ILogger.BeginScope(). If I create a scope on an ILogger in one class such as:
```
using (var scope = _logger.BeginScope("Example:{Example}", "example")
{
    ///long running task
}
```
this scope will often appear on other log messages not logged inside the using block (from other constructed ILoggers in other classes). If I don't dispose of the scope they continue to pile up duplicates indefinitely until the entire service is restarted. I had one such scope that wasn't disposed correctly that was created in the constructor of a class on a newly created ILogger that continued to pile up additional scopes as it was constructed until the scope field was nearly 400,000 characters long in ElasticSearch.

The behavior I was expecting was that the scope would be applied only to the single ILogger instance I called the BeginScope on and not shared across the entire serilog backend. If a new ILogger was created using ILoggerFactory.CreateLogger it would be created with a "clean" scope. Is there a way to achieve this behavior?

**Comment by nblumhardt** [comment]
Hi @plaisted - thanks for the note, sorry about the delay in responding.

Not disposing the result of `BeginScope()` will lead to this kind of crazy behavior. Scopes need to be at a higher level than the individual loggers so that calls from one class to another will carry the scope information through.

Unfortunately, sounds like you just hit one of the rough cases that the API can lead to. Always surrounding a scope block with `using` will take care of this though.

Regards,
Nick
