### ISSUE TITLE
Destructure.ByTransforming is recursive for non-anonymous types

### ISSUE THREAD

**Issue by petersondrew** [serilog/serilog#973]
If I use `Destructure.ByTransforming` to transform `TypeA` by removing sensitive information, and return it as `TypeA` or even `object` such as `Destructure.ByTransforming<Credentials>(c => c?.LogSafe())`, Serilog recursively transforms the returned value until maximum depth is reached.

This is fine for small objects where I can easily construct an anonymous type to return, but for larger objects where I may use something like `MemberwiseClone` to avoid complicated anonymous type construction (and avoid missing new properties as the class definition changes), I'm stuck.

Any thoughts on this? To me, the expectation was that since `ByTransforming` returns object, that no further type analysis would be done, and therefore it would not pass through `ByTransforming` again.

**Comment by nblumhardt** [comment]
Interesting one - thanks for the note.

This isn't really the usage pattern that was originally envisaged for `Destructure.ByTransforming()`, which was added as a shortcut for a "real" `IDestructuringPolicy`, though it really does seem like it should work.

The return value of the delegate will still always need processing because the value has to end up as one of Serilog's internal event property objects (`ScalarValue` and so-on).

I'm not sure what a solution to this would look like that doesn't add more allocation overhead to the pipeline; some investigation needed.

I think you can work around this in an implementation of `IDestructuringPolicy`, by returning `false` if the credentials are "already log-safe":

```csharp
class CredentialDestructuringPolicy : IDestructuringPolicy
{
    public bool TryDestructure(object value, ILogEventPropertyValueFactory propertyValueFactory, out LogEventPropertyValue result)
    {
        if (value is Credentials c && !c.IsLogSafe())
        {
            // Recursive, but the check above will cause termination
            result = propertyValueFactory.CreatePropertyValue(c.LogSafe(), true);
            return true;
        }
        result = null;
        return false; // Let the default policy handle it
    }
}
```

**Comment by petersondrew** [comment]
I think if the workaround is that we use a dedicated destructuring policy then that makes sense. Perhaps all that is really necessary is a note in the documentation?

**Comment by nblumhardt** [comment]
Done! Note added here: https://github.com/serilog/serilog/wiki/Structured-Data#customizing-the-stored-data

Thanks, Peter 👍
